### ISSUE TITLE
Write speed improvement for compressed parquet

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/parquet-dotnet#10]
from @xingchen517:

Hi Team,
Suggesstions:
1 Could you please expose the configuration for gzip CompressionLevel?
2 For Parquet.File.DataColumnWriter.WriteColumn, the GzipStream would be called every time for each value in each column, this would make the process slow, it would be very fast if you make it write first to a BufferStream then write it to GzipStream.
I tried the two things and it gave me 4x faster than before.
Thanks

-----

compression level already implemented, need to add bufferedstream

**Comment by skyyearxp** [comment]
@aloneguid i can speed write compressed parquet 2X~4X faster, but use Parallel only support above .net core V2.

`               //耗时 82秒
               watch_build.Start();
               //DataColumn[] columns = dataFields
               //    .Select(df => bridge.BuildColumn(df, batchArray, batchArray.Length))
               //    .ToArray();
               DataColumn[] columns = dataFields.AsParallel()
                   .Select(df => bridge.BuildColumn(df, batchArray, batchArray.Length))
                   .ToArray();
               watch_build.Stop();

               using (ParquetRowGroupWriter groupWriter = writer.CreateRowGroup())
               {
                  //耗时62秒
                  watch_encode.Start();
                  Parallel.ForEach(columns, column =>
                  {
                     groupWriter.PrepareColumn(column);
                  });
                  watch_encode.Stop();

                  //耗时10秒
                  watch_write.Start();
                  foreach (DataColumn dataColumn in columns)
                  {
                     groupWriter.WriteColumn(dataColumn);
                  }
                  watch_write.Stop();
               }`
