### ISSUE TITLE
Creator metadata field contains placeholders instead of Parquet.Net version and commit hash

### ISSUE THREAD

**Issue by martina-oefelein** [aloneguid/parquet-dotnet#104]
**Version:** Parquet.Net v3.8.1

**Runtime Version:**  .Net 5.

**OS:** macOS.

#### Expected behavior

The creator string embedded in Parquet files should include the Parquet.Net library name and version, like
`Parquet.Net version 3.8.1 (build 7cc73e098ee08943c9a87d4eca4bba1795fbc1ba)`

#### Actual behavior

The creator string is literally `Parquet.Net version %Version% (build %Git.LongCommitHash%)`

### Steps to reproduce the behavior

1. Create a parquet file using Parquet.Net
2. Inspect this parquet file using e.g. `parquet-tools`

#### Code snippet reproducing the behavior

```sh
parquet-tools meta any-file-created-by-Parquet.Net.parquet 2>/dev/null | grep creator
creator:     Parquet.Net version %Version% (build %Git.LongCommitHash%)
```

**Comment by aloneguid** [comment]
fixed in the next release

**Comment by tengl** [comment]
@aloneguid I get this `created_by = Parquet.Net version %Version% (build %Git.LongCommitHash%)`. 

I'm on `4.2.3`, Linux, .Net 6.
