### ISSUE TITLE
Question: Arrays vs. Lists

### ISSUE THREAD

**Issue by rpopovych** [aloneguid/parquet-dotnet#105]
I've read the docs for complex types (list) and my understanding that that the recommendation for arrays with simple types (ints for example) should use repeatable types (https://github.com/aloneguid/parquet-dotnet/blob/master/doc/rows.md#lists).

While I understand the reasoning (performance improvements), I am still in need of creating a list structure with a simple integer type `int[]`. I am placing these parquet files into AWS S3 and querying with Athena and it doesn't seem to handle repeatable types very well (ticket opened on their side).

In the meantime, Is it possible to force an array to serialize as a list using the high level (using `ParquetConvert.Serialize`)?

Example: I have this class:

```csharp
public class MyType
{
    public string Id { get; set; }
    public string Name { get; set; }
    public int[] Array { get; set; }
}
```

When I serialize using `ParquetConvert.Serialize`, I get this schema:

```
message root {
  optional binary Id (UTF8);
  optional binary Name (UTF8);
  repeated int32 Array;
}
```

That's not interpreted correctly by AWS services. They expect the following format:

```
message root {
  optional binary Id (UTF8);
  optional binary Name (UTF8);
  optional group Array (LIST) {
    repeated group bag {
      optional int32 array_element;
    }
  }
}
```

I tried passing in my own schema, but `ListField` doesn't seem to support simple types. I have to pass in a field to the [constructor](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Data/Schema/ListField.cs#L29). My suspicion is that it was intentional to keep simple type arrays as repeatable field **_only_**, but maybe I am missing something.

**Comment by aloneguid** [comment]
closing as seems to be stale
