### ISSUE TITLE
Unable to read RLE_DICTIONARY encoded columns

### ISSUE THREAD

**Issue by plaisted** [aloneguid/parquet-dotnet#107]
**Version:** Parquet.Net v3.8.6

**Runtime Version:** .net 5.0

**OS:** Windows

#### Expected behavior

Parquet.Net is able to open columns that contain dictionary encoded data.

#### Actual behavior
Exception thrown:
```
Parquet.ParquetException
  HResult=0x80131500
  Message=encoding RLE_DICTIONARY is not supported.
  Source=Parquet
  StackTrace:
   at Parquet.File.DataColumnReader.ReadColumn(BinaryReader reader, Encoding encoding, Int64 totalValues, Int32 maxReadCount, ColumnRawData cd)
   at Parquet.File.DataColumnReader.ReadDataPage(PageHeader ph, ColumnRawData cd, Int64 maxValues)
   at Parquet.File.DataColumnReader.Read()
   at Parquet.ParquetRowGroupReader.ReadColumn(DataField field)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

### Steps to reproduce the behavior

Read column from below file

[test.zip](https://github.com/aloneguid/parquet-dotnet/files/6299961/test.zip)

#### Code snippet reproducing the behavior

```csharp
            using (Stream fileStream = System.IO.File.OpenRead("C:\\temp\\test.parq"))
            {
                // open parquet file reader
                using (var parquetReader = new ParquetReader(fileStream))
                {
                    // get file schema (available straight after opening parquet reader)
                    // however, get only data fields as only they contain data values
                    DataField[] dataFields = parquetReader.Schema.GetDataFields();

                    // enumerate through row groups in this file
                    for (int i = 0; i < parquetReader.RowGroupCount; i++)
                    {
                        // create row group reader
                        using (ParquetRowGroupReader groupReader = parquetReader.OpenRowGroupReader(i))
                        {
                            // read all columns inside each row group (you have an option to read only
                            // required columns if you need to.
                            DataColumn[] columns = dataFields.Select(groupReader.ReadColumn).ToArray();

                            // get first column, for instance
                            DataColumn firstColumn = columns[0];

                            // .Data member contains a typed array of column data you can cast to the type of the column
                            Array data = firstColumn.Data;
                            int[] ids = (int[])data;
                        }
                    }
                }
            }
```

I believe the code is in place to support this already, it appears RLE_DICTIONARY encoding (8) effectively replaced PLAIN_DICTIONARY (2) (see https://github.com/apache/parquet-format/blob/master/Encodings.md) but the implementation is nearly the same with the exception of encoding type header. Maybe I'm over-simplifying the change required, I'm not very familiar with the parquet format.

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.

**Comment by JTraill** [comment]
I'm experiencing the same issue at the moment

**Comment by aloneguid** [comment]
Feel free to take ownership of this issue and raise a PR. Let me know if you have any issues 🙂

**Comment by BehroozBahrameh** [comment]
I got a bit confused as this issue is closed.
Currentlyently, it seems the dotnet client does not support it. Whenever you try to read data generated by the default configuration from Python or Java client, you will get `encoding RLE_DICTIONARY is not supported.` .
There are also states from [parquete-fomrat doc](https://github.com/apache/parquet-format/blob/master/Encodings.md) `Using the PLAIN_DICTIONARY enum value is deprecated in the Parquet 2.0 specification. I prefer using RLE_DICTIONARY on a data page and PLAIN on a dictionary page for Parquet 2.0+ files.`

So `Feel free to take ownership of this issue and raise a PR. Let me know if you have any issues` mean the dotnet client not support the ver2.0 specification, and we need to implement it?

**Comment by aloneguid** [comment]
Sorry by bad, RLE is not supported yet, PLAIN is :)

**Comment by BehroozBahrameh** [comment]
@aloneguid thank you for your reply.
As the last question, Is there any plan or estimation for supporting the second version of the specification especially due to the depreciation of the plain?

**Comment by aloneguid** [comment]
Sorry I can't give you even an approximate estimate on this due to the nature of the project. You are always welcome to implement it, no one works on it atm to my knowledge.

**Comment by mukunku** [comment]
Not sure how much sense it makes but I was reading this section on [RLE_DICTIONARY encoding](https://github.com/apache/parquet-format/blob/master/Encodings.md#dictionary-encoding-plain_dictionary--2-and-rle_dictionary--8) and noticed it falls back to plain encoding in some cases. I also noticed that [DataColumnReader.cs](https://github.com/aloneguid/parquet-dotnet/blob/e13d4cd8ed5e10dfadc45b67cde2d30af1a9b36f/src/Parquet/File/DataColumnReader.cs#L269) had a helper for doing the bit packing mentioned in that section. So I thought I'd try using the PLAIN_DICTIONARY logic for RLE_DICTIONARY encoded columns and it worked:

Changed this:
https://github.com/aloneguid/parquet-dotnet/blob/e13d4cd8ed5e10dfadc45b67cde2d30af1a9b36f/src/Parquet/File/DataColumnReader.cs#L242-L248

To this:
```
case Thrift.Encoding.PLAIN_DICTIONARY:
case Thrift.Encoding.RLE_DICTIONARY:
    if(cd.indexes == null)
        cd.indexes = new int[(int)totalValues];
    indexCount = ReadPlainDictionary(reader, maxReadCount, cd.indexes, 0);
    _dataTypeHandler.MergeDictionary(cd.dictionary, cd.indexes, cd.values, cd.valuesOffset, indexCount);
    cd.valuesOffset += indexCount;
    break;
```
Sample file:  [DLIx12_test.zip](https://github.com/aloneguid/parquet-dotnet/files/9642636/DLIx12_test.zip)

Might be a total coincidence 🤷🏼‍♂️ Just thought it was worth mentioning.

**Comment by aloneguid** [comment]
I've updated the parquet spec thrift to latest version in v4, it should be possible to implement this now. As always no promises on timing ;)
