### ISSUE TITLE
Feature Request: Consider use of IReadOnlyList<object> or ReadOnlySpan<object> instead System.Array 

### ISSUE THREAD

**Issue by aersam** [aloneguid/parquet-dotnet#108]
**Version:** Parquet.Net v.3.8

**Runtime Version:** All

**OS:** All

#### Expected behavior

In order to create a Data Column object I am forced to use an Array which often leads to an unnecessary copy of data. Using an interface such as IReadOnlyList<object> would be a lot nicer from a user perspective. If this is not possible, consider using ReadOnlySpan 

I am aware that this is breaking, but is should be fairly simple to change the calling code.

#### Actual behavior

It's always using array which is not as flexible as an interface

**Comment by godefroi** [comment]
Yes! This could significantly improve the allocation profile for our usages.

**Comment by hrabeale** [comment]
Hi,
I would at least opt for extending the interface with something like 
`DataColumn(Array buffer, int offset, int count, int[] repetitionLevels = null);`
Or am I using it wrong, how else am I supposed to write a row group whose size I may not know in advance without copying the whole array?
Thanks

**Comment by aclemmensen** [comment]
@hrabeale I've made a PR adding `offset` and `count` parameters and I'm using it locally with passing in arrays from `ArrayPool<T>`. It seems to work. :)

**Comment by hrabeale** [comment]
Sorry if I'm overusing this thread.
I still cannot get my head around the usage.
Even if they adopt this PR, I still have to pre-allocate one huge array.
Wouldn't it be possible to write to column in batches?
We used the parquet-cpp in a manner similar to this
```csharp
ParquetRowGroupWriter writer;
//...
 for (var i = 0; i < _buffers.Count; ++i)
{
    if (i == _buffers.Count - 1)
    {
        // or use the offset and length instead of copy, if available
        var data = new T[_nextBufferIndex];
        Array.Copy(_buffers[i], data, _nextBufferIndex);

        writer.WriteColumn(new DataColumn(_field, data), closeColumn: true);
    }
    else
        writer.WriteColumn(new DataColumn(_field, _buffers[i]), closeColumn: false);
}
```

**Comment by aloneguid** [comment]
I think you can do that theoretically, but writing in chunks will effectively discard any logical compression. You could use smaller row group size and array pooling?

**Comment by hrabeale** [comment]
> I think you can do that theoretically, but writing in chunks will effectively discard any logical compression. You could use smaller row group size and array pooling?

I am still trying to get a better grasp of the performance implications.
I reckon with a reasonable data page size one may still get a good benefit from compression while maintaining fair access speed, hence the recommendation? (8 KB data page)

Until now we have been using another proprietary column based format where we had batches around 4096 items and the overall compression ration was pretty much the same as if we converted the data to parquet with some other tool.
In some specific cases the compression may even improve as one can choose different compression/encoding strategies per data page.

From what I have seen so far, the common practice with parquet is to have one row group per file.
Then tools like spark are optimized to scale horizontally while sending these row groups to allocated nodes for separate processing.
Or am I getting it wrong?

**Comment by hrabeale** [comment]
Actually as I wrote in the https://github.com/aloneguid/parquet-dotnet/issues/137 I already tested it (writing smaller data pages with parquet-dotnet) and it had close to none impacts on compression.
