### ISSUE TITLE
ParquetReader loses ticks

### ISSUE THREAD

**Issue by MaratFaskhiev** [aloneguid/parquet-dotnet#111]
**Version:** 3.8.6

Here is the test which reproduces behavior. Because NanoTime uses AddMilliseconds method it loses ticks during the conversion to DateTimeOffset type.

```csharp
      [Fact]
      public void ConvertToDateTimeOffset_PreservesTicks()
      {
         var dto = new DateTimeOffset(2021, 05, 14, 17, 52, 31, TimeSpan.Zero);
         dto = dto.Add(TimeSpan.FromTicks(1234567));
         var nanoTime = new NanoTime(dto);
         var convertedDto = (DateTimeOffset) nanoTime;

         Assert.Equal(dto, convertedDto);
      }
```

**Comment by nilsgaeq** [comment]
This is still an issue for some date times, e.g. `2022-02-18T02:24:05.9104071+00:00"`. Happens because of rounding imprecision at ` _timeOfDayNanos = (long)(dt.TimeOfDay.TotalMilliseconds  * 1000000D);` in NanoTime constructor.

**Comment by nilsgaeq** [comment]
Is there a reason one can't simply do `_timeOfDayNanos = dt.TimeOfDay.Ticks * 100` instead, as there are 100 ns in a tick?

**Comment by aloneguid** [comment]
> Is there a reason one can't simply do `_timeOfDayNanos = dt.TimeOfDay.Ticks * 100` instead, as there are 100 ns in a tick?

I think this is a better way, you're correct. PR?

**Comment by aloneguid** [comment]
closing as pr is merged
