### ISSUE TITLE
Question: How to build map data in column based manner

### ISSUE THREAD

**Issue by kurobosi** [aloneguid/parquet-dotnet#115]
**Version:** Parquet.Net v3.8.6

**Runtime Version:** .Net Core 3

**OS:** Windows/Linux

#### Question

Hi.
Thanks for opening this great APIs!

I'm newbie for parquet format and struggle with writing map data repeated in column.
I read though all *.md, especially "Write data", "Complex-Type" and "Row-Based API",
though I could not find a way to write map data in *Column-based* manner.

I succeed writing a map (Dictionary<string, string>) data by using row-based manner (referring row.md in doc directory)
though no luck for making that in column-based. (Could not use MapFields() in column write way.)

Referring "complex-types.md", I kinda feel that it is not a simple way to prepare such map data as "column".  If it is possible, would you give me a resolution for how to write map data in column based manner?

Thank you.

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.
