### ISSUE TITLE
rowgroup sizes of > 5000 cause performance issue ? 

### ISSUE THREAD

**Issue by telferm57** [aloneguid/parquet-dotnet#117]
Hi there, this is more of a question than an issue, sorry if posting in the wrong place. 

I am using parquet files with several million rows - sometimes 100's of millions. The files are created by parquet-dotnet. When consuming these in python with fast parquet or pyarrow , particularly when dask is involved, this causes big performance problems. this is because the rowgroup size is set to 5000, so 200 rowgroups are created per million records, 20,000 per 100 million records. Dask and the parquet engines run off the rowgroup size for creating units of work, which are generally far too small. we're looking for 100-500Mb chunks of data to work with, so a rowgroup size of 500k in our case would be ideal. In the docs it states that a rowgroup size of over 5k  will cause performance issues - is this really the case ?

**Comment by aloneguid** [comment]
You'll have to find the best row group size for your particular use case, there's no golden rule.
