### ISSUE TITLE
Incorrect Definition Level for Null

### ISSUE THREAD

**Issue by matthew-kim-1** [aloneguid/parquet-dotnet#121]
# Incorrect Definition Level for null

**Version:** 3.9.0

**Runtime Version:** .NET Core 3.1

**OS:** MacOSX

Example Parquet Schema

```csharp
Schema schema = new Schema(
    new DataField<int>("required_field_a"),
    new DataField<int?>("optional_field_a"),
    new ListField("list_field",
        new StructField("struct_field",
            new DataField<int>("required_field_b"),
            new DataField<int?>("optional_field_b")
        )
    )
);
```

#### Expected behavior

In the attached **example.parquet** and above **Example Parquet Schema**, the definition level for `optional_field_b` should be 3 when the value is null.

For optional fields that have `MaxDefinitionLevel greater than 1` such as `optional_field_b`, the definition level should not be 0 when null. Instead, the definition level should be `MaxDefinitionLevel minus 1` when the value is null.

Based on above Parquet schema:
|Field             |Value  |Expected Definition Level|
|------------------|-------|-------------------------|
|`required_field_a`|`1`    |0                        |
|`optional_field_a`|`1`    |1                        |
|`optional_field_a`|`null` |0                        |
|`required_field_b`|`1`    |3                        |
|`optional_field_b`|`1`    |4                        |
|`optional_field_b`|`null` |3                        |

#### Actual behavior

Whenever an optional field has a null value, Parquet.Net sets the definition level as 0.

Based on above Parquet schema:
|Field             |Value  |Actual Definition Level|
|------------------|-------|-----------------------|
|`required_field_a`|`1`    |0                      |
|`optional_field_a`|`1`    |1                      |
|`optional_field_a`|`null` |0                      |
|`required_field_b`|`1`    |3                      |
|`optional_field_b`|`1`    |4                      |
|`optional_field_b`|`null` |0                      |

In the attached **example.parquet** and above **Example Parquet Schema**, the definition level for `optional_field_b` is 0 where the value is null. This causes other parquet tools like **Pandas**, **AWS Athena**, and **parquet-tools** to be unable to read the generated parquet file.

For optional fields in the parent level (i.e. `optional_field_a`), definition level is correct when the value is null since `MaxDefinitionLevel - 1`  is equal to `0`.

Definition Level for all required fields work as intended.

### Steps to reproduce the behavior

1. Create a schema that has **StructField** or **ListField**
2. Include an **optional DataField** (i.e. DataField<int?>) inside StructField or ListField
3. Include a null value for the optional DataField in Step 2.
4. Write Parquet File using Parquet.NET

#### Code snippet reproducing the behavior

```csharp
Schema schema = new Schema(
    new DataField<int>("required_field_a"),
    new DataField<int?>("optional_field_a"),
    new ListField("list_field",
        new StructField("struct_field",
            new DataField<int>("required_field_b"),
            new DataField<int?>("optional_field_b")
        )
    )
);

Table table = new Table(schema);

table.Add
(
    1, // required_field_a
    null, // optional_field_a
    new Row[] // list_field
    {
        new Row // struct_field
        (
            2, // required_field_b
            null // optional_field_b
        )
    }
);

using var stream = File.Create("./example.parquet");
using var writer = new ParquetWriter(schema, stream);
writer.Write(table);
```

### Bug Code in Parquet.Net incorrectly calculating Definition Level

This bug exists in two separate classes:

1. `Parquet.Data.BasicDataTypeHandler.cs` Line 141
2. `Parquet.Data.BasicPrimitiveDataTypeHandler.cs` Line 90

**Parquet.Data.BasicDataTypeHandler.cs**

```csharp
protected ArrayView PackDefinitions<TNullable>(TNullable[] data, int maxDefinitionLevel, out int[] definitionLevels, out int definitionsLength, out int nullCount)
    where TNullable : class
{
    definitionLevels = IntPool.Rent(data.Length);
    definitionsLength = data.Length;

    nullCount = 0;
    WritableArrayView<TNullable> result = ArrayView.CreateWritable<TNullable>(data.Length);
    int ir = 0;

    for (int i = 0; i < data.Length; i++)
    {
        TNullable value = data[i];

        if (value == null)
        {
            definitionLevels[i] = 0; // BUG: Definition level is set to 0 for null
            nullCount++;
        }
        else
        {
            definitionLevels[i] = maxDefinitionLevel;
            result[ir++] = value;
        }
    }

    return result;
}
```

**Parquet.Data.BasicPrimitiveDataTypeHandler.cs**

```csharp
private ArrayView PackDefinitions(TSystemType?[] data, int maxDefinitionLevel, out int[] definitionLevels, out int definitionsLength, out int nullCount)
{
    definitionLevels = IntPool.Rent(data.Length);
    definitionsLength = data.Length;

    WritableArrayView<TSystemType> result = ArrayView.CreateWritable<TSystemType>(data.Length);
    int ir = 0;
    nullCount = 0;

    for (int i = 0; i < data.Length; i++)
    {
        TSystemType? value = data[i];

        if (value == null)
        {
            definitionLevels[i] = 0; // BUG: Definition level is set to 0 for null
            nullCount++;
        }
        else
        {
            definitionLevels[i] = maxDefinitionLevel;
            result[ir++] = value.Value;
        }
    }

    return result;
}
```

### Proposed fix

Fix how Definition Level is calculated for null value.

**Before**

```csharp
if (value == null)
{
    definitionLevels[i] = 0; // Definition level is set to 0 for null
    nullCount++;
}
```

**After**

```csharp
if (value == null)
{
    definitionLevels[i] = maxDefinitionLevel - 1; // Updated to calculate definition level
    nullCount++;
}
```

This fix will need to be applied to both `Parquet.Data.BasicDataTypeHandler.cs` and `Parquet.Data.BasicPrimitiveDataTypeHandler.cs`.

[example.parquet.zip](https://github.com/aloneguid/parquet-dotnet/files/6970215/example.parquet.zip)

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.

**Comment by greg0rym** [comment]
I believe that I can also prove this is an issue when creating in `parquet-dotnet` and reading in python pandas. I will open a new issue as suggested.

**Comment by greg0rym** [comment]
I think I have fixed it locally by changing line 556 of `UntypedArrayExtensions` from
```
if(value == null) {
    dest[y] = 0;
}
```

to
```
if(value == null) {
    dest[y] = fillerValue - 1;
}
```

Presumably this only works for `int[]?` and would also need to be applied to the other `PackNullsTypeFast` methods.

**Comment by greg0rym** [comment]
I have had a go at creating a PR for this https://github.com/aloneguid/parquet-dotnet/pull/516.
