### ISSUE TITLE
Column data errors when writing string columns to individual parquets concurrently

### ISSUE THREAD

**Issue by goransh** [aloneguid/parquet-dotnet#122]
**Version:** Parquet.Net v3.9.0 (did not observe this bug with v3.8.6)

**Runtime Version:** Net Core v3.1.402

**OS:** Windows 10 (also observed when running in deployed Azure Functions)

#### Expected behavior

I expect to be able to write string columns to individual parquets concurrently.

#### Actual behavior

Parquet string column entries (rows) are out of order and/or contains wrong entries. I've only observed this with string columns. When I tested it with int32 columns I get the expected result (no bug).

### Steps to reproduce the behavior

Code for all of these steps is in the snippet below.

1. Create an array of strings
2. Write this string array to a column in parquet files concurrently. Each of the parquets will only contain this column (the parquet write process is completely independent between parquets). Add a random delay to simulate a real life scenario.
3. Read the parquet column back and compare it to the initial string array.

#### Code snippet reproducing the behavior

```csharp
[Test]
public async Task ParquetStringColumnConcurrentTest() {
  var correctColumnData = Enumerable
    .Range(0, 1000)
    .Select(number => number.ToString())
    .ToArray();
    
  var tasks = Enumerable.Range(0, 100)
    .Select(
      async _ => {
        await Task.Delay(new Random().Next() % 1000);
        await using var parquetStream = new MemoryStream();

        var numbersField = new DataField("Numbers", DataType.String, hasNulls: false, isArray: false);
        var schema = new Schema(numbersField);

        using (var parquetWriter = new ParquetWriter(schema, parquetStream)) {
            using var rowGroupWriter = parquetWriter.CreateRowGroup();

            var column = new DataColumn(numbersField, correctColumnData);

            rowGroupWriter.WriteColumn(column);
        }

        using var parquetReader = new ParquetReader(parquetStream);

        var readColumn = (string[])parquetReader.ReadEntireRowGroup().First().Data;

        var sequenceEqual = readColumn.SequenceEqual(correctColumnData);
        
        Assert.True(sequenceEqual, $"[{string.Join(", ", readColumn)}]");
      }
    );
  await Task.WhenAll(tasks);
}
```

Here are some of the sequences I get when running this:

```js
[1, 1, 2, 3, 4, 1, 1, 1, 1, 1, 13, 11, 14, 13, 14, 20, 16, 17, 18, 19, 20, 15, 15, 15,...]
[0, 1, 2, 3, 4, 5, 6, 7, 8, ..., 107, 108, 109, 110, 111, 112, 933, 944, 955, 116, 117, 118, 999, 120, 121,...]
```

I also sometimes get an exception when running this:

```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
```

Also: Moving the `correctColumnData` variable inside the async lambda makes no difference.

**Comment by Gevil** [comment]
We seem to be having the same issue when writing tables concurrently with multiple concurrent parquet writers.
This bug managed to corrupt our last months worth of PROD data. so beware of using this 3.9.0 version.
