### ISSUE TITLE
Parquet.ParquetException: 'NewField' does not exist in this file (Schema evolution with ParquetConvert.Deserialize)

### ISSUE THREAD

**Issue by msiddiqi** [aloneguid/parquet-dotnet#126]
**Version:** 3.9.0

**Runtime Version:** .Net Core v 2.2

**OS:** Windows

#### Expected behavior

I am having an issue with schema evolution. Added a new field in my type and it is not able to deserialize now. Can we mark a field optional somhow?

#### Actual behavior

Parquet.ParquetException: 'NewField' does not exist in this file

### Steps to reproduce the behavior

1. Serialize a collection of certain type.
2. Add a field to the type.
3. Deserialize using ParquentConvert.Deserialize<T>("...");

#### Code snippet reproducing the behavior

using (Stream fileStream = System.IO.File.OpenRead("C:\\temp\\parquet\\data.parquet"))
{
     positions = ParquetConvert.Deserialize<MyType>(fileStream);
}

```csharp
//here
```

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.

**Comment by aloha2023** [comment]
@aloneguid ParquetIgnore  attribute will ignore the property no matter it presents or not.
Do you have plan to support ParquetOptional? that means assigning null value to the property, but if the property does present, get the value and assign it

**Comment by aloneguid** [comment]
Unlikely as I don't need it personally. Although PRs are always welcome.

**Comment by VolodymyrSenchak** [comment]
I would also love to have such an attribute like [ParquetOptional].

By the way, just to mimic JSON deserialization behavior - I think that not throwing an error and just applying default value if the field which is declared in class does not exist in the file - would be much more expected behavior.

Or are there any limitations to doing that?
