### ISSUE TITLE
Question: How would I specify CultureInfo.InvariantCulture alongside table.ToString("j")

### ISSUE THREAD

**Issue by RushkaVenter** [aloneguid/parquet-dotnet#133]
**Version:** Parquet.Net v3.9.1

**Runtime Version:** .Net Core 3.1

**OS:** Windows/Linux/MacOSX v etc.

#### Expected behavior

When using ToString("j") on a Parquet.Data.Rows.Row object, the string should return a string formatted like a json string.

#### Actual behavior

When using ToString("j") on a Parquet.Data.Rows.Row object, the string returns a string formatted like a json string, however, the decimal values within the parquet is "12,5" and the json string looks like {"property_name": 12,5, "property_name_2: value} which is not a valid json string.

Normally you would be able to specify CultureInfo.InvariantCulture to get the decimals to convert as "12.5". How would you do that here?

### Steps to reproduce the behavior

1. Create an ParquetReader from a file with decimal values
2. Read the parquet file as a table.
3. Select the first row of the table
4. Convert the the row to string
5. Deserialize the json string

#### Code snippet reproducing the behavior

```csharp
 using (var parquetReader = new ParquetReader(ms))
  {
      var table = parquetReader.ReadAsTable();
      var firstItem = table.FirstOrDefault();
      Console.WriteLine(firstItem.ToString("j"));
      var obj = JsonSerializer.Deserialize<ItemModel>(firstItem.ToString("j"));
  }
```

**Comment by aloneguid** [comment]
this is by design, you're welcome to improve it

**Comment by aloneguid** [comment]
Reopening it. Feel free to raise a PR, contributions are always welcome!
