### ISSUE TITLE
Question:  Serialise of KeyValuePai with byte[] as key

### ISSUE THREAD

**Issue by zweistein22** [aloneguid/parquet-dotnet#138]
I have a simple Dictionary where the Key is a byte[]

Dictionary<byte[], int> ls = new();
            ls.Add(new byte[] { (byte)'a', (byte)'e' }, 1);
            ls.Add(new byte[] { (byte)'b', (byte)'b' }, 3);

This code crashes inside 
ParquetConvert.Serialize<KeyValuePair<byte[], int>>(ls, apghfile,null,CompressionMethod.Snappy,rowGroupSize: 5000,append: false);
  

As I understand I can use a byte[] as a column, and I do so in other occasions.
Why does the above code crash  with  System.ExecutionEngineException  ( near https://github.com/aloneguid/parquet-dotnet/blob/637e06eaaebecd24f7e00b4468d64ee9c7c489a0/src/Parquet/Serialization/Values/ClrBridge.cs#L29 )

Thank you for your help

Andreas

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.
