### ISSUE TITLE
declare a dictionary in a data column

### ISSUE THREAD

**Issue by derekdai1978** [aloneguid/parquet-dotnet#139]
**Version:** Parquet.Net v3.9.1

**Runtime Version:** .Net Framework v5

**OS:** Windows

#### Expected behavior

Please describe how you expect **Parquet.Net** to work.

#### Actual behavior

Please describe how **Parquet.Net** is behaving.

### Steps to reproduce the behavior

1. Step 1.
I defined the datacolumn as below but it says it is not allowed to define dict type
var PropertiesColumn = new DataColumn(new DataField<Dictionary<string, string>>("Properties"), new Dictionary<string, string>[input.Count]);
input.Count is an integer.
2. Step 2.
see the error message like below, 
System.ArgumentException: cannot declare a dictionary this way, please use MapField.at Parquet.Data.DataField.Discover(Type t)at FunctionAppCosmos.WriteCosmosSimDataToSynpsWithParquet.Run(IReadOnlyList`1 input, ILogger log) 

#### Code snippet reproducing the behavior

```csharp
//here
```

**Comment by aloneguid** [comment]
There's an example here - https://github.com/aloneguid/parquet-dotnet/blob/55b509751325c1503adff9cd42a9778281b6ec12/src/Parquet.Test/SchemaTest.cs#L101
