### ISSUE TITLE
Column name 'root' isn't written correctly

### ISSUE THREAD

**Issue by Meingjord** [aloneguid/parquet-dotnet#143]
**Version:** Parquet.Net v.3.9.1

**Runtime Version:** .Net 6.0

**OS:** Windows

#### Expected behavior

Write and Read succeeds for a column named `root`

#### Actual behavior

A file is created that cannot be read back properly

An exception is thrown:
```
System.NotSupportedException: 'Specified method is not supported.'
```

### Steps to reproduce the behavior

1. Write a parquet file with column name `root`
2. Try reading the file (with Parquet.net it gives an exception, reading with python pandas also doesn't work)

Please note that when `root` is renamed to some other name such as `Root` the code works as expected.
Also files written with python pandas that have the column `root` can be read with the Parquet.Net nuget package

#### Code snippet reproducing the behavior

```csharp
using Parquet;
using Parquet.Data;

var columns = new List<DataColumn>();
columns.Add(new DataColumn(new DataField<string>("root"), new string[] { "AAA"}));
columns.Add(new DataColumn(new DataField<string>("other"), new string[] { "BBB" }));
List<Field> fields = new List<Field>();
foreach (DataColumn column in columns)
{
    fields.Add(column.Field);
}

var filename = @"C:\Temp\Parquet\test.parquet";
var schema = new Schema(fields);
System.IO.File.Delete(filename);
using (Stream fileStream = System.IO.File.OpenWrite(filename))
{
    using (var parquetWriter = new ParquetWriter(schema, fileStream))
    {
        using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
        {
            foreach (var column in columns)
            {
                groupWriter.WriteColumn(column);
            }
        }
    }
}

using (Stream fileStream = System.IO.File.OpenRead(filename))
{
    using (var parquetReader = new ParquetReader(fileStream))
    {
        DataField[] dataFields = parquetReader.Schema.GetDataFields();
        for (int i = 0; i < parquetReader.RowGroupCount; i++)
        {
            using (ParquetRowGroupReader groupReader = parquetReader.OpenRowGroupReader(i))
            {
                DataColumn[] c = dataFields.Select(groupReader.ReadColumn).ToArray();
            }
        }
    }
}
```

**Comment by aloneguid** [comment]
Looks like the file is written correctly. Pandas has the same issue as we do, probably not parsing the path correctly same as us ;)
This is fixed and coming in 4.2.2.
