### ISSUE TITLE
Efficiency of run length encoding

### ISSUE THREAD

**Issue by fandrei** [aloneguid/parquet-dotnet#144]
**Version:**
3.9.1

**Runtime Version:**
.NET 5

#### Expected behavior

Remove repetitions in columns.

#### Actual behavior

The file produced by the sample below contains a number of bytes that repeat - 00 FE 04 00 FE 04 00 FE 04 etc. When I compress this file with 7-zip, it becomes almost 200 times smaller.

Is this expected behavior?

#### Code snippet reproducing the behavior

```csharp
			var buf = new int[1024 * 1024];
			for (var i = 0; i < buf.Length; i++)
			{
				buf[i] = 1;
			}

			using (var stream = File.Create("_test.parquet"))
			{
				var field = new DataField<int>("Val");
				var schema = new Schema(field);
				using var parquetWriter = new ParquetWriter(schema, stream);
				using var groupWriter = parquetWriter.CreateRowGroup();
				var column = new DataColumn(field, buf);
				groupWriter.WriteColumn(column);
			}
```

**Comment by aloneguid** [comment]
Yes I think RLE is only used for repetition/definiton levels, and data has no encoding. It's hard to guess which encoding for data is more suitable without compressing with all and choosing best but then performance will suffer. If file size is an issue, you can set CompressionMethod to GZIP in ParquetWriter (it's SNAPPY by default).

**Comment by fandrei** [comment]
@aloneguid but checking for repetitions isn't expensive at all. For instance when I use Spark to save parquet files, it does use RLE and the size of the output file for this sample is just 655 bytes instead of 197168 bytes that this library produces.

**Comment by aloneguid** [comment]
You're welcome to raise a pr for this.

**Comment by fandrei** [comment]
@aloneguid not that I have much time to work on someone else's projects.

**Comment by aloneguid** [comment]
I don't have time to work on your issues either. Good luck 😃

**Comment by fandrei** [comment]
@aloneguid well, it's your project. And RLE is one of important features of Parquet. If you decided to not make a quality implementation, it's up to you :)

**Comment by houseofcat** [comment]
> @aloneguid not that I have much time to work on someone else's projects.

Plenty of time to benefit from some one else's work though.

**Comment by fandrei** [comment]
@houseofcat as well as other people benefit from mine.
