### ISSUE TITLE
Serialize complex objects (inherited class objects, arrays of primitive data types)

### ISSUE THREAD

**Issue by desRp** [aloneguid/parquet-dotnet#145]
**Version:** Parquet.Net v3.9.1

**Runtime Version:** .Net Framework v, .Net Core 3.1

**OS:** Windows/Linux/MacOSX v etc.  Ubuntu 20.04

When serialized complex objects (inherited class objects, arrays of primitive data types) , the Parquet file cannot be read fully it returns only a few properties.

Please describe how you expect **Parquet.Net** to work.

#### Actual behavior

Please describe how **Parquet.Net** is behaving.

### Steps to reproduce the behavior

1. Step 1.
2. Step 2.

#### Code snippet reproducing the behavior

```csharp

 public class BaseClass
    {
        public int Prop1 { get; set; }
    }
    public class Derived1 : BaseClass
    {
        public string StringProp { get; set; } = new string('Y', 1000);
    }

    public class TestClassDerived : Derived1
    {
        public string StringProp2 { get; set; } = new string('Y', 1000);


    }

 List<TestClassDerived> x = new List<TestClassDerived>();
            for (int i = 0; i < maxiteraitons; i++)
            {

                x.Add(new TestClassDerived() { Prop1 = i });

            }

 using var memoryStreamNetD = new MemoryStream();
            ParquetConvert.Serialize(x, memoryStreamNetD, null, CompressionMethod.Gzip);

File.WriteAllBytes("d:\\NetTest1Derived.parquet", memoryStreamNetD.ToArray());
//here
```
[NetTest1Derived.csv](https://github.com/aloneguid/parquet-dotnet/files/7832811/NetTest1Derived.csv)

<!-- Attaching a .parquet file showing the problem is a great way to help speeding this up --
[NetTest1Derived.csv](https://github.com/aloneguid/parquet-dotnet/files/7832812/NetTest1Derived.csv)
[NetTest1Derived.txt](https://github.com/aloneguid/parquet-dotnet/files/7832813/NetTest1Derived.txt)

Please note NetTest1Derived.txt is a parquet file.
>

**Comment by trishmiddleton** [comment]
I have having the same issue.  My data object has no properties.  They are inherited from a base class.  ti.GetDeclaredProperty does not retrieve those types.  So Reflector and Serialize (GenerateCollector) don't work.  I could skip needing Reflector by passing in the Schema but GenerateCollector uses GetDeclaredProperty.  If I change it to classType.GetRuntimeProperty it works.

**Comment by aloneguid** [comment]
very unlikely it will support complex C# object hierarchies as parquet format can't be mapped to it
