### ISSUE TITLE
BasicDataTypeHandler.Write: High CPU cost due to statistics calculation

### ISSUE THREAD

**Issue by tomersh26** [aloneguid/parquet-dotnet#148]
**Version:** Parquet.Net 3.7.7 (but also in latest version)22

**Runtime Version:** .Net Framework 4.8

**OS:** Windows

Hi,

We notice that calling BasicDataTypeHandler.Write incurs a high cost due to statistics calculation. 
We are seeing this quite a lot, and as seen in the below flame chart, the extra cost is coming from the following methods (mainly the first two):
1. Distinct.Count()
2. CompareInfo.Compare(string, string, CompareOptions)
3. string.Compare(string, string) due to currentCulture cost

Note that the total cost of Distinct.Count() and CompareInfo.Compare is twice the cost of WriteOne.
Is it possible to avoid this statistics calculation? Is there any way to mitigate it?

![image](https://user-images.githubusercontent.com/8223197/150701348-8861776d-8973-4c89-b2ea-94635a85038f.png)

**Comment by aloneguid** [comment]
Yes one could disable statistics calculation, but performance issues will surface when querying this data - engine like Spark will have to scan it can calculate all the time. So I'm not going to do that.
