### ISSUE TITLE
Data duplicates

### ISSUE THREAD

**Issue by valdum8** [aloneguid/parquet-dotnet#149]
I am reading a couple of parquet files generated by spark python scripts by a third party developer. 
Some files contains duplicates.
The developer is telling me that I should not read the files sequentially using the parquet.net library because the data is stored as a DataFrame with a log indicating history and changes, so that explain the duplicates. Reading the DataFrame from Databricks does not show duplicates. 

Any solution to this?  

Thanks!
V

**Version:** Parquet.Net v...

**Runtime Version:** .Net Framework v, .Net Core v etc.

**OS:** Windows/Linux/MacOSX v etc.

#### Expected behavior

Please describe how you expect **Parquet.Net** to work.

#### Actual behavior

Please describe how **Parquet.Net** is behaving.

### Steps to reproduce the behavior

1. Step 1.
2. Step 2.

#### Code snippet reproducing the behavior

```csharp
//here
```

**Comment by aloneguid** [comment]
can't read minds
