### ISSUE TITLE
ParquetConvert.Serialize with "append: true" doesn't work

### ISSUE THREAD

**Issue by AlexeyMelnyk** [aloneguid/parquet-dotnet#152]
Parquet.Net 3.9.1
.NET 5, .NET 6
Windows

I assume the reason of the failure is a File.Create call in ParquetConvert.Serialize.
When append it true there should be a File.Open call.
A workaround is to use the ParquetConvert.Serialize overload that accepts a stream object.

#### Expected behavior

ParquetConvert.Serialize works in the append mode

#### Actual behavior

Throws System.IO.IOException: 'The parameter is incorrect. 

### Steps to reproduce the behavior

1. Serialize first batch of records to a file with ParquetConvert.Serialize
2. Serialize the second batch to the file with ParquetConvert.Serialize and setting append flag to true

#### Code snippet reproducing the behavior

```csharp
class Example
{
    public int Integer { get; set; }
}

var fileName = @"Fail.parquet";
var data = new[] { new Example { Integer = 1 } };
ParquetConvert.Serialize(data, fileName);
ParquetConvert.Serialize(data, fileName, append: true);
```

**Comment by houseofcat** [comment]
Possibly related to this?
https://github.com/aloneguid/parquet-dotnet/pull/135
