### ISSUE TITLE
Guid properties are not serialized by ParquetConvert.Serialize

### ISSUE THREAD

**Issue by stefer** [aloneguid/parquet-dotnet#158]
**Version:** Parquet.Net v3.9.1

**Runtime Version:** .Net Core v6

**OS:** Windows/Linux

#### Expected behavior

Guid properties should be serialized when using ParquetConvert.Serialize.
Preferrably, Guids are serialized as [UUID](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#uuid) type.

#### Actual behavior

Guid properties are not serialized.

### Steps to reproduce the behavior

1. Class with public Guid property
2. call ParquetConvert.Serialize

#### Code snippet reproducing the behavior

```csharp
using Parquet;
using System.IO;

class Test {
  public int IntProperty { get; set; } = 23;
  public Guid GuidProperty { get; set; } = Guid.Empty;
}

public class Program {
    public static void Main() {
        var values = Enumerable.Range(1, 20).Select(x => new Test {IntProperty = x, GuidProperty = Guid.NewGuid() });
    
        using (var stream = File.Create("C:\\temp\\NoGuid.parquet")) {
            ParquetConvert.Serialize(values, stream);
        }
    }
}
```

[NoGuid.zip](https://github.com/aloneguid/parquet-dotnet/files/8554277/NoGuid.zip)

**Comment by BillyHouston** [comment]
Also interested in this one - saw there was a fork a while back to add Guid/UUID support but it was never merged

**Comment by aloneguid** [comment]
class serialization is experimental so it's not supported at the moment
