### ISSUE TITLE
Support of definition level

### ISSUE THREAD

**Issue by ramon-garcia** [aloneguid/parquet-dotnet#160]
As explained in [this blog entry about Parquet](https://blog.twitter.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet), it is necessary to include a definition level in optional columns in order to rebuild a register from column data.
Parquet.net examples show [how to include a repetition level with the data](../tree/master/docs/complex-types.md) but I can't find any public API that allows one to include definition level.

**Comment by aloneguid** [comment]
@ramon-garcia definition levels are calculated by this library. Have a look at one of the `DataColumn` internal constructors which accepts definition levels, repetition levels and dictionary indexes. Please reopen if you have more questions

**Comment by aloneguid** [comment]
Sorry not sure I understand.

**Comment by ramon-garcia** [comment]
Definition levels are used to disambiguate at what level a value is null when one has nested structures. This is explained in the [Dremel](https://static.googleusercontent.com/media/research.google.com/es//pubs/archive/36632.pdf) paper.

So if one stores data about events with the following schema:

```
message Event {
   uint64 id = 1; 
   message Source {
      message Computer {
           string name = 1;
     };
    Computer sourceComputer = 1;
  }
  Source eventSource = 2;
  string text = 3;
}
```

If there is a null value in the column Event.Source.Computer.name, it may be because the nested field Event.Source.Computer.name is null, or perhaps because Event.Source.Computer is null, or perhaps because Event.Source is null for the current event. The definition level states which one of these is the case.

So, if one calls the column API  groupWriter.WriteColumn for the column Event.Source.Computer.name with an array of values, and one of these values is null, how can the library know at what nesting level is the field null?

**Comment by aloneguid** [comment]
Ah, I see why it's confusing. In Parquet format structures are encoded as normal column. So in your previous example, `Event` will be written as 4 columns:
- `id`
- `Source.Computer.Name`
- `eventSource`
- `text`

It's sort of irrelevant that the second column is part of a structure, on low level parquet columns do not have any hierarchy. The only way user knows it's part of the structure is from schema definition. This library will extract it into class or row, depending on what you are using. 

In addition to that, this library accepts both arrays of values and **nullable** array of values, mostly not to bore you as a user. So if you are specifying a nullable array of ints, for example `[1, 2, null, 4]`, it will split this array into:
- non-nullable value array: `[1, 2, 4]` and definitions array `[1, 1, 0, 1]`. 

Also refer to [this page in docs](https://github.com/aloneguid/parquet-dotnet/blob/master/docs/complex-types.md).

**Comment by ramon-garcia** [comment]
Well, it is not a vital issue. But definition levels exists for this purpose: so that one can completely reconstruct the original structure from the columns, and make queries, aggregations, ... where there is a difference between a null value and a null enclosing structure.

Then it should be documented.
