### ISSUE TITLE
Import the exported parquet file where column is type of array read fail

### ISSUE THREAD

**Issue by wwwolfsasa** [aloneguid/parquet-dotnet#163]
**Version:** Parquet.Net v3.9.1

**Runtime Version:** .Net Standard

**OS:** Windows

#### Expected behavior

In the ‘Table’ object, data type of the second column is double array.
Before write to a MemoryStream it is still doing greate.

![1](https://user-images.githubusercontent.com/76436844/170024070-d9152795-008c-4dee-b571-2f95668975e8.png)

After parquet file export, and then I try to read it by simple viewer or the other third party viewer.

I found that data of column 2 at each row becomes to only ‘double’
![2](https://user-images.githubusercontent.com/76436844/170024120-a37f93a7-0b10-4724-bc5c-115ec86d47ab.png)

Is there any thing I make mistakes or miss some thing to export parquet file.

Thanks for yours help.
Best regards.

**Comment by aloneguid** [comment]
Not sure I understand, can you attach a reproducible code snippet?

**Comment by aloneguid** [comment]
Feel free to reopen if this is still an issue.
