### ISSUE TITLE
Allow Scale of 0 for Decimal Types

### ISSUE THREAD

**Issue by aromano-resurgent** [aloneguid/parquet-dotnet#165]
**Version:** Parquet.Net v 3.9.1

**Runtime Version:** .Net Framework v net472

**OS:** Windows10

#### Expected behavior

I would expect parquet-dotnet to allow scale = 0 for DecimalDataFields

#### Actual behavior

parquet-dotnet raises an error:

`System.ArgumentException: 'scale cannot be less than 1
Parameter name: scale'`

### Steps to reproduce the behavior

Attempt to create a parquet schema with a DecimalDataField with scale = 0

#### Code snippet reproducing the behavior

```csharp
var schema_fields = new Parquet.Data.DataField[]
{
    new Parquet.Data.DecimalDataField(name: "Test", precision: 38, scale: 0)
};
var parquetSchema = new Parquet.Data.Schema(schema_fields);
```

I know it is a bit of an odd request, but I often work with legacy SQL Server Databases that use data types such as Decimal(20,0) as a way to allow large integers numbers.

Let me know if I can provide any more information.

**Comment by aloneguid** [comment]
Fair enough, however you are better to use integer types instead (int, long, BigInteger) if there is no precision part. They have much more compact representation and are generally faster.

**Comment by aloneguid** [comment]
Seems like you can create zero precision number with other libraries, so worth implementing it here too.

**Comment by aloneguid** [comment]
I've checked that 4.4.4 actually allows zero scale
