### ISSUE TITLE
Convert Parquet.Data.Rows.Table to System.Data.DataTable

### ISSUE THREAD

**Issue by DSpada** [aloneguid/parquet-dotnet#167]
Hi to everyone,

There is a way to convert queckly Parquet.Data.Rows.Table to System.Data.DataTable?

I need di put some parquet files into a PostgreSQL DB, but with Parquet.Data.Rows.Table i need to map parquet rows and columns type and I can't make BulkInsert into DB as is Table

>        using (Stream fileStream = File.OpenRead(fileInfo.FullName))
>        {
>              using (var parquetReader = new ParquetReader(fileStream))
>               {
>                    var dt = parquetReader.ReadAsTable(); //Parquet.Data.Rows.Table
>                }
>        }
  
Thank you so much in advance.

**Comment by aloneguid** [comment]
Sorry but this is just a simple data conversion task which is outside of this project's scope.
