### ISSUE TITLE
Writing null to a struct field throws null reference exception

### ISSUE THREAD

**Issue by vigneshc** [aloneguid/parquet-dotnet#171]
**Version:** Parquet.Net v...

**Runtime Version:** .Net Framework 472

**OS:** Windows

#### Expected behavior

Parquet schema with 2 nested structs throws a null reference exception when writing using Row based api in RowValidator.cs.
This happens when use set one of the nested structs to null.

#### Actual behavior

Throws null reference exception with below stacktrace.
`
    System.NullReferenceException: Object reference not set to an instance of an object.
  Stack Trace: 
    RowValidator.Validate(Row row, IReadOnlyList`1 fields)
    RowValidator.Validate(Row row, IReadOnlyList`1 fields)
    Table.Add(Row item)
`
Based on [Validate](https://github.com/aloneguid/parquet-dotnet/blob/3f3f070419ab1a9f9a86f2cc0f39ce07aaf92673/src/Parquet/Data/Rows/RowValidator.cs) method, we would get null reference exception. 
Is there a way to write null?
#### Code snippet reproducing the behavior

```csharp
            var schema = new Schema(
                new StructField("c1", new DataField("ic2", DataType.String), new DataField("ic2", DataType.String)),
                new StructField("c2", new DataField("ic2", DataType.String), new DataField("ic2", DataType.String)));
            var row = new Row(
                new Row("t2", "t22"),
                null);
            var stream = new MemoryStream();

            using (var parquetWriter = new ParquetWriter(schema, stream))
            {
                using (var rowGroup = parquetWriter.CreateRowGroup())
                {
                    var parquetTable = new Table(schema);

                    parquetTable.Add(row);
                    rowGroup.Write(parquetTable);
                }
            }
```
Updating RowModelTests with null also reproduces it.

```csharp
      [Fact]
      public void Struct_write_read()
      {
         var table = new Table(
            new Schema(
               new DataField<string>("isbn"),
               new StructField("author",
                  new DataField<string>("firstName"),
                  new DataField<string>("lastName"))));
         var ms = new MemoryStream();

         table.Add("12345-6", new Row("Ivan", "Gavryliuk"));
         table.Add("12345-7", new Row("Richard", "Conway"));
         table.Add("12345-8", null); // null value for struct field.

         Table table2 = WriteRead(table);

         Assert.Equal(table.ToString(), table2.ToString(), ignoreLineEndingDifferences: true);
      }

```

**Comment by vigneshc** [comment]
Updating RowValidator.cs to skip check for null results in a null reference later in RowsToDataColumnsConverter.cs

**Comment by aloneguid** [comment]
Thanks, feel free to raise a PR, I can't get free time for this any time soon.
