### ISSUE TITLE
Error when one of the columns shares the same name of the parquet table

### ISSUE THREAD

**Issue by azalpacir** [aloneguid/parquet-dotnet#172]
**Version:** 3.9.1

**Runtime Version:** .Net6

**OS:** Windows/Linux/

#### Expected behavior

The "ReadAsTable" method should not throw an error.

#### Actual behavior

The "ReadAsTable" or any other other methods that gets the data columns is returning an error: "The specified method is not supported."

### Steps to reproduce the behavior

1. Create parquet table with "account" as the name.
2. Add a column also with the name "account"

#### Code snippet reproducing the behavior

```csharp
using var fileReader = new StreamReader(folderLocation);
using var parquetReader = new ParquetReader(fileReader.BaseStream, new ParquetOptions { TreatBigIntegersAsDates = false });

var table = parquetReader.ReadAsTable();
```

Issue happens to the parquet files that has a table name the same with it one of it's columns. It's messing up with the List of SchemaElements in the metadata. 

![image](https://user-images.githubusercontent.com/30047281/180721107-8154aee9-dfaa-4053-97fd-a50bae8e05d0.png)

**Comment by aloneguid** [comment]
fixed in v4
