### ISSUE TITLE
Is dictionary encoding supported in writer?

### ISSUE THREAD

**Issue by volgunin** [aloneguid/parquet-dotnet#176]
**Version:** Parquet.Net 3.9.1

**Runtime Version:** .NET 6

**OS:** Wndows

#### Expected behavior

Being able to specify the type of encoding to use.

#### Actual behavior

Parquet files with large number of repetitive rows are significantly larger compared to ones generated by Java libraries.

**Comment by aloneguid** [comment]
It is supported but there's no option exposed to enforce it in writer. Happy for you to take ownership on this.

**Comment by volgunin** [comment]
Is the issue only in passing the encoding parameter to writer? I saw that reader uses PLAIN_DICTIONARY enum, but nothing like that in writer.

**Comment by aloneguid** [comment]
Sorry yes, PLAIN is supported, but we need to implement an encoder for this new one. I think it wasn’t in the spec at the time of writing dictionary encoding.
