### ISSUE TITLE
ArgumentException 'Stream was not readable' when attempting to write to file in append mode.

### ISSUE THREAD

**Issue by jkindwall** [aloneguid/parquet-dotnet#178]
**Version:** Parquet.Net v4.0.0

**Runtime Version:** .Net 6.0

**OS:** Windows

#### Expected behavior

I open a file to for writing in append mode and it appends data to the file.

#### Actual behavior

I get a "Stream was not readable" exception when I try to create the ParquetWriter object with append: true.

### Steps to reproduce the behavior

see Code snippet

#### Code snippet reproducing the behavior

```csharp
            using Stream file = File.OpenWrite(this.Settings.OutputFile);
            using ParquetWriter parquetWriter = await ParquetWriter.CreateAsync(schema, file, append: true); // <== Exception occurs here
            using ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup();
```

**Comment by RoelofSpijker** [comment]
`OpenWrite` creates a non-readable stream (https://learn.microsoft.com/en-us/dotnet/api/system.io.file.openwrite?view=net-6.0#returns). Appending to a parquet file involves reading as you can't simply add to the end, due to the structure of the files. The documentation explains this as follows:

> Note that you have to specify that you are opening ParquetWriter in append mode in it's constructor explicitly - new ParquetWriter(new Schema(id), ms, append: true). Doing so makes parquet.net open the file, find the file footer and delete it, rewinding current stream posiition to the end of actual data. Then, creating more row groups simply writes data to the file as usual, and .Dispose() on ParquetWriter generates a new file footer, writes it to the file and closes down the stream.

You can use File.Open with ReadWrite access.
