### ISSUE TITLE
NULL in struct field writer DL=0 instead of 1

### ISSUE THREAD

**Issue by exyi** [aloneguid/parquet-dotnet#185]
**Version:** 4.0.0

Let's say I have schema `optional a: { optional x: int32, optional y: int32 }`

When I write [1, null] into ColumnData of a.x and [1, 1] into a.y, it produces definition levels

```
a.x           a.y
2              2
0              2
```

However, definition level = 0 indicates that the entire struct is null (as far as I understand it https://blog.twitter.com/engineering/en_us/a/2013/dremel-made-simple-with-parquet). DL=1 should be used instead.

Pyarrow and pqrs interprets it "correctly" - as nulls set in the field, but DuckDB interprets it as the entire field being null.

Generally, I'd like to explicitly specify definition levels for my columns in order to distinguish struct set to null and struct with fields set to null. Would it be possible to add an API for it?

**Comment by aloneguid** [comment]
yes please go ahead
