### ISSUE TITLE
Bug in DataColumnReader.ReadPageData when using Azure Data Lake SDK

### ISSUE THREAD

**Issue by Sense545** [aloneguid/parquet-dotnet#188]
**Version:** Parquet.Net v4.1.0

**Runtime Version:** .Net 6

**OS:** Windows

#### Expected behavior

ReadPageData should read whole page

#### Actual behavior

It only reads the first bytes returned from _inputStream.ReadAsync

#### Why this happens

The [Stream.Read](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0) interface specifies that Read can return less than the supplied count:
> The total number of bytes read into the buffer. This can be less than the number of bytes allocated in the buffer if that many bytes are not currently available, or zero (0) if the end of the stream has been reached.

Azure Data Lake SDK [LazyLoadingReadOnlyStream.ReadInternal](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/LazyLoadingReadOnlyStream.cs#L224-L234
) does this when the requested number of bytes is larger than the number of bytes remaining in the buffer.

[DataColumnReader.ReadPageData](https://github.com/aloneguid/parquet-dotnet/blob/67173d7534240f65fb4ced0372d8ef6bc4459a2b/src/Parquet/File/DataColumnReader.cs#L140) only calls `_inputStream.ReadAsync` once and does not check its return value. It should keep calling it as long as it returns > 0 and not all requested data has been returned yet. Similar to what is done [here in Azure Data Lake SDK](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/LazyLoadingReadOnlyStream.cs#L265-L286)

### Steps to reproduce the behavior

1. Create a DataLakeFileClient
2. Open a read stream with a small buffer size (e.g. 256kb)
3. Read a parquet file where the compressed page size > 256kb

#### Code snippet reproducing the behavior

The issue can also be reproduced by using a dumb stream implementation that only returns one byte at the time:

```csharp
using Parquet;
using Parquet.Data;

internal class Program
{
    private static async Task Main(string[] args)
    {
        DataField field = new("date", typeof(DateTimeOffset));
        Schema schema = new(field);

        using MemoryStream memoryFileStream = new();
        using (ParquetWriter parquetWriter = await ParquetWriter.CreateAsync(schema, memoryFileStream))
        {
            using ParquetRowGroupWriter rowGroupWriter = parquetWriter.CreateRowGroup();
            DateTimeOffset[] data = new DateTimeOffset[10000];
            for (int i = 0; i < 10000; i++) data[i] = DateTimeOffset.UtcNow.AddMilliseconds(i);
            await rowGroupWriter.WriteColumnAsync(new DataColumn(field, data, 0, 10000));
        }

        int fileSize = (int)memoryFileStream.Length;
        using MemoryStream memoryStreamCopy = new(memoryFileStream.GetBuffer(), 0, fileSize);
        using DumbStream bufferedStream = new(memoryStreamCopy);
        using ParquetReader parquetReader = await ParquetReader.CreateAsync(bufferedStream);
        for (int iterations = 0; iterations < 100; iterations++)
        {
            using ParquetRowGroupReader rowGroupReader = parquetReader.OpenRowGroupReader(0);
            await rowGroupReader.ReadColumnAsync(field);
        }
    }

    internal class DumbStream : Stream
    {
        private readonly MemoryStream _memoryStream;
        public DumbStream(MemoryStream memoryStream) { _memoryStream = memoryStream; }
        public override bool CanRead => true;
        public override bool CanSeek => true;
        public override bool CanWrite => false;
        public override long Length => _memoryStream.Length;
        public override long Position { get => _memoryStream.Position; set => _memoryStream.Position = value; }
        public override void Flush() { }
        public override int Read(byte[] buffer, int offset, int count) => _memoryStream.Read(buffer, offset, 1);
        public override long Seek(long offset, SeekOrigin origin) => _memoryStream.Seek(offset, origin);
        public override void SetLength(long value) => throw new NotSupportedException();
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken) => Task.FromResult(Read(buffer, offset, count));
    }
}
```

**Comment by Sense545** [comment]
Here is a patch that fixes the issue. Would it be possible to get this merged and a new version released?

```patch
index 195c9d8..d9fc456 100644
--- a/src/Parquet/File/DataColumnReader.cs
+++ b/src/Parquet/File/DataColumnReader.cs
@@ -137,7 +137,14 @@ namespace Parquet.File {
         private async Task<IronCompress.DataBuffer> ReadPageData(Thrift.PageHeader ph) {

             byte[] data = ArrayPool<byte>.Shared.Rent(ph.Compressed_page_size);
-            await _inputStream.ReadAsync(data, 0, ph.Compressed_page_size);
+
+            int totalBytesRead = 0, remainingBytes = ph.Compressed_page_size;
+            do {
+                int bytesRead = await _inputStream.ReadAsync(data, totalBytesRead, remainingBytes);
+                totalBytesRead += bytesRead;
+                remainingBytes -= bytesRead;
+            }
+            while(remainingBytes != 0);

             if(_thriftColumnChunk.Meta_data.Codec == Thrift.CompressionCodec.UNCOMPRESSED) {
                 return new IronCompress.DataBuffer(data, ph.Compressed_page_size, ArrayPool<byte>.Shared);
```

**Comment by aloneguid** [comment]
@Sense545 of course, please raise a PR and i'll merge. Looks good.
