### ISSUE TITLE
DllNotFoundException on nironcompress when running in Azure Function App

### ISSUE THREAD

**Issue by Russ256** [aloneguid/parquet-dotnet#190]
Version:  4.1.0

Runtime Version: .Net 6

OS: Windows

Issue:
When attempting to write parquet file in an Azure function an exception is thrown.  Works ok when running locally.

Result: Failure Exception: System.AggregateException: One or more errors occurred. (Unable to load DLL 'nironcompress' or one of its dependencies: The specified module could not be found. (0x8007007E)) ---> System.DllNotFoundException: Unable to load DLL 'nironcompress' or one of its dependencies: The specified module could not be found. (0x8007007E) at IronCompress.Iron.compress(Boolean compress, Int32 codec, Byte* inputBuffer, Int32 inputBufferSize, Byte* outputBuffer, Int32* outputBufferSize) at IronCompress.Iron.CompressOrDecompress(Boolean compressOrDecompress, Codec codec, ReadOnlySpan`1 input, Nullable`1 outputLength) at IronCompress.Iron.Compress(Codec codec, ReadOnlySpan`1 input, Nullable`1 outputLength) at Parquet.File.Compressor.Compress(CompressionMethod method, ReadOnlySpan`1 input) at Parquet.File.DataColumnWriter.WriteColumnAsync(DataColumn column, SchemaElement tse, IDataTypeHandler dataTypeHandler, Int32 maxRepetitionLevel, Int32 maxDefinitionLevel, CancellationToken cancellationToken) at Parquet.File.DataColumnWriter.WriteAsync(List`1 path, DataColumn column, IDataTypeHandler dataTypeHandler, CancellationToken cancellationToken) at Parquet.ParquetRowGroupWriter.WriteColumnAsync(DataColumn column, CancellationToken cancellationToken) at VentientReportImport.Import.WriteParquetAsync(String windFarm, Collection`1 data)

**Comment by Russ256** [comment]
On further investigation this is a 32-bit issue.  It works if the function app is using 64-bit runtime but not if using 32-bit runtime.  Unfortunately to run in 64-bit you have to run the function app in at least a basic service plan which is chargeable, you can only run 32-bit on the dev app service plans.

Can you support the 32-bit runtime?

**Comment by aloneguid** [comment]
It's only using native code for codecs not available for .NET so if you choose no-compression or one of gzip, brotli it will work.
I'm looking into supporting ARM natively at the moment, 32-bit support can be added at the same time - as always no promises on timelines.

**Comment by aloneguid** [comment]
should work in 4.1.2
