### ISSUE TITLE
Regression: ParquetWriter.CreateRowGroup calls Stream.Position for no reason

### ISSUE THREAD

**Issue by Pansynchro-Admin** [aloneguid/parquet-dotnet#192]
**Version:** Parquet.Net v... 4.10

**Runtime Version:** .Net 6

**OS:** Windows

#### Expected behavior

Writing to a writeable stream should not throw exceptions.  This was true in v3.x.

#### Actual behavior

Writing to a write-only stream that does not support `Position` throws an exception when calling `CreateRowGroup`, because it instantiates a `new ParquetRowGroupWriter()`, and [the constructor asks for the stream's `Position` property.](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/ParquetRowGroupWriter.cs#L44)

The only thing it does with this value is to store it to a field that is never used.  So not only is this throwing exceptions, it is doing so completely pointlessly.

#### Code snippet reproducing the behavior

```csharp
var pipe = new System.IO.Pipelines.Pipe();
var input = pipe.Writer.AsStream(); //write-only stream
var pWriter = new ParquetWriter(GetSchema(), input); //GetSchema should simply return any valid schema
var group = writer.CreateRowGroup(); //explodes here
```

**Comment by aloneguid** [comment]
Correct, thanks. Care to raise a PR?

**Comment by Pansynchro-Admin** [comment]
All right, fixing this was a bit of a hack, interposing a new stream that will keep track of the current position even when the writeable stream won't.  Thankfully there's no code in here that actually tries to *change* the position, only read it.  But it works, and it will only do this for streams that report `CanSeek: false`.  For all other streams, the behavior remains unchanged.

**Comment by Pansynchro-Admin** [comment]
Thanks for merging the fix.  Can you reply here to let me know when it's in Nuget?

**Comment by aloneguid** [comment]
out in 4.1.1 ;)
