### ISSUE TITLE
macos arm m1 fails due to missing `nironcompress` shared lib

### ISSUE THREAD

**Issue by annerajb** [aloneguid/parquet-dotnet#195]
**Version:** 
4.1.0

**Runtime Version:**
6.0

**OS:** Windows/Linux/MacOSX v etc.
macos arm m1 12.6

#### Expected behavior
(it starts)

Please describe how you expect **Parquet.Net** to work.
It starts and does not fail for pinvoke

#### Actual behavior
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'nironcompress' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libnironcompress, 0x0001): tried: 'libnironcompress' (no such file), '/usr/local/lib/libnironcompress' (no such file), '/usr/lib/libnironcompress' (no such file), '/Users/emed/repos/incident-42/parquet-sessionid-util/libnironcompress' (no such file)
   at IronCompress.Iron.compress(Boolean compress, Int32 codec, Byte* inputBuffer, Int32 inputBufferSize, Byte* outputBuffer, Int32* outputBufferSize)
   at IronCompress.Iron.CompressOrDecompress(Boolean compressOrDecompress, Codec codec, ReadOnlySpan`1 input, Nullable`1 outputLength)
   at IronCompress.Iron.Decompress(Codec codec, ReadOnlySpan`1 input, Nullable`1 outputLength)
   at Parquet.File.Compressor.Decompress(CompressionMethod method, ReadOnlySpan`1 input, Int32 outLength)
   at Parquet.File.DataColumnReader.ReadPageData(PageHeader ph)
   at Parquet.File.DataColumnReader.ReadDataPage(PageHeader ph, ColumnRawData cd, Int64 maxValues)
   at Parquet.File.DataColumnReader.ReadAsync(CancellationToken cancellationToken)

```
### Steps to reproduce the behavior

1. Step 1.
2. Step 2.

#### Code snippet reproducing the behavior

```csharp
//here
using(Stream fileStream = System.IO.File.OpenRead("filethatexists.parquet")) {
    // open parquet file reader
    using(ParquetReader parquetReader = await ParquetReader.CreateAsync(fileStream)) {
        DataField[] dataFields = parquetReader.Schema.GetDataFields();

        // enumerate through row groups in this file
        for(int i = 0; i < parquetReader.RowGroupCount; i++) {
            // create row group reader
            using(ParquetRowGroupReader groupReader = parquetReader.OpenRowGroupReader(i)) {
                // read all columns inside each row group (you have an option to read only
                // required columns if you need to.
                var columns = new DataColumn[dataFields.Length];
                for(int c = 0; c < columns.Length; c++) {
                    columns[c] = await groupReader.ReadColumnAsync(dataFields[c]); <<<< fails
}
}
}
}
}
```

**Comment by aloneguid** [comment]
The file is using a compression codec not available in .NET, and ironcompress is not compiled for ARM yet, this is coming.

**Comment by annerajb** [comment]
I reverted to the previous version of parquet-dotnet and it loaded the file
as a workaround

**Comment by aloneguid** [comment]
That's fine, but old version is using a self-baked C# port of snappy which is slow and buggy, aloneguid/ironcompress#1 is work in progress on this.

**Comment by aloneguid** [comment]
@annerajb this **should** work in 4.1.1. Please check as I don't have M1 on hand and it's not available as a build agent.

**Comment by gabynevada** [comment]
Working for me on M1 with the latest build. Thanks!

**Comment by deanro** [comment]
I just tried using the Visual Studio ARM build running in Windows 11 ARM using Parallels on an M1 Mac and I'm seeing the following error on 4.1.1.

System.DllNotFoundException : Unable to load DLL 'nironcompress' or one of its dependencies: The specified module could not be found. (0x8007007E)

Looking at my build output I can see that nironcompress.dll is in the following directory

\Debug\net7.0\runtimes\win-x64\native

But it's not in any of the others like win-arm64, or linux-arm64

**Comment by aloneguid** [comment]
Only x64 is supported on Windows. ARM and x86 is in the works.

**Comment by deanro** [comment]
Thanks for the response. Nothing critical for us, so I'll just keep monitoring the thread/releases.
