### ISSUE TITLE
Version 4.1 ONLY has async methods, which do not cooperate with Parallel.ForEach

### ISSUE THREAD

**Issue by MarcMeketonVillanova** [aloneguid/parquet-dotnet#196]
**Version:** Parquet.Net v4.1.1

**Runtime Version:** .Net Core v3.1

**OS:** Windows 10.

#### Expected behavior

For reasons I do not understand, my C#8.0 in .Net Core v3.1 does not have Parallel.ForEachAsync.

So when I needed to use Parallel.For, I had to go back to Parquet.Net v3.10 to use the non-asynchronous parquet writer.

It would have been nice in v4+ to have the option of not doing async writing.

**Comment by aloneguid** [comment]
There will be no blocking calls going forward. Sorry.
