### ISSUE TITLE
Installing on 4.8 .NetFramework

### ISSUE THREAD

**Issue by mbabcock74** [aloneguid/parquet-dotnet#197]
**Version:** Parquet.Net v 4.1.1

**Runtime Version:** .Net Framework v 4.8 , .Net Core v etc.

**OS:** Windows

#### Expected behavior

Able to install Parquet.NET on 4.8 .Net Framework

#### Actual behavior

Please describe how **Parquet.Net** is behaving.

### Steps to reproduce the behavior

1. Try to install Library from Nuget Package Manager on Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.3.5

#### Code snippet reproducing the behavior

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Parquet.Net 4.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by aloneguid** [comment]
.NET 4.8 is not supported as it's not compatible with .net standard 2.1.
This library supports .NET 6.0, .NET Core 3.1, and .NET Standard 2.1.
You are welcome to add .NET 4.8 support.
