### ISSUE TITLE
Does not work ParquetReader.CreateAsync() for read files

### ISSUE THREAD

**Issue by alexey17000** [aloneguid/parquet-dotnet#198]
**Version:** Parquet.Net 4.1.1

**Runtime Version:** Net Core 3.1

**OS:** Windows

#### Expected behavior

Does not work ParquetReader.CreateAsync() for read files
 // return without error or exeption 
// in Parquet\Thrift\FileMetaData.cs 
if(field.Type == TType.I32) {

                                Version = await iprot.ReadI32Async(cancellationToken);  // return without error or exeption 
                                isset_version = true;
                            }

if  
Stream fs = File.OpenRead("C:\\Users\\Downloads\\partbed5c8739bbcc000.snappy.parquet")
MemoryStream ms = new MemoryStream();
fs.CopyTo(ms);
then worked

What could be the reason?

### Steps to reproduce the behavior

1. Step 1.
2. Step 2.

#### Code snippet reproducing the behavior

```csharp
//Does not work ParquetReader.CreateAsync() for read files
 using (Stream fs = File.OpenRead("C:\\Users\\Downloads\\partbed5c8739bbcc000.snappy.parquet"))
            { 
            using (ParquetReader pr = await ParquetReader.CreateAsync(fs))
            { // return without error or exeption 
// in Parquet\Thrift\FileMetaData.cs 
if(field.Type == TType.I32) {

                                Version = await iprot.ReadI32Async(cancellationToken);  // return without error or exeption 
                                isset_version = true;
                            }

if  
Stream fs = File.OpenRead("C:\\Users\\Downloads\\partbed5c8739bbcc000.snappy.parquet")
MemoryStream ms = new MemoryStream();
fs.CopyTo(ms);
then worked

What could be the reason?
```

**Comment by aloneguid** [comment]
can't help you, unclear how to reproduce this

**Comment by derekdiamond** [comment]
I can repro this easily.

Do as the code says above. If you copy to a memorystream  and use the memorystream it works. If you use the stream from OpenRead it hangs.

**Comment by aloneguid** [comment]
@derekdiamond I don't think it's as easy as you advertise :) Can you write a unit test that reproduces this in a PR?

**Comment by derekdiamond** [comment]
> @derekdiamond I don't think it's as easy as you advertise :) Can you write a unit test that reproduces this in a PR?

Ok let me create a fork and do this

**Comment by derekdiamond** [comment]
I have a netstandard2.0 library. I have to code as follows to avoid a hand in the await:
