### ISSUE TITLE
Support .netstandard 2.0

### ISSUE THREAD

**Issue by achen831008** [aloneguid/parquet-dotnet#203]
**Version:** Parquet.Net v4.1.2

**Runtime Version:** .Net Framework v4.8

**OS:** Windows

#### Expected behavior

Install Parquet.Net to .net framework 4.8 based project

#### Actual behavior

latest Parquet.Net no longer support .netstandard 2.0

**Comment by aloneguid** [comment]
It will be a lot of work to support old standard.
