### ISSUE TITLE
Is the DELTA_BINARY_PACKED encoding not supported? If it is, could you point out how to use it?

### ISSUE THREAD

**Issue by thebeard-lifebell** [aloneguid/parquet-dotnet#205]
**Version:** Parquet.Net v...

**Runtime Version:** .Net Framework v, .Net Core v etc.

**OS:** Windows/Linux/MacOSX v etc.

#### Expected behavior

Please describe how you expect **Parquet.Net** to work.

#### Actual behavior

Please describe how **Parquet.Net** is behaving.

### Steps to reproduce the behavior

1. Step 1.
2. Step 2.

#### Code snippet reproducing the behavior

```csharp
//here
```

**Comment by thebeard-lifebell** [comment]
@aloneguid Hoping you can help here.

**Comment by aloneguid** [comment]
@thebeard-lifebell do you mean for reading or writing? Reader supports the following encodings - https://github.com/aloneguid/parquet-dotnet/blob/4d03d4826d37ccbcebce34465ea62517127d3a15/src/Parquet/File/DataColumnReader.cs#L243. They are the most common ones. I haven't seen files encoded with other ones, hence it's not implemented.

It's a challenge to even generate sample files encoded differently as popular engines like Apache Spark never chooses anything else. If you don't mind, how did you get delta-binary-packed file?

**Comment by aloneguid** [comment]
It would be great to have it if you decide to add support to this library.
