### ISSUE TITLE
Unable to load shared library nironcompress (Macbook Pro Intel, Azure Function)

### ISSUE THREAD

**Issue by josdeweger** [aloneguid/parquet-dotnet#207]
**Version:** Parquet.Net v4.1.2
**Runtime Version:** .NET 6
**OS:** MacOSX (Intel)

#### Expected behavior
Expected Parquet.NET to load all necessary dependencies

#### Actual behavior
I get the following error when running the function locally:

```
System.Private.CoreLib: Exception while executing function: MyFunctionName. IronCompress: Unable to load shared library 'nironcompress' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libnironcompress, 0x0001): tried: 'libnironcompress' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibnironcompress' (no such file), '/usr/lib/libnironcompress' (no such file, not in dyld cache), 'libnironcompress' (no such file), '/usr/local/lib/libnironcompress' (no such file), '/usr/lib/libnironcompress' (no such file, not in dyld cache).
```

### Steps to reproduce the behavior
1. Create the example from the getting started section
2. Run it inside an Azure Function on MacOSX

Thank you for any help on this!

**Comment by aloneguid** [comment]
Do you mind attaching a sample project and instructions how to run it? Not sure I'm good with Azure Functions.

**Comment by josdeweger** [comment]
Thanks for the quick response. No problem, here you go! You only need to add a parquet file called `example.parquet` to the root of the project. The exception occurs here: `await groupReader.ReadColumnAsync(dataFields[c])`

[ExampleParquetFunction.zip](https://github.com/aloneguid/parquet-dotnet/files/10238964/ExampleParquetFunction.zip)

**Comment by josdeweger** [comment]
@aloneguid if there is anything I can do to help, let me know. Might need some directions in the solution though...

**Comment by aloneguid** [comment]
@josdeweger just looked at the attached zip, and inside `ExampleParquetFunction.zip\ExampleParquetFunction\Example\bin\Debug\net6.0\bin\runtimes` there's `win-x64` folder which is weird - this is normally happening when compiled on Windows. Are you compiling and running on the same os?

**Comment by josdeweger** [comment]
@aloneguid That's unexpected indeed. I just removed the bin folder and built the project again, with the same result:

<img width="498" alt="image" src="https://user-images.githubusercontent.com/100540105/208419810-4614ef90-093d-478e-b707-432a17efa119.png">

**Comment by josdeweger** [comment]
@aloneguid had a bit of time to look at this tonight. When I copy `ExampleParquetFunction/Example/bin/Debug/net6.0/runtimes/osx-x64/native/libnironcompress.dylib` to `/usr/local/lib/libnironcompress.dylib` it works. Maybe that tells you something

**Comment by josdeweger** [comment]
tried again with my new Macbook Pro with M1 processor, same issue. Had to copy the dylib file manually to the local/lib folder to make it work

**Comment by rustyswayne** [comment]
@aloneguid I had a similar issue where I could correct create a parquet file when testing my Azure Function locally, but found it failed once I deployed the function application to run in Azure.  I was able to resolve my issue but tweaking the configuration of the Azure Function application in Azure, changing the Platform from 32 bit to 64 bit.

![Parquet Microsoft Azure](https://user-images.githubusercontent.com/1865016/211119802-dbf9183b-7442-4017-ac30-b0b874197e46.png)

**Comment by aloneguid** [comment]
You can run any bitness or platform if data is uncompressed, gzip or brotli. Other codecs use native interop and hence call to native compression lib. Unfortunately those are not available in .net and I couldn't find any good implementations.  

It should be improved soon though. Optionally we can have a compression callback if you have preferred library available on your platform.

**Comment by aloneguid** [comment]
Regarding windows, native compression does not support 32bit. Only 64 and arm.

**Comment by aloneguid** [comment]
Please try with v4.2.3. If the worst case it should give a better error message.

**Comment by amnontopel** [comment]
Any findings on this one? Seeing the same thing

**Comment by josdeweger** [comment]
@aloneguid I gave v4.2.3 a try, unfortunately the problem was not resolved, but indeed the error message is a bit more clear:

```
[2023-01-19T13:22:19.378Z] Executed 'HttpTrigger' (Failed, Id=9fd4d649-2d0c-4c5d-878f-d71c05d49b9e, Duration=163ms)
[2023-01-19T13:22:19.378Z] System.Private.CoreLib: Exception while executing function: HttpTrigger. IronCompress: Unable to load nironcompress (Arm64/osx.13-arm64/). CD: /Users/josdeweger/dev/gefreubel/parquet/ExampleParquetFunction/Example/bin/Debug/net6.0. System.Private.CoreLib: Unable to load shared library 'nironcompress' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libnironcompress, 0x0001): tried: 'libnironcompress' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibnironcompress' (no such file), '/usr/lib/libnironcompress' (no such file, not in dyld cache), 'libnironcompress' (no such file), '/usr/local/lib/libnironcompress' (no such file), '/usr/lib/libnironcompress' (no such file, not in dyld cache).
```

**Comment by aloneguid** [comment]
@josdeweger do you mind trying in a console project with your set up? Just want to rule out it's not Azure Function related issue.

**Comment by josdeweger** [comment]
@aloneguid I just gave it a try in a console app (removed the dylib file from local/lib), and it works without issues. So it might be Azure Function related

**Comment by aloneguid** [comment]
Thanks, that's interesting! I suspect Azure Functions is using a custom hosting runtime. I'll get a proper setup to investigate.

**Comment by josdeweger** [comment]
awesome, let me know if I can be of any further assistence!

**Comment by cajuncoding** [comment]
Yep I encounters this afree updating to new versions also. I use Parquet.Net exclusively in background processes that run an Azure Functions. 

I’ll try checking the bigness of my Function App and report back if that resolves it…

@josdeweger Thanks for posting this issue and all the details in the thread! Saved me a lot of time trying to sort out what this error was all about! 🙏

**Comment by josdeweger** [comment]
@aloneguid is doing all the work here, so kudo's to him!

**Comment by cajuncoding** [comment]
Woot! 🙌

Yes I confirmed that updating my Azure Function (in-process) app to 64-bit resolved the issue, and makes sense. This is also confirmed by @aloneguid 's comments above and in the Githbu documentation for [IronCompress](https://github.com/aloneguid/ironcompress):

![image](https://user-images.githubusercontent.com/20844814/213560202-b32bd1fe-c61d-4bb7-9a5b-d799bf2adcd7.png)

For anyone else looking for how to update your Function App, the setting is located in:
`Azure Function` -> `Configuration` -> `General Settings`  -> `Platform Settings` -> `Platform Dropdown`

![image](https://user-images.githubusercontent.com/20844814/213560575-54961bfd-8c14-4807-9a35-8ac3a4258d70.png)

**Comment by amnontopel** [comment]
I was able to overcome this by copying the missing dll to the bin folder. However I am getting a differnt errorr now: "An attempt was made to load a program with an incorrect format". this is solved only if setting the target platform of the project as x64 which isn't an option in my case. any idea?

**Comment by aloneguid** [comment]
@amnontopel are you writing or reading files from the function?

**Comment by amnontopel** [comment]
Reading

בתאריך יום ו׳, 20 בינו׳ 2023, 14:10, מאת Ivan G ***@***.***>:

**Comment by aloneguid** [comment]
As a workaround today you can set compression level to Gzip or Brotli, those are not using native calls so it works on any platform. Ik working on bringing the rest to more platforms, including web assembly.

**Comment by amnontopel** [comment]
Can you explain how i set this?

**Comment by aloneguid** [comment]
`ParquetWriter` has `CompressionMethod` property.

**Comment by amnontopel** [comment]
I see. So for reading files (specifically with RLE encoding) I still need
to wait for your future release

**Comment by aloneguid** [comment]
No, encoding and compression are unrelated.

**Comment by amnontopel** [comment]
Ok, but reading fails on ironcompress. Btw I had no issues with version 3.7

בתאריך יום ב׳, 23 בינו׳ 2023, 15:44, מאת Ivan G ***@***.***>:

**Comment by aloneguid** [comment]
try with 4.3.4

**Comment by amnontopel** [comment]
Reading works!! thanks you

**Comment by amnontopel** [comment]
I see a new problem with writing files now where it fails to encode
non-string columns. I am basically writing data from DataTable Object to
parquet. It fails to encode DateTime, DatetimeOffset and int32 columns.
works if I string it.

**Comment by aloneguid** [comment]
Code and error please

**Comment by amnontopel** [comment]
error on red line below: "failed to encode data"



public static async void CreateParquetFromDataTable(DataTable dt, string
OutputFilePath)
        {
            try
            {
                // var dt = GenerateTestData();
                var fields = GenerateSchema(dt);
                var schema = new ParquetSchema(fields);
                if (File.Exists(OutputFilePath))
                    File.Delete(OutputFilePath);
                //Stream fileStream =
System.IO.File.OpenWrite(OutputFilePath);
                // Open the output file for writing
                using (var stream = File.Open(OutputFilePath,
FileMode.Create, FileAccess.Write))
                {
                    using (var writer = await
ParquetWriter.CreateAsync(schema, stream))
                    {
                        writer.CompressionMethod = CompressionMethod.Gzip;
                        var startRow = 0;

                        // Keep on creating row groups until we run out of
data
                        while (startRow < dt.Rows.Count)
                        {
                            using (var rgw = writer.CreateRowGroup())
                            {
                                // Data is written to the row group column
by column
                                for (var i = 0; i < dt.Columns.Count; i++)
                                {
                                    var columnIndex = i;

                                    // Determine the target data type for
the column
                                    var targetType =
dt.Columns[columnIndex].DataType;
                                   if (targetType == typeof(DateTime))
targetType = typeof(string);

                                    // Generate the value type, this is to
ensure it can handle null values
                                    var valueType = targetType.IsClass
                                        ? targetType
                                        :
typeof(Nullable<>).MakeGenericType(targetType);

                                    // Create a list to hold values of the
required type for the column
                                    var list = (IList)typeof(List<>)
                                        .MakeGenericType(valueType)
                                        .GetConstructor(Type.EmptyTypes)
                                        .Invoke(null);

                                    // Get the data to be written to the
parquet stream
                                    foreach (var row in
dt.AsEnumerable().Skip(startRow).Take(RowGroupSize))
                                    {
                                        // Check if value is null, if so
then add a null value
                                        if (row[columnIndex] == null ||
row[columnIndex] == DBNull.Value)
                                        {
                                            list.Add(null);
                                        }
                                        else
                                        {
                                           // list.Add(row[columnIndex]);
                                            // Add the value to the list,
but if it's a DateTime then create it as a DateTimeOffset first

 list.Add(dt.Columns[columnIndex].DataType == typeof(DateTime)
                                                ?
row[columnIndex].ToString()
                                                : row[columnIndex]);
                                        }
                                    }

                                    // Copy the list values to an array of
the same type as the WriteColumn method expects
                                    // and Array
                                    var valuesArray =
Array.CreateInstance(valueType, list.Count);
                                    list.CopyTo(valuesArray, 0);

                                    // Write the column
                                    //rgw.WriteColumn(new
Parquet.Data.DataColumn(fields[i], valuesArray));
                                    var column = new
Parquet.Data.DataColumn(fields[i], valuesArray);

* await rgw.WriteColumnAsync(column);                                }*
                            }

                            startRow += RowGroupSize;
                        }
                    }
                    stream.Close();
                }
            }
            catch (Exception e)
            {
                throw new Exception(e.Message);
            }
        }

**Comment by aloneguid** [comment]
I can't run above as it's hard to guess out of context what need to be done. The exception indicates that data type is not supported, so I'd check what exactly you are passing to the library. It does support non-string types for sure, including DateTime and int32. Exception message can be improved of course.
