### ISSUE TITLE
Update to v4.1.2 with Visual Studio 2022 Community (VB.NET Application)

### ISSUE THREAD

**Issue by bldenton** [aloneguid/parquet-dotnet#208]
I'm trying to update the parquet.net library for an application in Visual Studio 2022 Community to the latest version (oarquet.net v4.1.2). When I do, I receive the following error and the library will not update.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Parquet.Net 4.1.2'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

The latest version I'm able to update to is parquet.net v4.0.1. 

Do you have a suggestion on how to fix this? 

Thank you.

**Comment by aloneguid** [comment]
Net 4 is not supported anymore
