### ISSUE TITLE
Exception when reading nested columns with name collisions

### ISSUE THREAD

**Issue by ankappes** [aloneguid/parquet-dotnet#211]
**Version:** Parquet.Net v4.0.1

**Runtime Version:** .NET 6

**OS:** Windows

#### Expected behavior

The unit test below is a slight modification of the unit test from StructureTest.cs. The difference is that the column names are not unique in the hierarchy, i.e., there is a column with path address.name and type string and a column with path name and type int. I would expect the unit test to pass without errors.

#### Actual behavior

Running the unit test below throws System.InvalidCastException: Unable to cast object of type 'System.String[]' to type 'System.Int32[]'. The test passes if either the names are unique (const string line1="line1") or the type of the second name column is set to string. Looking at the source code of ThriftFooter.GetSchemaElement(Thrift.ColumnChunk columnChunk), it seems to me that the logic to obtain the schema element is wrong, as it does not skip children of other columns when trying to match the name. In this example, the column with path "name" is mapped to the schema element with path "address.name". But I might get something wrong...

#### Code snippet reproducing the behavior

```csharp
        [Fact]
        public async Task Name_collision_write_read() {
            const string address = "address";
            const string name = "name";
            const string line1 = name;
            const string postcode = "postcode";
            
            var schema = new Schema(
                new StructField(address,
                    new DataField<string>(line1),
                    new DataField<string>(postcode)), 
                new DataField<int>(name)
                );

            var ms = new MemoryStream();
            await ms.WriteSingleRowGroupParquetFileAsync(schema,
                new DataColumn(new DataField<string>(line1), new[] { "woods" }),
                new DataColumn(new DataField<string>(postcode), new[] { "postcode" }),
                new DataColumn(new DataField<int>(name), new[] { 5 }));
            ms.Position = 0;

            // out Schema readSchema, out DataColumn[] readColumns
            (Schema readSchema, DataColumn[] readColumns) = await ms.ReadSingleRowGroupParquetFile();
            
            Assert.Equal("woods", readColumns[0].Data.GetValue(0));
            Assert.Equal(postcode, readColumns[1].Data.GetValue(0));
            Assert.Equal(5, readColumns[2].Data.GetValue(0));
        }
```

**Comment by aloneguid** [comment]
May be related to #143

**Comment by aloneguid** [comment]
There were a few fixes for unsafe schema parsing in the latest version (4.2.3) which I can confirm works for your use case. Please try again with latest version.

**Comment by ankappes** [comment]
I tried again with 4.2.3 and everything works as expected. Thanks!
