### ISSUE TITLE
IndexOutOfRangeException when trying to read timedelta column written by fastparquet

### ISSUE THREAD

**Issue by ankappes** [aloneguid/parquet-dotnet#214]
**Version:** Parquet.Net v4.0.1

**Runtime Version:** .NET 6

**OS:** Windows

#### Expected behavior

I would expect parquet.Net to be able to read TIME columns coming from a pandas data frame containing timedelta objects and written by fastparquet without errors. 

#### Actual behavior

The steps below lead to an IndexOutOfRangeException. There seems to be an (additional) trailing zero in the stream which causes TimeSpanHandler.ReadAsInt64(BinaryReader reader, TimeSpan[] dest, int offset) to read beyond the actual data. If line 153 is changed to 

```csharp
         while (reader.BaseStream.Position + 8 <= reader.BaseStream.Length && idx < dest.Length)
```
the unit test below passes without errors. I have no idea whether this is a problem in fastparquet or in parquet.NET, but pyarrow for example is able to read back the parquet file without problems.

### Steps to reproduce the behavior

1. Create a parquet file from a pandas data frame containing one column with datetime.timedelta objects, using fastparquet version 2022.11.0:
```csharp
timeDeltas = [datetime.timedelta(0, 1, 0, 0), datetime.timedelta(0, 30, 0, 0)]
timeDeltaDf = pandas.DataFrame(timeDeltas)
timeDeltaDf.columns = ["TimeDeltaColumn"]
timeDeltaDf.to_parquet("C:/Tabellen/timeDeltaColumn_writtenWithFastParquet.parquet", engine='fastparquet')
```
2. Try to read the file with parquet.NET:
```csharp
        [Fact]
        public async Task ReadTimeDeltaColumn_WrittenByFastParquet() {
            using (var fs = new FileStream("C:/Tabellen/timeDeltaColumn_writtenWithFastParquet.parquet", FileMode.Open)) {
                using(ParquetReader reader = await ParquetReader.CreateAsync(fs)) {
                    DataColumn[] columns = await reader.ReadEntireRowGroupAsync();
                    var data = (TimeSpan?[])columns[0].Data;
                    Assert.Equal(TimeSpan.FromSeconds(1), data[0]);
                    Assert.Equal(TimeSpan.FromSeconds(30), data[1]);
                }
            }
        }
```

**Comment by aloneguid** [comment]
Can you attach pandas generated parquet here please.
