### ISSUE TITLE
Support case-insensitive mapping

### ISSUE THREAD

**Issue by Pragmateek** [aloneguid/parquet-dotnet#216]
**Version:** Parquet.Net v4.1.3

**Runtime Version:** .Net Framework v4.7.2

**OS:** Windows 10

#### Expected behavior

Parquet fields which are lower-cased should be mapped to properties with the same name but camel-cased.

#### Actual behavior

An exception telling that the target property cannot be found, e.g. `ParquetException: 'N' does not exist in this file`.

### Steps to reproduce the behavior

1. Serialize an instance of class using lower-case
2. Try to Deserialize it to an instance of class using camel-case

#### Code snippet reproducing the behavior

```csharp
using Parquet;
using System.IO;

namespace CaseInsensitiveParquet
{
    public class ParquetCase
    {
        public int n { get; set; }
        public string s { get; set; }
    }

    public class DonetCase
    {
        public int N { get; set; }
        public string S { get; set; }
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            var file = Path.GetTempFileName();
            ParquetConvert.SerializeAsync(new[] { new ParquetCase { n = 1, s = "1" } }, file).Wait();
            
            var x = ParquetConvert.DeserializeAsync<DonetCase>(File.OpenRead(file)).Result;
        }
    }
}
```

**Comment by aloneguid** [comment]
You can use `[ParquetColumn(Name = "...")]` attribute at the moemnt.

**Comment by Pragmateek** [comment]
> [ParquetColumn(Name = "...")]

Thanks for your answer, indeed it works like that. 👍
