### ISSUE TITLE
Certain DataType enums are missing in 4.x

### ISSUE THREAD

**Issue by jchristn** [aloneguid/parquet-dotnet#219]
**Library Version:** 4.2.2

**.NET Version:** All

**OS:** Windows

#### Expected Behaviour
```Parquet.Schema.DataType``` in v3.x (was ```Parquet.Data.DataType```) contained enum values for ```UnsignedByte```, ```Short```, and others, that have been removed.

#### Actual Behaviour
The types supported in 3.x are no longer present.

### Steps to Reproduce
```
switch ([insert whatever variable of type Parquet.Schema.DataType here])
{
  case Parquet.Schema.DataType.Short:
    // ...
}

#### Code Snippet

As above.

Is there guidance on which types to use in the absence of those mentioned previously?

**Comment by aloneguid** [comment]
Yes for some reason they were duplicated.  Short is the same as UnsignedInt16.

**Comment by aloneguid** [comment]
I mean Int16. UnsignedShort is UnsignedInt16 and so on
