### ISSUE TITLE
🈁💌💗 Post your use cases / software / screenshots here

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/parquet-dotnet#221]
Hi everyone! This is an open thread for posting examples of the way you are using `Parquet.Net`. I'm looking for real world usage!

For example:

> I use `Parquet.Net` to store and query my collection of memes. It's very fast and efficient, and it supports all kinds of data types, like strings, integers, Booleans, and even emojis! 😂

Of course it's a joke, but you get the idea! 

How do you use `Parquet.Net`? Share your examples below, and don't forget to check you are not violating your employer's privacy policy, intellectual rights and so on. You don't want to end up like Bob, who accidentally leaked the company's secret formula for their best-selling product. He thought he was just sharing a harmless photo of his lunch, but he didn't notice the paper on his desk with the confidential information. Now he is looking for a new job and a new place to eat.

**Comment by aloneguid** [comment]
[ML.NET](https://github.com/dotnet/machinelearning) seems to be using Parquet.Net in order to decode files, reference to [.csproj](https://github.com/dotnet/machinelearning/blob/main/src/Microsoft.ML.Parquet/Microsoft.ML.Parquet.csproj).

**Comment by aloneguid** [comment]
[ParquetViewer](https://github.com/mukunku/ParquetViewer) - native Windows Forms app.

![image](https://user-images.githubusercontent.com/3155189/212433149-4e50a373-ca40-41a1-8e4a-d47ebd264468.png)

**Comment by mithom** [comment]
we use it to store data gathered in testcell tests. It forms the backend of our data sharing/storing and processing framework around testing. When implemented correctly (still WIP), it would allow our calculation engineers to search through all the test results and filter based on some of the data of the test results

**Comment by aloneguid** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/3155189/212929230-ca1a48ba-3e36-4a3b-89e7-23e96a300120.png">

[Recfluence](https://recfluence.net/) seems to be using parquet.net to [read data](https://github.com/markledwich2/Recfluence/blob/f1b1ff83cdfcab85290aa05fa9a5eeacf023960c/App/YtReader/YtReader.csproj).

**Comment by aloneguid** [comment]
[Azure Synapse Analytics](https://learn.microsoft.com/en-us/azure/synapse-analytics/overview-what-is) powershell export script in the official [Microsoft repo](https://github.com/microsoft/AzureSynapseScriptsAndAccelerators/blob/49995e3d69b63d25569a5b87c07777487c3a6028/Migration/SQLServer/2B_ExportSourceDataToParquet/Export-ToParquet.ps1).

**Comment by sbrickey** [comment]
we use it as a replacement for Azure Data Factory, which saves us about $10k/month

our design is simple: table to store source/destinations and some tracking flags. Process will check the table, identify which records are "ready", transfers data, then updates the records to indicate their completion... we use this to keep cloud data "current" from the source system(s)

ADF cost was split about half between "bytes transferred" and "API calls" (interactions with the table above)

we replaced it with custom code running on a B-series VM, which costs around $130/month

the custom code is simple: generate local parquet file from source, upload to storage, execute API call into databricks to merge parquet file into existing data.

**Comment by immitev** [comment]
We use the library for implementing SSIS+ components for reading/writing Parquet files https://cozyroc.com/ssis/parquet . 

Well, the initial development is based on an older version of the library, due to requiring .NET Framework 4.0 support (did some backporting). Luckily the upcoming version of  our component suite can target .NET Framework 4.6.1, so that we are transitioning to the [3.10.0](https://github.com/aloneguid/parquet-dotnet/releases/tag/3.10.0) version.

**Comment by aloneguid** [comment]
[Cinchoo ETL](https://github.com/Cinchoo/ChoETL) is an ETL framework for .NET. From website:

> Simple, intuitive Extract, transform and load (ETL) library for .NET. Extremely fast, flexible, and easy to use. Cinchoo ETL is a code-based ETL framework for extracting data from multiple sources, transforming, and loading into your very own data warehouse in .NET environment. You can have data in your data warehouse in no time.

seems to be using `Parquet.Net` for [reading and writing](https://github.com/Cinchoo/ChoETL/blob/72208c092e04a5600f80092fcef5cfa56bd1439e/src/ChoETL.Parquet/ChoParquetRecordReader.cs) parquet files.
