### ISSUE TITLE
Azure Synapse Spark java.io.IOException: Could not read footer for file

### ISSUE THREAD

**Issue by lucashby** [aloneguid/parquet-dotnet#226]
**Library Version:** 4.2.2

**.NET Version:** .NET 6.0 (SDK Version 6.0.405)

**OS:** Azure Synapse Spark 3.2

#### Expected Behaviour

Should be able to process .parquet files as we have with 4.1.x.

#### Actual Behaviour

Spark throws exceptions (attached) complaining about the parquet file's footer.  We don't do anything with the file footer and the library has worked fine until we went onto 4.2.2.

### Steps to Reproduce

Would require access to an Azure Synapse Spark cluster, but all you would need to do is produce a parquet file which you then process through the Apache Spark cluster (you can use a Notebook or compiled code to do so) to see the exception.

#### Code Snippet
In Spark for .NET (C#),  loading the file could look like this:

```csharp
var df = Spark.Read().Format("parquet").Load("path/to/file.parquet");
```
[application_1673979747726_0001-Driver (stdout) - stdout.log](https://github.com/aloneguid/parquet-dotnet/files/10439508/application_1673979747726_0001-Driver.stdout.-.stdout.log)

**Comment by aloneguid** [comment]
try 4.3.0

**Comment by lucashby** [comment]
The update does seem to allow for processing the files again.  Just had to handle the DateTimeOffset breaking change, but I think we are only using it one time so should be manageable.
