### ISSUE TITLE
Dictionary encoding not working

### ISSUE THREAD

**Issue by volgunin** [aloneguid/parquet-dotnet#234]
**Library Version:** 4.3.3
**.NET Version:** 6.0
**OS:** Windows

Hey team, new dictionary encoding feature enabled by default in latest builds seems to not working. Indexes are written using PLAN_DICTIONARY encoding while reader has the same implementation for both PLAIN_DICTIONARY and RLE_DICTIONARY encodings.

Adding this code to DataColumnReader.ReadColumn method:
```
case Thrift.Encoding.PLAIN_DICTIONARY: {
                        cd.indexes ??= new int[(int)totalValuesInChunk];
                        if(!ParquetPlainEncoder.Decode(cd.indexes, 0, cd.indexes.Length, _thriftSchemaElement, s, out int indexCount)) {
                            throw new IOException("could not decode");
                        }
                        //cd.dictionary.Explode(cd.indexes.AsSpan(), cd.values, cd.valuesOffset, indexCount);
                        cd.dictionary.ExplodeFast(cd.indexes.AsSpan(), cd.values, cd.valuesOffset, indexCount);
                        cd.valuesOffset += indexCount;
                    }
                    break;
```
seems to solve the issue with the library itself - it can now read its own files correctly.

The bigger issue is that when I read these files on DataBricks, I get the same result - the entire column is populated with the first value from the dictionary.

DataBricks not supporting  PLAIN_DICTIONARY?

**Comment by aloneguid** [comment]
Can you specify more details on how to reproduce this? It does read its own files for sure - this is tested end to end.

**Comment by volgunin** [comment]
This test fails. The data after reading consist of 'xxx' strings only.

`
[TestMethod]
        public async Task DictionaryEncodingTest2()
        {
            var data = new string?[]
            {
                "xxx",
                "xxx",
                "xxx",
                "xxx",
                "xxx",
                null,
                "yyy",
                "yyy",
                "yyy",
                string.Empty,
                "yyy",
                "yyy",
                null,
                null,
                "zzz",
                "zzz",
                "zzz",
                "zzz",
            };

            var dataField = new DataField(name: "string", clrType: typeof(string));
            var parquetSchema = new ParquetSchema(dataField);

            using var stream = new MemoryStream();

            using (var parquetWriter = await ParquetWriter.CreateAsync(parquetSchema, stream, formatOptions: new ParquetOptions() { UseDictionaryEncoding = true }))
            {
                using var groupWriter = parquetWriter.CreateRowGroup();
                await groupWriter.WriteColumnAsync(new DataColumn(dataField, data));
            }

            stream.Position = 0;

            using var parquetReader = await ParquetReader.CreateAsync(stream);
            using var groupReader = parquetReader.OpenRowGroupReader(0);
            var dataColumn = await groupReader.ReadColumnAsync(dataField);

            CollectionAssert.AreEqual(dataColumn.Data, data);
        }
`

**Comment by aloneguid** [comment]
Thanks.  Spark has some quirks in dictionary encoding, its using legacy format which I tried to repeat as it doesn't really stick to specs. I'll check again

**Comment by aloneguid** [comment]
should work in 4.4.0

**Comment by aloneguid** [comment]
please reopen if not working
