### ISSUE TITLE
Make it configurable to chose native compression over managed implementation

### ISSUE THREAD

**Issue by dxdjgl** [aloneguid/parquet-dotnet#240]
The performance degradation of managed snappy vs native snappy makes it very desirable to be able to force the native implemenation.

**Comment by aloneguid** [comment]
It might be a good idea to try native first, and if not available fall back to managed. Managed implementation makes tools like [this](https://parquetdbg.aloneguid.uk/) possible to work completely in browser ;)

**Comment by dxdjgl** [comment]
Sure but it will require the additional pull request to be accepted on IronCompress

**Comment by dxdjgl** [comment]
If we change IronCompress so that it tries out native compression first, if that fails with DllNotFoundException then try managed implementation. Of course GZip should be handled without catching the DllNotFoundException first, what do you think about this proposal, however it will remove the following properties
1. UseNativeBrotli
2. PreferManagedSnappy
Since it will always prefer native over managed.

**Comment by aloneguid** [comment]
I like it, just remove all the flags and make the magic happen. "It just works".

**Comment by dxdjgl** [comment]
Made changes to IronCompress just awaiting your approval 😄
