### ISSUE TITLE
Signed byte vs unsigned byte schema

### ISSUE THREAD

**Issue by mukunku** [aloneguid/parquet-dotnet#244]
It seems the unsigned byte data type was renamed to signed byte but the comment still refers to it as unsigned:
https://github.com/aloneguid/parquet-dotnet/blob/57dc5bc927e4d18d58af34fbb85c04478beb9498/src/Parquet/Schema/DataType.cs#L24-L27

Should this data type still be "unsigned byte"?

**Comment by aloneguid** [comment]
You're right, it's a typo.  Should be signed byte.  The enum is obsolete now though

**Comment by mukunku** [comment]
I opened #246 to fix it for now.
