### ISSUE TITLE
There is no CreateRowGroupAsync method inside parquetwriter which shown in the sample code

### ISSUE THREAD

**Issue by Hariprasad-b-s** [aloneguid/parquet-dotnet#245]
due to this data is not writing in the file "await groupWriter.WriteColumnAsync(datacolumn)"

**Comment by aloneguid** [comment]
Just a typo in documentation, will correct. See unit tests for up to date syntax.

**Comment by ekmekcicaner** [comment]
Will you add WriteColumnAsync method or not?

**Comment by aloneguid** [comment]
see new readme, hopefully that answers your question
