### ISSUE TITLE
Not able to mark property as Optional for DeserializeAsync

### ISSUE THREAD

**Issue by aloha2023** [aloneguid/parquet-dotnet#257]
There is ParquetIgnore attribute available but it will ignore the property no matter it presents or not.

Do you have plan to support something like "ParquetOptional"? That means assigning null value to the property when it's not available in the parquet file, but if the property does present, get the value

**Comment by aloneguid** [comment]
Sorry not sure I understand

**Comment by aloha2023** [comment]
For example,
The parquet files can have 
{"A":"value 1", "B":"value 2"}   or   {"A":"value 3"} , let's say column B is added later

So to backward support the old parquet files that only have column A, we have to mark column B with ParquetIgnore 
But that will block the column B to be read from new parquet files even they have the data.

If we have the [Optional] feature supported (just like the default behavior of NettonSoft.Json package), then we could mark Column B as optional instead of Ignore
