### ISSUE TITLE
Read schema not equal to written schema

### ISSUE THREAD

**Issue by dxdjgl** [aloneguid/parquet-dotnet#258]
Unable to read back encoding of DateAndTime other than "Impala"

**Comment by aloneguid** [comment]
can't reproduce

**Comment by dxdjgl** [comment]
[Fact]
        public async Task Defect() 
        {
            var filename = "d:\\schema.parquet";

            var field = new DateTimeDataField("Date", DateTimeFormat.DateAndTime, true);
            var schema = new ParquetSchema(field);

            using(var fileStream = new FileStream(filename, FileMode.Create, FileAccess.Write, FileShare.None)) {

                using(var parquetWriter = await ParquetWriter.CreateAsync(schema, fileStream)) 
                {
                    using(var groupWriter = parquetWriter.CreateRowGroup()) {

                        var dates = new List<DateTime>() { DateTime.Now };
                        var dataColumn = new DataColumn(field, dates.ToArray());

                        groupWriter.WriteColumnAsync(dataColumn);
                    }
                }
            }


            using(var parquetReader = await ParquetReader.CreateAsync(filename)) 
            {
                parquetReader.Schema.Fields.ToString();

                Assert.Single(schema.Fields);
                Assert.Equal(schema.Fields.Count, parquetReader.Schema.Fields.Count);
                Assert.Equal(schema.Fields.First().GetType(), parquetReader.Schema.Fields.First().GetType());
            }
        }

**Comment by dxdjgl** [comment]
Try the above test case, and then check out my pull request

**Comment by dxdjgl** [comment]
Problem for me becomes apparent if I try to write a new file with the schema read from the first file, which is no longer dateandtime but "impala" encoding
