### ISSUE TITLE
Reading/writing complex types

### ISSUE THREAD

**Issue by vikcher** [aloneguid/parquet-dotnet#263]
I was looking for some documentation on how to read/write structs and seems like this section of the documentation is incomplete.
Is there a plan to add this? https://github.com/aloneguid/parquet-dotnet/blob/master/docs/complex-types.md#structures

**Comment by aloneguid** [comment]
Yes and no. There are plans but lack of time ;) There are plenty of examples in unit tests, it's just a matter of writing up a nice guide. Are you up for it?

**Comment by aloneguid** [comment]
documentation updated
