### ISSUE TITLE
Class Serialisation - Guid support

### ISSUE THREAD

**Issue by RoelVerhees** [aloneguid/parquet-dotnet#265]
Hello there, 

First of all, I really loves this package and I'm using it a lot, but I really would like to request one feature that makes it perfect.
Is there a possibility to support GUID in the class serialization functionality?

I'm now manually resolving this, by outputting the GUID as String, but would be nice if you could serialize a GUID and deserialize a GUID.

**Comment by aloneguid** [comment]
There's no backward compatible UUID mapping to a parquet type, therefore it might be challenging at the moment. We can implement this with some conversion logic later.

**Comment by kruno-exponent** [comment]
Hi Ivan, 

I have a sizable proto which I need to store in parquet. The protos are intended to be this data structure which is serialized into parquet (which is just a copy of Google Dremel).

Duplicating sizable structures would be extremely wasteful for maintenance and runtime. Parquet (column stores) really shine when there is a big number of fields and huge data structures. I

 would assume this is your target audience. If you have these big data structures you are increasing the probability that for whatever reason at least a single field will create problems.

Can you maybe explain what is your rationale for not wanting to add this feature?

Can we at least add custom logic to ignore fields and make https://github.com/aloneguid/parquet-dotnet/pull/31 more general by passing a callback which determines is the type ignored through options?

**Comment by aloneguid** [comment]
Sorry I wasn't clear - this is on the roadmap.

I'm up for having this feature available and new serializer makes it technically possible to implement nicely.

Due to the nature of open-source I can't give you an estimate, but it's on my personal near-term todo list ;)

**Comment by aloneguid** [comment]
#331

**Comment by aloneguid** [comment]
@RoelVerhees guids are supported now, as long as they are encoded as UUID in parquet.
