### ISSUE TITLE
WriteColumnAsync throwing exception when serializing Int32?

### ISSUE THREAD

**Issue by emcdaniel1624** [aloneguid/parquet-dotnet#266]
I have been getting an exception when serializing the ID column of a table. The exception just says failed to encode data page data for column ID (System.Int32). Any idea as to why this might be happening?

**Comment by emcdaniel1624** [comment]
ParquetRowGroupWriter.WriteColumnAsync(new Parquet.Data.DataColumn(fields[i], valuesArray));

**Comment by aloneguid** [comment]
Sorry I really have no idea. You might want to reopen with more information.

**Comment by emcdaniel1624** [comment]
I created a new issue and included more information
