### ISSUE TITLE
Serialization is loosing properties form base class of base class

### ISSUE THREAD

**Issue by clarkfinger** [aloneguid/parquet-dotnet#268]
If class hierarhy has more than one level of inheritance ParquetConvert.SerializeAsync is loosing properties form base class of base class even SchemaReflector.ReflectWithInheritedProperties is used.

Issue is caused by th fact that SchemaReflector is getting properties only form the base class instead of whole hierarchy.
PropertyHelpers.GetDeclaredPropertyFromClassType() method also requires correction.

**Comment by clarkfinger** [comment]
Pull request has been created fro this issue fix https://github.com/aloneguid/parquet-dotnet/pull/269

**Comment by aloneguid** [comment]
merged )
