### ISSUE TITLE
Clarify guidance on list vs arrays

### ISSUE THREAD

**Issue by jmandel** [aloneguid/parquet-dotnet#281]
### Issue description

https://github.com/aloneguid/parquet-dotnet/blob/1a5dde264e3fcc2ff221b555d05889e449f4365c/docs/rows.md?plain=1#L145 says

>  In general, *when repeated data can be represented as a plain type, always use repeatable field*. Repeatable fields are lighter and faster than lists which have extra overhead on serialisation and performance.

https://github.com/aloneguid/parquet-dotnet/blob/1a5dde264e3fcc2ff221b555d05889e449f4365c/docs/schema.md?plain=1#L163 says

> If you can, prefer lists to arrays because:

I understand there is some nuance here, but these seem like opposite baseline recommendations.

**Comment by aloneguid** [comment]
Updated guidance:
- rows: https://aloneguid.github.io/parquet-dotnet/rows.html#arrays-repeatable-fields
- schema: https://aloneguid.github.io/parquet-dotnet/schema.html#lists
