### ISSUE TITLE
Optional values for Row

### ISSUE THREAD

**Issue by bykka** [aloneguid/parquet-dotnet#287]
### Issue description

The Row class supports three possible types: IEnumerable<object>, object, and object?[]. If the schema contains optional fields, then only the object?[] type is suitable, not IEnumerable<object>. Therefore, it is necessary to convert IEnumerable<object> to an array to ensure compatibility with optional fields in the schema.

**Comment by aloneguid** [comment]
Thanks for the feedback. I'll be slowly deprecating Table/Row API as they are inflexible like that and by design do not allow proper evolution without breaking changes. There will be similar API replacing them. Is there any reason you can't use ParquetSerializer or low-level api?

**Comment by bykka** [comment]
I read data from AWS DynamoDB and there is no way to read data by column or to know how many records I will get. So, the Row API suit better for my case.
