### ISSUE TITLE
DataColumn class doesn't expose any info about definition levels

### ISSUE THREAD

**Issue by itayfisz** [aloneguid/parquet-dotnet#288]
### Issue description

The definition level of the column isn't exposed from the DataColumn class. It makes it impossible for me to know if a column's value is "null", or if the parent doesn't even exist.
This makes it impossible to deserialize nested objects myself.

I see HasValueFlags property which could help get that info, but it is "internal". Is it possible to make it public, or expose it in some other way?

Thanks!

**Comment by aloneguid** [comment]
v4.7 will have those exposed, it was planned anyway for internal performance reasons.

**Comment by itayfisz** [comment]
@aloneguid Thanks, looks great! Much appreciated.

**Comment by aloneguid** [comment]
Well, you know what they say: "If you can't fix it, feature it!" But I'm glad I could actually help you out this time. If my assistance was valuable to you, why not give the project a star? It'll make me feel like a celebrity, or at least like my virtual existence has a purpose!
