### ISSUE TITLE
[BUG]: Unable to write parquet file with multiple row groups using ParquetRowGroupWriter

### ISSUE THREAD

**Issue by emmanuelrflores** [aloneguid/parquet-dotnet#291]
### Library Version

>4.6.0

### OS

macOS

### OS Architecture

64 bit

### How to reproduce?

I am trying to create parquet files with multiple row groups. On 4.5.4 I was able to build a parquet file with multiple row groups using the example from the [writing.md](https://github.com/aloneguid/parquet-dotnet/blob/master/docs/writing.md) document. I upgraded to 4.6.2 and started getting the following error

`"One or more errors occurred. (Field [x (System.Int32)] is not attached to any schema. You need to construct a schema passing in this field first. (Parameter 'column'))"`

Going back to 4.6.0 also has the error. 

Is the method shown below and in the writing.md documentation considered the old form of serialization and I should try the new one? 

Below is a code sample I am using. 

### Failing test

```csharp
var xColumn = new DataColumn(
   new DataField<int>("x"),
   Array.Empty<int>());

var yColumn = new DataColumn(
   new DataField<string>("y"),
   Array.Empty<int>());

// create file schema
var schema = new ParquetSchema(xColumn.Field, yColumn.Field);

using(Stream fileStream = System.IO.File.OpenWrite("c:\\test.parquet")) {
    for(int i = 0; i < 50; i++){
        using(ParquetWriter parquetWriter = await ParquetWriter.CreateAsync(schema, fileStream)) {
            xColumn = new DataColumn(
                new DataField<int>("x"),
                Enumerable.Range(0,1000).ToArray());
            yColumn = new DataColumn(
                new DataField<int>("y"),
                Enumerable.Range(0,1000).ToArray());
            using(ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup()) {
                await groupWriter.WriteColumnAsync(xColumn);
                await groupWriter.WriteColumnAsync(yColumn);
            }
        }
    }
}
```

**Comment by emmanuelrflores** [comment]
Looking at the [serialization.md](https://github.com/aloneguid/parquet-dotnet/blob/master/docs/serialisation.md), specifically the [Appending to files](https://github.com/aloneguid/parquet-dotnet/blob/master/docs/serialisation.md#appending-to-files) section, I was able to do the same as my example above. If I want to have multiple group rows in the file for the data, you can do so with the following: 

```Csharp
// exterior class
public class XY{
    public int x {get; set;}
    public int y {get; set;}
}

// inside a serialize method
// Create 50 row groups with 1000 points within each one
using(Stream fileStream = System.IO.File.OpenWrite("c:\\test.parquet")) {
    for(int i = 0; i < 50; i++){
        var data = Enumerable.Range(0, 1000).select(i => {
            XY xy = new();
            xy.x = i;
            xy.y = i;
            return xy;
        }).ToList();

        bool append = i == 0;
        await ParquetSerializer.SerializeAsyncData(data, fileStream, new ParquetSerializerOptions { Append = append});
    }
}
```

The documentation does say you can define row group size when serializing, but looking at the [ParquetSerializer.cs](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Serialization/ParquetSerializer.cs) constructors or the [ParquetSerializerOptions.cs](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Serialization/ParquetSerializerOptions.cs) class, I was unable to find an option for row group size. Is that an oversight for this release and will be coming soon?

**Comment by aloneguid** [comment]
Starting from 4.7.1, you can set custom row group size, see https://github.com/aloneguid/parquet-dotnet/blob/master/docs/serialisation.md#specifying-row-group-size

**Comment by emmanuelrflores** [comment]
I've verified it works for what I'm trying to do. Thanks!

**Comment by aloneguid** [comment]
Happy it works for you. Don't forget to star the project! It will make me feel appreciated and motivated to keep improving it. Also, if you have any feedback or suggestions, feel free to open an issue or a pull request.
