### ISSUE TITLE
Clarification on serialization of dates, times, and decimals

### ISSUE THREAD

**Issue by bdquig** [aloneguid/parquet-dotnet#292]
### Issue description

The old way of serialization was to use ParquetColumn attributes.  With these attributes, you could specify the storage format for dates and times or the precision and scale for decimals.

The new way if serialization is to use Json attributes. How can you specify these additional settings?

**Comment by aloneguid** [comment]
The new serializer does not support this feature yet, but I'm working on it and it will be available soon. In the meantime, you can use the old serializer or the low level api to customize your output. I'll update you here when the feature is ready.

**Comment by tylerchessman** [comment]
Are there any examples of how to use the old serializer?  Example, if working with a DateTime, is there a way to specify that only the "Date" portion should be written to Parquet?

**Comment by aloneguid** [comment]
@tylerchessman yes sorry, forgot to reply :) With old serializer you can set `ParquetColumn` attribute on a class property which allows you to customize serialization for dates and decimals. Something similar is coming soon in new one.

**Comment by aloneguid** [comment]
This is now available since v4.9, [docs](https://github.com/aloneguid/parquet-dotnet/blob/master/docs/serialisation.md#customising-serialisation) are updated too. Hope it works for you! ;)
