### ISSUE TITLE
Protobuf with parquet

### ISSUE THREAD

**Issue by kruno-exponent** [aloneguid/parquet-dotnet#295]
### Issue description

Hi,

I'm running into issues with serializing Protobufs with this library.

This library can't process Google.Protobuf.ByteString.

https://github.com/aloneguid/parquet-dotnet/pull/31/files could potentially solve my issue but I would then still need to modify the protobuf compiler which is not optimal.

Would it be possible to add option or register custom type converter to this library?

**Comment by kruno-exponent** [comment]
Sorry for commenting on #265 instead of this issue. Is there a way to monitor the new serializer work?

**Comment by aloneguid** [comment]
@kruno-exponent if you mean tracking progress, you can subscribe to release notes https://github.com/aloneguid/parquet-dotnet/releases. I try to keep them up to date.
