### ISSUE TITLE
[BUG]: Empty arrays are serialized incorrectly

### ISSUE THREAD

**Issue by qixzy** [aloneguid/parquet-dotnet#300]
### Library Version

4.7.1

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

Consider this code:

```csharp
class Person
{
    public string Name { get; set; }
    public int[] PostIds { get; set; }
}
await Parquet.Serialization.ParquetSerializer.SerializeAsync(new[]
{
    new Person ()
    {
        Name = "Mark",
        PostIds = new int[]{ 1, 2, 3 }
    },
    new Person ()
    {
        Name = "Joe",
        PostIds = new int[]{  }
    },
    new Person ()
    {
        Name = "Alice",
        PostIds = new int[]{ 4, 5 }
    },
}, "example.parquet");
```

Then, use [DuckDB](https://github.com/duckdb/duckdb) to select everything (latest version, `v0.7.1 b00b93f0b1`)
```sql
select * from 'C:\Path\To\Example\example.parquet';
```

Result: ``Error: Invalid Input Error: Mismatch in parquet read for column 1, expected 3 rows, got 2``
Instead, if you insert at least one item in {Joe}.PostIds (e.g. `8`), you correctly see 
```
  Name     PostIds
 varchar   int32[]
------------
 Mark     [1, 2, 3]
 Joe      [8]
 Alice    [4, 5]
```

The same issue also occurs if you use structures, instead of primitives:

```csharp
class Person
{
    public string Name { get; set; }
    public PostId[] PostIds { get; set; }
}

class PostId
{
    public int Number { get; set; }
}

await Parquet.Serialization.ParquetSerializer.SerializeAsync(new[]
{
    new Person ()
    {
        Name = "Mark",
        PostIds = new int[]{ 1, 2, 3 }.Select(x => new PostId{ Number = x }).ToArray()
    },
    new Person ()
    {
        Name = "Joe",
        PostIds = new int[]{  }.Select(x => new PostId{ Number = x }).ToArray()
    },
    new Person ()
    {
        Name = "Alice",
        PostIds = new int[]{ 4, 5 }.Select(x => new PostId{ Number = x }).ToArray()
    },
}, "example.parquet");
````

**Comment by qixzy** [comment]
I've also tried with a variety of tools for reading back the Parquet file ([pqrs](https://github.com/manojkarthick/pqrs), DuckDB, [parquet-viewer-online.com](https://parquet-viewer-online.com), [extendsclass](https://extendsclass.com/parquet-viewer.html), and they all either 1) error out or 2) return inconsistent data.

For example, this is what pqrs returns:

```
############################
File: /mnt/d/example.parquet
############################

{Name: "Mark", PostIds: [{Number: 1}, {Number: 2}, {Number: 3}]}
{Name: "Joe", PostIds: [{Number: 4}, {Number: 5}]}
{Name: "Alice", PostIds: null}
```

**Comment by aloneguid** [comment]
Thanks for reporting this, I can confirm it's a bug. In addition to that, arrays in general can't distinguish between null and empty, therefore majority of the libraries use lists instead of arrays.

There is a bug in this lib trying to use arrays for atomic types.

I'm about to fix this.

**Comment by qixzy** [comment]
Seems to work correctly, thank you for fixing it!

**Comment by aloneguid** [comment]
I'm glad it fixed your issue and hope you enjoy using this project and find it useful for your needs. If you do, please consider giving it a star on GitHub. It would mean a lot to me and help other people discover it too. Thank you!
