### ISSUE TITLE
Decimal precision/scale wrt whole value...

### ISSUE THREAD

**Issue by larryboymi** [aloneguid/parquet-dotnet#306]
### Issue description

...

Running into an issue where I need to utilize more of the precision for the whole value than I get with the defaulted precision (38-18 = 20).

I was able to get around this by specifying a false scale of `12`, but doing so causes my application flow other issues. Is there a way to not cause an error in BigDecimal in such a case?

I believe https://github.com/aloneguid/parquet-dotnet/blob/bf24f0de55418190925e2febde8f57ad2bbcb36c/src/Parquet/File/Values/Primitives/BigDecimal.cs#L46 means that https://github.com/aloneguid/parquet-dotnet/blob/bf24f0de55418190925e2febde8f57ad2bbcb36c/src/Parquet/File/Values/Primitives/BigDecimal.cs#L173 will be thrown on a large whole value/small scaled right of zero case, like the number `4122888939532301310025563.3528` which I believe is valid in `decimal(38,18)`, unless scale is set more rigidly than I believe.

**Comment by aloneguid** [comment]
Sorry, slightly struggling to understand the issue. Can you maybe show a reproducible piece of code with cause of issue?

**Comment by larryboymi** [comment]
I was just wondering if the `DataColumn` or `BigDecimal` itself be more flexible in the default case, but it seems to stick to the scale in the default, and not allow for data to come in without specifying a smaller scale when it could.

In reality I moved in some extra logic to help set the scale smaller so that the value could get in, but it would be nice if the library might operate in this manner given an option or something.

```csharp
decimal[] bigWhole = new decimal[] { 4122888939532301310025563.3528m };
DataField defaultDecimalDF = new DataField("bigDecimal", typeof(decimal));
var schema = new ParquetSchema(new List<DataField>() { defaultDecimalDF });
DataColumn dc = new DataColumn(defaultDecimalDF, bigWhole);

var ms = new MemoryStream();
using (var writer = await ParquetWriter.CreateAsync(schema, ms))
{
    using (ParquetRowGroupWriter groupWriter = writer.CreateRowGroup())
    {
        await groupWriter.WriteColumnAsync(dc);
    }
}
```

Results in `System.NotSupportedException : decimal data buffer is 18 but result must fit into 16 bytes`

This might not be an Issue, more of an enhancement option. Appreciate the time.

**Comment by aloneguid** [comment]
@larryboymi you can use `DecimalDataColumn` which allows to override default precision/scale, not sure this helps?
