### ISSUE TITLE
Very slow performance reading wide parquet file using V4

### ISSUE THREAD

**Issue by mikestaib** [aloneguid/parquet-dotnet#309]
### Issue description

Reading a wide parquet file (3500 columns with 300 rows each) with ParquetReader.ReadTableFromFileAsync(filename) using version 4.8.1 takes minutes. 4.0.0 has similar abysmal performance. 

Going back to 3.10 using ParquetReader.ReadTableFromFile(filename) this takes about a second. 

Parquet file used for testing containing random values attached. Can someone confirm they see the same slowness?
[wide_parquet.zip](https://github.com/aloneguid/parquet-dotnet/files/11290727/wide_parquet.zip)

**Comment by aloneguid** [comment]
The attached file took 1.6 seconds to read on the latest version. Table reader is supposed to be slow but definitely not minutes.

Can you generate a performance trace?

**Comment by mikestaib** [comment]
Thanks for taking a look. Did a few more checks and seems I am able to get those speeds only with the net6.0 and net7.0 tests, testing in netcoreapp3.1 is considerably slower. I originally noticed the slowness in a legacy .NET framework 4.7.2 app, seems in later versions this may not be an issue.

**Comment by aloneguid** [comment]
That's interesting it's slower in .net core 3! I'm only doing performance testing on .NET 7 at the moment. Will have to take a look which bit and will come back to you.

**Comment by aloneguid** [comment]
Feel free to try v4.9.1, it's slightly faster now.

**Comment by mikestaib** [comment]
Thanks for digging in. Looks like there was some improvement, but that still too long for me to read this file in a minimal .NET Framework 4.7.2 console app:

`static void Main(string[] args)
        {
            var sw = Stopwatch.StartNew();
            var parquet = ParquetReader.ReadTableFromFileAsync(@"C:\Temp\wide_parquet.parquet").Result;
            sw.Stop();
            Console.WriteLine($"Took {sw.Elapsed.TotalSeconds} seconds to read file");
            Console.ReadLine();
        }`

v4.9.0 -> 424 seconds
v4.9.1 -> 154 seconds

Optimizations might be fighting a losing battle if the underlying framework is to blame. I'm content to stay at 3.10 personally as I don't need the async api for what I am doing.

**Comment by aloneguid** [comment]
Yeah no worries, thanks for bringing it to my attention anyway. I've already started writing my own performance optimised Thrift generator in T4, it's actually not that hard.

Once done it will be faster than in 3.x as even they are synchronous, there is still a lot of unnecessary logic. Unfortunately Thrift is multi-platform and multi-language, but some language bindings are very suboptimal, like the C# one. The standard compiler generates like thousands of async calls which slows it down to a crawl for absolutely no reason.

**Comment by aloneguid** [comment]
@mikestaib check out 4.10 release

**Comment by mikestaib** [comment]
Thanks, down to 5 seconds with 4.10. Still not as fast as the old synchronous API but not so incredibly painful as it was.

**Comment by aloneguid** [comment]
Hey @mikestaib, I'm glad you find it satisfying! Yeah, the trade-off is that it's a bit slower on single thread but it can handle more concurrent requests.

Thanks for sticking with me and giving me feedback along the way.

If you like the project, please give it a star. You'll make my day and yours too. Trust me, it's worth it.
