### ISSUE TITLE
Document migration guide from DateTimeOffset to DateTime

### ISSUE THREAD

**Issue by PSanetra** [aloneguid/parquet-dotnet#315]
### Issue description

We have existing parquet files which were serialized with DateTimeOffset with version before 4.3.0. It would be nice to have a migration guide how to deserialize those files now with DateTime when DateTimeOffset was used before. Is it just DateTime with UTC timezone?

**Comment by aloneguid** [comment]
Correct, it's just datetime in UTC. Parquet format does not differentiate between datetime and datetimeoffset, those are just CLR types that are stored the same.
