### ISSUE TITLE
Issue using DECIMAL data type...

### ISSUE THREAD

**Issue by albamain** [aloneguid/parquet-dotnet#318]
### Issue description

Using Parquet.net 4.10.1 writing a parquet file: when the data are coming from a database table (or a DataTable) with a DECIMAL field, the file is created but it become unreadable. 
Trying to read the .parquet file with a common viewer, an error is raised with a message which says: "Cannot find data type handler to create model schema for [n:<my decimal column name>, t: FIXED_LEN_BYTE_ARRAY, ct: <not set>, rt: OPTIONAL, c:0]

This was working fine using 3.9 version

Attached there's the code sample used: the .parquet file produced returns the error above when opened with a viewer
            
[testPq.zip](https://github.com/aloneguid/parquet-dotnet/files/11405387/testPq.zip)

**Comment by aloneguid** [comment]
Thank you for reporting a bug in our open-source project. We (myself and ChatGPT) appreciate your effort and feedback. However, to help us fix the bug faster and more effectively, please follow these guidelines:

- Use the bug report form template to provide clear and concise information about the bug.
- Include the steps to reproduce the bug, the expected and actual results, and any error messages or screenshots if applicable.
- Specify the software environment, such as the operating system, browser, version, and any external dependencies that may affect the bug.
- Avoid reporting multiple bugs in one report. Create separate reports for each bug you encounter.
- Search for existing bug reports before creating a new one. If you find a similar report, you can comment on it or add more details.

Following these guidelines will help us prioritize and resolve the bug as soon as possible. Thank you for your cooperation and understanding.
