### ISSUE TITLE
[BUG]: Issue using DECIMAL data type

### ISSUE THREAD

**Issue by albamain** [aloneguid/parquet-dotnet#319]
### Library Version

4.10.1

### OS

Windows 1x.x, Windows Server

### OS Architecture

64 bit

### How to reproduce?

1. Environment: Windows 1x.x; VS2022, C# , .NET framework 4.8,  using Parquet.Net Nuget (see attached) to create a set of data to be saved as a .parquet file.
2. Data are coming from a database table (or a DataTable) with a DECIMAL field; the .parquet file is created successfully. 
Run the program (just adapt the file path). No errors, no problem, the .parquet file gets created.

The actual problem is described below:

a. Use a Parquet viewer to open the .parquet file created, like  [https://github.com/mukunku/ParquetViewer](url) or [https://github.com/aloneguid/parquet-viewer-uwp](url)

b. The viewer will return an error _"Cannot find data type handler to create model schema for [n:MYDECIMALFIELD, t: FIXED_LEN_BYTE_ARRAY, ct:, rt: OPTIONAL, c:0]"_ .

c.1 Using an online viewer like  [https://www.parquet-viewer.com/](url)  the file isn't opened and no error is returned. 
c.2 Using the VScode component [https://github.com/dvirtz/vscode-parquet-viewer](url) to open the file, the file appears in a JSON format - the decimal field appears like a byte array of values instead of an actual value.

d. All the above was working fine using Parquet.Net 3.9

[testPq.zip](https://github.com/aloneguid/parquet-dotnet/files/11408048/testPq.zip)

**Comment by aloneguid** [comment]
Looks to me it's an issue with the tools you are using to view? Im not an author if any of those sorry

**Comment by albamain** [comment]
You mean none of the tools is working? If you omit the Decimal field the read runs just fine. Same using decimal and Parquet.Net 3.9
