### ISSUE TITLE
[BUG]: Decimal type failure issue 

### ISSUE THREAD

**Issue by albamain** [aloneguid/parquet-dotnet#320]
### Library Version

4.10.1

### OS

Windows 1x.x, Windows Server

### OS Architecture

64 bit

### How to reproduce?

1. Reproduction steps: Refer to [https://github.com/aloneguid/parquet-dotnet/issues/319](url)
Just adding a note: you said none of the tools involved are made by you but you are the author for 

https://github.com/aloneguid/parquet-viewer-uwp   

and it is failing as all the other mentioned tools with the same error. 
Again,  parquet-viewer-uwp works fine if the data are not using Decimal.

Thanks

**Comment by albamain** [comment]
Just in case: do you have a C# code snippet using Parquet.Net 4.10 I can use to 
1. write a DataTable which includes a Decimal field with few rows to a .parquet file 
2. read the .parquet file and restore the content in a DataTable


to make sure we're not doing something wrong?
Thanks

**Comment by aloneguid** [comment]
Sorry but I can't help you. Please consider using another library because I honestly don't understand you. Is this a prank?

**Comment by albamain** [comment]
I was pretty sure this attempt was useless. 
We've identified a bug of yours, we've specified how to reproduce it, we've identified code owned by you which is  involved in the issue but you simply do not want to cooperate. Fair enough.
Good luck.
