### ISSUE TITLE
[BUG]:  simple array can not be desterilized 

### ISSUE THREAD

**Issue by Motke84** [aloneguid/parquet-dotnet#321]
### Library Version

latest

### OS

Windows

### OS Architecture

32 bit

### How to reproduce?

Scheme with an Array[] can not be parsed and I am getting too general exception
I didn't created this file I am just consuming it.

System.FieldAccessException
  HResult=0x80131507
  Message=failed to compile 'Vector/list/element (System.Double?)'
  Source=Parquet
  StackTrace:
   at Parquet.Serialization.Dremel.Assembler`1.Compile(ParquetSchema schema, DataField df)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Parquet.Serialization.Dremel.Assembler`1..ctor(ParquetSchema schema)
   at Parquet.Serialization.ParquetSerializer.<DeserializeAsync>d__5`1.MoveNext()
   at ParquetTest.Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\SD.ICE-Repositories\NetCoreBoilerplate\ParquetTest\Program.cs:line 82

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentNullException: Value cannot be null. (Parameter 'method')

My object is:

public class VectorPoco
    {

        [ParquetColumn("ID")]
        public long? Id { get; set; }

        [ParquetColumn("Exch")]
        public string? Exch { get; set; }

        [ParquetColumn("ProductID")]
        public string? ProductId { get; set; }

        [ParquetColumn("SecTyp")]
        public string? SecTyp { get; set; }

        [ParquetColumn("MMY")]
        public string? Mmy { get; set; }

        [ParquetColumn("HasOI")]
        public bool? HasOi { get; set; }

        
   
       // [ParquetColumn("Vector",ListElementName = "Vector", ListContainerName = "Vector", UseListField = true)]
        public IEnumerable<double?>? Vector { get; set; }
    }
    
    what am I doing wrong or there is a bug with this kind of case
    parquet file is in tmp.zip
    
[tmp.zip](https://github.com/aloneguid/parquet-dotnet/files/11414827/tmp.zip)

### Failing test

```csharp
var data =
                         await ParquetSerializer.DeserializeAsync<VectorPoco>(fs, new ParquetOptions()
                         {
                             
                         });



public class VectorPoco
    {

        [ParquetColumn("ID")]
        public long? Id { get; set; }



        [ParquetColumn("Exch")]
        public string? Exch { get; set; }


        [ParquetColumn("ProductID")]
        public string? ProductId { get; set; }


        [ParquetColumn("SecTyp")]
        public string? SecTyp { get; set; }


        [ParquetColumn("MMY")]
        public string? Mmy { get; set; }

        [ParquetColumn("HasOI")]
        public bool? HasOi { get; set; }

        
   
       // [ParquetColumn("Vector",ListElementName = "Vector", ListContainerName = "Vector", UseListField = true)]
        public IEnumerable<double?>? Vector { get; set; }
    }
```

**Comment by aloneguid** [comment]
ParquetColumn attribute is for legacy serializer. Just refer to serializer docs and follow examples :)
