### ISSUE TITLE
[BUG]:  GetParquetSchema does not respect JsonIgnore

### ISSUE THREAD

**Issue by Mrinal-Thomas-Epic** [aloneguid/parquet-dotnet#322]
### Library Version

4.10.1

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

The GetParquetSchema [TypeExtension](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Serialization/TypeExtensions.cs) does not respect the `[JsonIgnore]` attribute.

### Failing test
For example code, I used the class

```csharp
	public class Test
	{
		public string A { get; set; }

		[JsonIgnore]
		public string B { get; set; }
	}
```
and called
```
ParquetSchema schema = typeof(Test).GetParquetSchema(true);
```
and the schema has two data fields (for string A and B).

**Comment by aloneguid** [comment]
seems to work fine?

![image](https://github.com/aloneguid/parquet-dotnet/assets/3155189/1fe31a6a-cd57-4c09-bb64-87c92b85c958)

**Comment by Mrinal-Thomas-Epic** [comment]
ohhh I think I know what happened. I am using Netwonsoft.Json for some other JSON work and they also define their own [JsonIgnore](https://www.newtonsoft.com/json/help/html/PropertyJsonIgnore.htm) attribute. When I switched to [System.Text.Json.Serialization.JsonIgnore](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.serialization.jsonignoreattribute?view=net-8.0), it started working for me.

This can be closed unless Parquet.Net is expected to work with the Newtonsoft.Json attribute. Thanks for the quick response.

**Comment by aloneguid** [comment]
Awesome!  Now you can enjoy the beauty and simplicity of `System.Text.Json.Serialization.JsonIgnore`.

If you like this project, please don't forget to give it a star ;)
