### ISSUE TITLE
[BUG]: Breaking change somewhere between 4.6.2 and 4.11.1: Method not found `ctor ParquetSchema(IReadOnlyCollection)`

### ISSUE THREAD

**Issue by atlemann** [aloneguid/parquet-dotnet#334]
### Library Version

4.11.1

### OS

Any

### OS Architecture

64 bit

### How to reproduce?

1. Create a library, `A`, which depends on Parquet.Net v4.6.2
2. Use library `A` in an app which uses Parquet.Net 4.11.1
3. Run the app and get the following exception

Introduced by f2c07540a1137be6bc22f0c9ea0f06419ebb4ec1

```
Unhandled exception. System.MissingMethodException: Method not found: 'Void Parquet.Schema.ParquetSchema..ctor(System.Collections.Generic.IReadOnlyCollection`1<Parquet.Schema.Field>)'.
```

**Comment by aloneguid** [comment]
Requirement was relaxed from `IReadonlyCollection` to `IEnumerable`. This is not a bug, you have to upgrade.

**Comment by atlemann** [comment]
It means I have to upgrade all transient dependencies as well, which I wouldn't expect without a major version bump. Just something to keep in mind.

**Comment by aloneguid** [comment]
Sorry to hear that, I'll keep in mind for future breaking changes, this one slipped through as it was so minor.
