### ISSUE TITLE
[BY DESIGN]: ParquetSerializer collection deserialization issue 

### ISSUE THREAD

**Issue by paveldayneko** [aloneguid/parquet-dotnet#344]
### Library Version

4.8.0 and higher

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

1. Serialize object with array collection using ParquetConvert class and parquet.net@4.7.1 . Store result file  and try to deserialize (all work nice)
```csharp

public class Dto
{
    public IReadOnlyCollection<string> HarmlessCollection { get; set; }
}

var dataToWrite = new List<Dto>
{
    new()
    {
        HarmlessCollection = new List<string>() { "Hello" }
    }
};


using (var stream = File.Create("tmp.parquet"))
{
    ParquetConvert.SerializeAsync(dataToWrite, stream).GetAwaiter().GetResult();
}

using (var stream = File.OpenRead("tmp.parquet"))
{
    var result = ParquetConvert.DeserializeAsync<Dto>(stream).GetAwaiter().GetResult();
}
```
2. Replace ParquetConvert with ParquetSerializer, update Colelction type to List<T> and perform and try to deserialize file from previous run (all works)
```csharp

public class Dto
{
    public List<string> HarmlessCollection { get; set; }
}

using (var stream = File.OpenRead("tmp.parquet"))
{
    var result = ParquetSerializer.DeserializeAsync<Dto>(stream).GetAwaiter().GetResult();
}
```
3. Update to  parquet.net@4.7.1 and try to run deserialization from step 2. ParquetException with error message "'HarmlessCollection/list/element' does not exist in this file" will be thrown. The same issue is relevant for latest versions parquet.net@4.12.0.

So it seems like ParquetSerializer used to deserialize array collections produced by ParquetConvert nicely before 4.8.0 version.
This backward compatibility is important for our project as we already have gigs of data produced by deprecated ParquetConvert and would like to update to the lates version of this library and use ParquetSerializer without a need to re-process all the files we are storing now.

Thanks!

**Comment by aloneguid** [comment]
This is due to the fact i have dropped support for plain arrays which are not used by anyone else. They were default for old serialiser when writing collection of primitives. You can still access the data, it's just `ParquetSerializer` won't read it out of the box.

**Comment by paveldayneko** [comment]
Would it be possible to resurrect it there? I can provide PR for that or you generally opposing idea of having this logic in ParquetSerializer?

**Comment by Mitkee** [comment]
While I get that dropping support for writing arrays, reading files generated with older versions of the library is very important. We've a large number (100 000 +) files generated with older versions which we now can't read with the newer library version, which essentially means we'll either be stuck in the old version or we've to create a migrator where we read and re-generate each file in order to keep the parquet files compatable with the library which geerated them in the first place. 

 Would it be possible to keep the reader support for arrays -> list but drop support from the writer?

**Comment by aloneguid** [comment]
@paveldayneko of course feel free to raise a PR.
@Mitkee I think my wording was wrong, support wasn't dropped, it's just the entire `ParquetConvert` serializer was dropped as it's old and no new features are added. If you need it, you should either stick with an old version, use raw API, or add support for this yourself (at the end of the day, this is true meaning of open-source).
