### ISSUE TITLE
Json Attribute usage breaks several use cases

### ISSUE THREAD

**Issue by Galzai** [aloneguid/parquet-dotnet#345]
Hi,
The removal of distinction between Json attributes and parquet attributes is breaking use cases where an object is first deserialized from Json, and then is serialized to parquet (or various combinations of that). 
If you require different behaviors (For example deserializing a value from Json, but ignoring when serializing to parquet) this makes implementation more cumbersome,  and in my opinion Json and Parquet attributes should not be forced to correlate.

**Comment by aloneguid** [comment]
You might think I'm crazy, but I kind of enjoy the fact that it crashes. Hear me out ;) JSON and parquet have nothing in common and they don't play well together. So when you use the same model for both, you're basically asking for trouble. You can't change either format, use the best data types for each one, or anything like that.

**Comment by Galzai** [comment]
@aloneguid "if you are using the same model for both you're basically asking for trouble" is exactly why you don't want to force correlation by using the json attribute for parquet this prevents per use-case flexibility, there's a distinction between objects in code (The intermediate class) and the data model as input/output , so there are plenty of use cases where this distinction can be useful  and simplify implementation

**Comment by aloneguid** [comment]
Yeah you might be right as well as I am, but I'm going to stick to my approach for now.
