### ISSUE TITLE
[BUG]: Error serializing DateTimeOffset DayOfWeek has no fields

### ISSUE THREAD

**Issue by andyong79** [aloneguid/parquet-dotnet#347]
### Library Version

4.12

### OS

Windows 10

### OS Architecture

64 bit

### How to reproduce?

Seems to happen trying to serialize any object that has a DateTimeOffset in it.

I created a .net 6 console app and tested with the below code sample and could replicate the error.
System.InvalidOperationException: 'property 'DayOfWeek' has no fields'

### Failing test

```csharp
using Parquet.Serialization;

var data = new List<TestClass>(){
    new TestClass()
    {
        DtOffset = new DateTimeOffset(DateTime.UtcNow)
    }
};
var schema = await ParquetSerializer.SerializeAsync(data, @"c:\temp\test.parquet");

public class TestClass
{
    public DateTimeOffset DtOffset { get; set; }
}
```

**Comment by aloneguid** [comment]
Try `DateTime` instead.

**Comment by andyong79** [comment]
Unfortunately i don't control the model so can't change it

**Comment by aloneguid** [comment]
Well then it's sort of outside of the scope of this project ;)
