### ISSUE TITLE
[BUG]: Optional column with all null values

### ISSUE THREAD

**Issue by ligadata-kn** [aloneguid/parquet-dotnet#348]
### Library Version

4.12.0

### OS

Mac OS Ventura 13.4 (M2)

### OS Architecture

ARM 64

### How to reproduce?

1. Created partsupp table in TPCH dataset (TPC benchmark data generated by tpchgen)
2. Declared the following table: 
`        Table table = new Table(
            new DataField<Int64>("ps_partkey"),
            new DataField<Int64>("ps_suppkey"),
            new DataField<Int64>("ps_availqty"),
            new DataField<double>("ps_supplycost"),
            new DataField<string>("ps_comment")
        );`
3. Imported data from CSV file
4. Turns out none of the rows had a value for ps_comment so the generated Parquet file had this metadata: 
`File path:  partsupp.parquet
Created by: Parquet.Net version 4.12.0 (build 7340cefb906024ef2c1de3026dada7785ed8d2ad)
Properties: (none)
Schema:
message root {
  required int64 ps_partkey (INTEGER(64,true));
  required int64 ps_suppkey (INTEGER(64,true));
  required int64 ps_availqty (INTEGER(64,true));
  required double ps_supplycost;
  optional binary ps_comment (STRING);
}

Row group 0:  count: 80000000  14.28 B records  start: 4  total(compressed): 1.064 GB total(uncompressed):1.064 GB 
--------------------------------------------------------------------------------
               type      encodings count     avg size   nulls   min / max
ps_partkey     INT64     S BB_     80000000  1.75 B     0       "1" / "20000000"
ps_suppkey     INT64     S BB_     80000000  4.01 B     0       "1" / "1000000"
ps_availqty    INT64     S BB_     80000000  3.71 B     0       "1" / "9999"
ps_supplycost  DOUBLE    S BB_     80000000  4.82 B     0       "1.0" / "1000.0"`

5. I had trouble scanning the parquet file using "parquet-cli scan" as it looked for a fifth column and didn't find it
6. "select *" failed in Azure Synapse Serverless on this table (but it works fine when you query specific columns)
7. COPY INTO failed in Azure Synapse Dedicated SQL Pool as it complained about missing column
8. Overall, it appears there's a mismatch in the schema and the rowset in the parquet file. Not clear if this is a bug in this library or if those different systems (parquet-cli and Azure Synapse) aren't correctly interpreting this as an optional column with no data.

### Failing test

```csharp
static void ProcessPartSuppFile(string filePath, string dstPath)
    {
        string file = Path.GetFileName(filePath);
        if (file != "partsupp.tbl")
            return;

        Table table = new Table(
            new DataField<Int64>("ps_partkey"),
            new DataField<Int64>("ps_suppkey"),
            new DataField<Int64>("ps_availqty"),
            new DataField<double>("ps_supplycost"),
            new DataField<string>("ps_comment")
        );

        // no header row to skip
        using (StreamReader sr = new StreamReader(filePath))
        {
            while (!sr.EndOfStream)
            {
                string? line = sr.ReadLine();
                if (line == null)
                    break;
                
                string[] c = line.Trim('|').Split('|', 5);
                table.Add(Int64.Parse(c[0]), Int64.Parse(c[1]), Int64.Parse(c[2]), double.Parse(c[3]), c[4]);
            }
        }

        table.WriteAsync(Path.Combine(dstPath, "partsupp.parquet"));
    }
```

**Comment by aloneguid** [comment]
Please try low level api or class serializer. Row api will be deprecated in the next major release.
