### ISSUE TITLE
[BUG]: ADX export malformed string values

### ISSUE THREAD

**Issue by mcbos** [aloneguid/parquet-dotnet#356]
### Library Version

4.13.0

### OS

Windows 11

### OS Architecture

64 bit

### How to reproduce?

1. Create an export using Azure Data Explorer non-native writer
2. Deserialize export file using ParquetSerializer
3. Inspect first row, strings are malformed

### Failing test

```csharp
I'll create a PR which will include a test.

Example adx query:

.export compressed to parquet (
    h@"https://storage1.blob.core.windows.net/containerName;secretKey"
  ) with (
    UseNativeParquetWriter = false
  )
  <|
let T = datatable(String:string, Nullable:string)
[
   "a", "",
   "b", "y",
   "c", "z",
];
T
```

**Comment by aloneguid** [comment]
Can you attach a sample export from step 1 please?

**Comment by mcbos** [comment]
An example export can be found [here](https://github.com/mcbos/parquet-dotnet/blob/356-fix-adx-malformed-strings/src/Parquet.Test/data/required-strings-adx.parquet).

**Comment by aloneguid** [comment]
seems to be just fine using Parquet Viewer (https://aloneguid.github.io/parquet-online/) which is using this library?

**Comment by mcbos** [comment]
This happens when using ParquetSerializer.Deserialize, parquet-online is using the column based deserialization right?

I suspect that the issue has to do with the FileOffset not being set correctly by the adx export.
I have fixed it by calling `PropagateLevels` when the string nullability differs from the schema, is this the correct solution?

**Comment by aloneguid** [comment]
Oh I see, class serializer may behave slightly differently, I have to check.

**Comment by aloneguid** [comment]
merged, thanks ;)
