### ISSUE TITLE
Does the library support treating missing columns as nulls?

### ISSUE THREAD

**Issue by greenlynx** [aloneguid/parquet-dotnet#361]
### Issue description

Hi,

I have a Parquet file that I wrote some records to using `ParquetSerializer.SerializeAsync<MyRecordType>`. I'm using `ParquetSerializer.DeserializeAsync<MyRecordType>` to read it back.

I'd now like to add a new, nullable string property named `AccountId` to `MyRecordType`, but retain the ability to read the existing file. I'm getting an exception: `Parquet.ParquetException: 'AccountId' does not exist in this file` which makes sense, but it would be good to have the option to just set the new property to be set to null when the column doesn't exist in the file. Is that possible somehow please?

**Comment by aloneguid** [comment]
At the moment you can mark this new property with `[JsonIgnore]` and deserializer will skip it. Note that schema evolution is not supported by parquet format itself.

**Comment by greenlynx** [comment]
Thanks for the fast reply - as I understand it, `[JsonIgnore]` also stops the field being serialized too, which isn't what I need. I need to read the file (with the new field set to null if it's missing from the Parquet file) then write it again, including the new field.

Would you be open to a PR that enables this "treat missing columns as null" behavior (opt-in, behind an option?)

**Comment by greenlynx** [comment]
Hi - I've submitted a PR to address this functionality: https://github.com/aloneguid/parquet-dotnet/pull/366
