### ISSUE TITLE
Support Writing Int64 timestamp MICROS unit

### ISSUE THREAD

**Issue by michael-mckinney** [aloneguid/parquet-dotnet#362]
### Issue description

Currently the only supported INT64 DateTimeFormat is for a ConvertedType of TIMESTAMP_MILLIS.

Per https://spark.apache.org/docs/latest/sql-ref-datetime-pattern.html and https://spark.apache.org/docs/3.4.1/configuration.html#runtime-sql-configuration it seems the preference for Spark (ie what underlies DataBricks) is to use Parquet's LogicalType TimestampType(isAdjustedToUTC = true, unit = MICROS) (ie ConvertedType TIMESTAMP_MICROS) as truncation likely occurs when ingesting nanos or exporting millis.

Is it possible to add additional INT64 timestamp support to include MICROS?

**Comment by nodakai** [comment]
I'm willing to add `UTC = true, unit = NANOS` once `MICROS` is done
