### ISSUE TITLE
Issue with processing parquet files that contains more than 1 RowGroup

### ISSUE THREAD

**Issue by andrewlyakh** [aloneguid/parquet-dotnet#369]
### Discussed in https://github.com/aloneguid/parquet-dotnet/discussions/364

<div type='discussions-op-text'>

<sup>Originally posted by **andrewlyakh** June 29, 2023</sup>
Hi!
We're trying to use this very useful library but we've met with the issue of parsing parquet files containing more than 1 RowGroup.
The ParquetExtensions.ReadAsTableAsync() function doesn't use row validation for the single-row group file (this is not a problem for us now).
But if the file schema contains more that 1 group, this row validation fails starting from the second group because of calling Table.Add(Row item) function (screenshots 1-3):

1.
![image](https://github.com/aloneguid/parquet-dotnet/assets/33354646/740ae32b-bf81-4191-82bd-22042ca06e73)

2.
![image](https://github.com/aloneguid/parquet-dotnet/assets/33354646/be5e1df6-7a86-42fd-a035-429d82e4767c)

3.
![image](https://github.com/aloneguid/parquet-dotnet/assets/33354646/ae0b000c-d5ea-4300-b81e-0cac76fc04f4)

Validation fails because the EnumerableType doesn't equal the runtime element type (screenshot 4). The TryExtractIEnumerableType extension method returns the Object as an element type instead of the Row and the ValidateList() function throws the ArgumentException($"expected a collection of...") exception (line 74):

4.
![image](https://github.com/aloneguid/parquet-dotnet/assets/33354646/72d1f265-eb00-4f53-a546-b33778c12923)

We would be very very grateful if this error could be corrected!

And again, thank you so much for this useful library!</div>

**Comment by aloneguid** [comment]
@andrewlyakh are you still planning on raising a PR?

**Comment by andrewlyakh** [comment]
> @andrewlyakh are you still planning on raising a PR?

Hi! I have no plans to raise PR. We've decided to avoid the usage of the column groups functionality in our application.

**Comment by andrewlyakh** [comment]
It was decided to avoid the usage of the column groups functionality.
