### ISSUE TITLE
datetime type doesn't work

### ISSUE THREAD

**Issue by mikeTWC1984** [aloneguid/parquet-dotnet#37]
I'm trying to set datetime column (using DateTimeOffset // INT96 type) and read the file with apache drill. Query runs, but datetime column display some weird value like below:
p}'\xC5e\x0B\x00\x00\x1D\x85%\x00
There is a setting to tread int96 as timestamp (in drill),  but if set to true query throws an error (no useful message tough, just says reader error)

**Comment by aloneguid** [comment]
There's nothing I can do about it - can't fix issues in Drill.
