### ISSUE TITLE
Class deserialiser does not support Immutable types

### ISSUE THREAD

**Issue by dev1010101** [aloneguid/parquet-dotnet#370]
### Issue description

When using DeserializeAsync\<T\> there is a constraint that T needs to have a empty constructor.

CsvHelper and Json have support for classes that are immutable and have a constructor to populate all fields.

**Comment by aloneguid** [comment]
Parquet format is column based, therefore there is no way to set all fields of a class at once without a huge performance degradation and massive memory usage. Therefore it's very unlikely this is going to happen.

**Comment by dev1010101** [comment]
Fair point. Feature we are after is:
- Class reading in batches in stead of full parquet file
- Filtering predicate when reading

Very quick mockup signature for reading:
 `IAsyncEnumerable<T> ParquetReader.DeserializeAsync<T,KeyT>(string KeyColumn, KeyT min, KeyT max)`

This would be already a huge win because the metadata can be used to only read relevant sections.
This combined optionally combined with a Batchreader would further improve performance

I can create 2 new enhancement request if both ideas are considerd valuable.
Only if these 2 are tackled the convenience for having support for readonly classes makes sense.

**Comment by aloneguid** [comment]
@dev1010101 re (1) you can pass row group index when reading instead of reading entire file. Thing with predicates is that internally entire file (or row group) needs to be read back into memory before filtering can be applied as parquet format doesn't store values separately (this is how it achieves great compression and speed rates).

**Comment by dev1010101** [comment]
For the predicate we could look at row group statistics to decide  on what groups to read

**Comment by aloneguid** [comment]
True, you can do that, that's what Spark's query optimiser is in fact utilising to speed up execution. However, that might be falling out of scope of parquet library and more to a query engine?
