### ISSUE TITLE
Add DELTA_BINARY_PACKED encoder For Int32 And Int64

### ISSUE THREAD

**Issue by ee-naveen** [aloneguid/parquet-dotnet#375]
As of now, parquet.net does not support delta encoding.

https://github.com/aloneguid/parquet-dotnet/issues/205 Parquet.net already supports read, however write is currently not supported.

Delta Binary Packed encoding is designed to achieve high compression ratios for numerical data types. 
It efficiently packs the numerical values, reducing the amount of storage required to store the data on disk. 
This can result in significant storage space savings, especially for datasets with large numeric columns.

Reference:

- https://image.slidesharecdn.com/hadoopsummit-140630160016-phpapp01/75/efficient-data-storage-for-analytics-with-apache-parquet-20-29-2048.jpg?cb=1665769903
- https://image.slidesharecdn.com/hadoopsummit-140630160016-phpapp01/75/efficient-data-storage-for-analytics-with-apache-parquet-20-30-2048.jpg?cb=1665769903
- https://image.slidesharecdn.com/hadoopsummit-140630160016-phpapp01/75/efficient-data-storage-for-analytics-with-apache-parquet-20-31-2048.jpg?cb=1665769903
- https://www.slideshare.net/cloudera/hadoop-summit-36479635

**Comment by aloneguid** [comment]
Thanks, this is definitely on my radar.

**Comment by ee-naveen** [comment]
I have made significant progress, and we might be raising a PR for review soon.
The initial results look promising, but running more tests.

**Comment by ee-naveen** [comment]
Available in 4.16
