### ISSUE TITLE
Deserialize parquet file to JSON

### ISSUE THREAD

**Issue by VolodymyrSenchak** [aloneguid/parquet-dotnet#376]
### Issue description

Not sure that this is easy to implement, but is it possible in the future to implement functionality that will just convert parquet data to JSON? 
I think in some cases such functionality will be very useful.

**Comment by VolodymyrSenchak** [comment]
Oh, thanks for replying. Actually, even existing functionality with row API should help me (parsing files will happen in the background process, so I can neglect some performance degradation) 
I'm currently gathering all cases which can be in our project, and I suspect that files could have different structures depending on the case. 
And since currently Class Serialisation approach will throw an exception when some property will not be found in file - I see two options:
1  - parse file with some base class which will try to identify which type structure file has, and then a second time with the appropriate type. But from a performance perspective, it would also be not ideal, because it will be needed to parse the file twice.
2 - by using row API parse file to JSON, and then parse it to some aggregate class. 

Maybe you could suggest how I can solve that issue when a parquet file can have a dynamic structure?

**Comment by aloneguid** [comment]
Class serialization won't throw an exception starting from v4.16.0, the release is coming in the next week or two (the code is already in master) so I'd recommend it highly - a lot of time was spend in making it understand all parquet structures and performance is great (it compiles classes to IL so there is zero reflection etc.)

**Comment by VolodymyrSenchak** [comment]
Wow, very glad to hear that. Then we will wait until 4.16.0 will be available. Thank you a lot!

**Comment by VolodymyrSenchak** [comment]
@aloneguid, hi,
wanted to clarify, when are you planning to release 4.16.0 version?

**Comment by aloneguid** [comment]
Hey, sorry for the delay, I've got one issue to finish so most probably by the end of this week.
________________________________

**Comment by aloneguid** [comment]
Released.
