### ISSUE TITLE
Documentation: `ParquetSerializer.DeserializeAsync` doesn't accept a file path

### ISSUE THREAD

**Issue by nodakai** [aloneguid/parquet-dotnet#379]
### Issue description

https://aloneguid.github.io/parquet-dotnet/serialisation.html#quick-start
```
IList<Record> data = await ParquetSerializer.DeserializeAsync<Record>("/mnt/storage/data.parquet");
```

https://github.com/aloneguid/parquet-dotnet/blob/9010985b382b71104493cfe1d2057633979edcdd/src/Parquet/Serialization/ParquetSerializer.cs#L116

**Comment by pantonis** [comment]
Documentation is outdated

**Comment by aloneguid** [comment]
I'm happy to announce that I've fixed the issue with the missing method overloads in version 4.22.0. I appreciate your feedback and support. If you like this project, please consider giving it a star on GitHub. Thank you!
