### ISSUE TITLE
IAsyncEnumerable deserializer

### ISSUE THREAD

**Issue by Arithmomaniac** [aloneguid/parquet-dotnet#386]
https://github.com/aloneguid/parquet-dotnet/blob/07e7c6792a08c5e227819db65d2483c99a58e2f5/src/Parquet/Serialization/ParquetSerializer.cs#L140

There should be a version of this method that returns an `IAsyncEnumerable<T>`. Implementation like this, maybe? (Happy to make a PR if desired.)

```csharp
Assembler<T> asm = GetAssembler<T>();
var result = new List<T>();

using ParquetReader reader = await ParquetReader.CreateAsync(source, options, cancellationToken: cancellationToken);
for(int rgi = 0; rgi < reader.RowGroupCount; rgi++) {
     await DeserializeRowGroupAsync(reader, rgi, asm, result, cancellationToken);
     foreach (var item in result) { 
        yield return item; 
    }
    result.Clear();
}
```

**Comment by aloneguid** [comment]
Sounds reasonable, would you like to raise a PR?

**Comment by Arithmomaniac** [comment]
Sure; what should the method be named?

**Comment by aloneguid** [comment]
Good question, quick googling and [this SO answer](https://stackoverflow.com/a/59452285/80858) suggests good names could be `DeserializeAllAsync` or `DezerializeAsAsyncEnumerable`?

**Comment by Arithmomaniac** [comment]
I'll go with `DeserializeAllAsync`. Hopefully will have a PR within a week.
