### ISSUE TITLE
Remove unsupported parquet-cli commands (view, view-all)

### ISSUE THREAD

**Issue by aloneguid** [aloneguid/parquet-dotnet#4]
**view** and **view-all** are not supported anymore, remove so they are not dangling there.

**Comment by atlemann** [comment]
Doh! It's was the only thing I was using the CLI for...

**Comment by aloneguid** [comment]
They were crashing often and didn't produce correct results, I don't have capacity to support them for free or answer support requests. All the efforts are now on core library.

**Comment by atlemann** [comment]
It's fine. It was just very convenient.
