### ISSUE TITLE
Zstandard Support?

### ISSUE THREAD

**Issue by ldsands** [aloneguid/parquet-dotnet#40]
I hope you don't mind feature requests.

It looks like you support gzip and snappy. I would love to see zstandard support as well. It seems to be gaining support. I had some space issues recently with a project of mine and [wrote a simple comparison of snappy and zstandard using parquet files in python](https://dev.to/ldsands/snappy-vs-zstd-for-parquet-in-pyarrow-9g0).

I looks like there are two projects supporting zstandard in c#. ([first one](https://github.com/skbkontur/ZstdNet))([second one](https://github.com/bp74/Zstandard.Net)) Could one of these be used to easily add support for zstandard?

I have little formal programming training and even less experience with .net but I might be willing to pitch in at some point.

Thanks for your time!

**Comment by aloneguid** [comment]
The idea is definitely worth following. I don't have capacity at the moment if anyone wants to take this on.

**Comment by djepson-rms** [comment]
@aloneguid I'd be willing to work on it. Zstd and lz4 support would help a lot with one of my projects.

I'm wondering what sort of approach you would prefer.

1. Adding direct dependencies to third party libraries in parquet-dotnet
2. Bring-your-own-algorithm approach where we add ZStandard and Lz4 to the CompressionMethod enum, register stub readers and writers in the DataFactory for them that throw an exception, and then add a method to register/replace any implementation?

**Comment by djepson** [comment]
@aloneguid I'd be willing to work on it. Zstd and lz4 support would help a lot with one of my projects.

I'm wondering what sort of approach you would prefer.

1. Adding direct dependencies to third party libraries in parquet-dotnet
2. Bring-your-own-algorithm approach where we add ZStandard and Lz4 to the CompressionMethod enum, register stub readers and writers in the DataFactory for them that throw an exception, and then add a method to register/replace any implementation?

**Comment by jack-pappas** [comment]
@djepson Your second choice feels like the better one. It's a bit more complex to implement, but gives the user of the library the flexibility to not only support new compression types (as they're added to Parquet), but also to swap in custom implementations of a compression codec if needed; an example of the latter would be someone who wants to work with gzip-compressed parquet files, but wants to use a hardware-accelerated implementation (Intel QuickAssist, for example).

One small tweak to the idea: the ``CompressionMethod`` enum in this library should maybe be tied to the labels and values from the [parquet format thrift definitions](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L487); it currently has the Gzip and Snappy cases in the wrong order, so the values won't match up _directly_ to the parquet values. If your interface for a compression codec has a ``CompressionMethod``-typed property then, it should be possible to register a new codec instance with the library, even for a ``CompressionMethod`` value that's not actually included in the enum; then, if parquet defines a new compressor method which isn't immediately added to the ``CompressionMethod`` enum of this library, you'd still be able to register a compressor instance with that value and be able to work with paruqet files using that compression mode.

**Comment by aloneguid** [comment]
You could easily support the official libzstd dll/so/dylib via p/invoke so if it's in the binary folder parquet.net will just pick it up and use. I don't think anyone is going to port zstandard to .net.

**Comment by aloneguid** [comment]
I'm going to support all the compression methods in v4, but can't give an estimate when it will be public.

**Comment by aloneguid** [comment]
I've got all compression formats supported in v4, it's far from release though https://github.com/aloneguid/parquet-dotnet/blob/delta/docs/compression.md

**Comment by aloneguid** [comment]
as v4/async is out, compression codecs should come soon
