### ISSUE TITLE
[BUG]: ColumnMetaData doesn't list PLAIN_DICTIONARY in the encodings list

### ISSUE THREAD

**Issue by spanglerco** [aloneguid/parquet-dotnet#401]
### Library Version

4.16.4

### OS

Linux

### OS Architecture

64 bit

### How to reproduce?

1. Write a parquet file containing a string column that contains a repeated value such that dictionary encoding is used
2. Examine the file and notice that the ColumnMetaData for the string column has an encodings list of RLE, BIT_PACKED, and PLAIN, but not PLAIN_DICTIONARY, even though it contains data pages using PLAIN_DICTIONARY encoding.

Specifically, I came across a parquet reader that was relying on the encodings listed in the footer to decide whether or not to read a dictionary page. I filed a bug with them first, and their investigation revealed this issue (they are planning to make their reader more tolerant to avoid this being a problem).

But technically, I believe [the parquet file format](https://github.com/apache/parquet-format/blob/c8f7f94cce6dbb1a8cc891704c3bd3a6e5e4e205/src/main/thrift/parquet.thrift#L717) says that if a column is using dictionary encoding, it should include that in the list of encodings in the footer so that readers know what to expect.

Currently, the list of encodings in the footer [is hard-coded](https://github.com/aloneguid/parquet-dotnet/blob/fe4f82812318ba0679553fb2da9c30b401961f1d/src/Parquet/File/ThriftFooter.cs#L137). I assume the desired fix would be to dynamically populate that list of encodings based on the actual pages being written.

### Failing test

```csharp
using Parquet;
using Parquet.Rows;
using Parquet.Schema;

Table table = new(
    new DataField<int>("x"),
    new DataField<string>("y1", nullable: true))
{
    new Row(0, "string"),
    new Row(1, "string"),
};

await table.WriteAsync("output.parquet");
```

**Comment by aloneguid** [comment]
The purpose of it is validate whether pages can be read, without reading more data. In other words, it's a hint to readers, but they shouldn't rely on it. Or in other words the reader you have mentioned has serious bug.

It would be nice to improve population if this field, but it's not a requirement. Thanks for noticing it though, appreciate it.
