### ISSUE TITLE
documentation isssue

### ISSUE THREAD

**Issue by pavlexander** [aloneguid/parquet-dotnet#404]
### Issue description

Hi,
I have jsut started experimenting with the library, so I headed to documentation here https://aloneguid.github.io/parquet-dotnet/serialisation.html#quick-start

but it does not correlate with the actual code.

### for reading

For example: the code

`IList<Record> data = await ParquetSerializer.DeserializeAsync<Record>("/mnt/storage/data.parquet");`

will not work, as [there is no signature](https://github.com/aloneguid/parquet-dotnet/blob/fe4f82812318ba0679553fb2da9c30b401961f1d/src/Parquet/Serialization/ParquetSerializer.cs#L116) that accepts the file path!

the actual working code that I have managed to get to work looks like it:

```csharp
            IList<MyParquetTest> saved = null;
            using (var stream = System.IO.File.OpenRead(file))
            {
                saved = await ParquetSerializer.DeserializeAsync<MyParquetTest>(stream);
            }
```

### for appending

supposedly appending should work with

`await ParquetSerializer.SerializeAsync(toAppend, file, new ParquetSerializerOptions { Append = true });`

but I get the exception

> System.IO.IOException: you can only append to existing streams, but current stream is empty.

so the actual working code is

```csharp
         using (var stream = System.IO.File.Open(file, FileMode.Open))
            {
                await ParquetSerializer.SerializeAsync(toAppend, stream, new ParquetSerializerOptions { Append = true });
            }
```

Have I misunderstood something, or reading the docs at the wrong place or doing something wrong in my code?

**Comment by aloneguid** [comment]
The reading overload with file name was added in the latest version. As for appending, the file should already exist and have parquet data. I'll close this but feel free to reopen and ask more questions.
