### ISSUE TITLE
ParquetTimestampAttribute has no effect on nullable DateTime properties

### ISSUE THREAD

**Issue by aden-74** [aloneguid/parquet-dotnet#408]
The documentation says that to use non-legacy date type, we need to annotate a property with [ParquetTimestamp]:
```
[ParquetTimestamp]
public DateTime TimestampDate { get; set; }
```
Yes, this works. But it does not work when you use nullable DateTime, like the following:
```
[ParquetTimestamp]
public DateTime? TimestampDate { get; set; }
```
In this case, dates are serialized as INT96 numbers.

**Comment by aloneguid** [comment]
This is fixed in 4.23.0, please feel free to validate and re-open if any issues.
