### ISSUE TITLE
 ParquetRowGroupWriter .WriteColumn throws Unable to cast object of type 'System.Object[]' to type 'System.Int64[]'

### ISSUE THREAD

**Issue by neilp-snow** [aloneguid/parquet-dotnet#41]
**Version:** Parquet.Net v3.6.0

**Runtime Version:** .Net Framework V4.7.2

**OS:** Windows

#### Expected behavior

ParquetRowGroupWriter.WriteColumn writes to file

#### Actual behavior

> ParquetRowGroupWriter.WriteColumn 

throws `Unable to cast object of type 'System.Object[]' to type 'System.Int64[]'`

### Steps to reproduce the behavior

1. Step 1.
2. Step 2.

#### Code snippet reproducing the behavior

I'm trying to convert a System.Data.DataTable to a parquet file.

Where `dt` is my DataTable:

```csharp
            using (Stream fileStream = System.IO.File.OpenWrite("C:\\test.parquet"))
            {
                using (var parquetWriter = new ParquetWriter(queryResultSchema, fileStream))
                {
                    // create a new row group in the file
                    using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
                    {
                        for(int i=0; i< dt.Columns.Count; i++)
                        {
                            DataColumn c1 = new DataColumn(fieldList[i], dt.Rows.OfType<System.Data.DataRow>().Select(r => Convert.ChangeType(r[i], dt.Columns[i].DataType)).ToArray());

                            groupWriter.WriteColumn(c1);
                        }
                    }
                }
            }
```

**Comment by shawnjones253** [comment]
@neilp-snow how did you get around this? I'm trying to do something similar.
