### ISSUE TITLE
[BUG]: ParquetSerializer doesn't support different JsonPropertyName and ClrPropertyName on struct fields

### ISSUE THREAD

**Issue by Mrinal-Thomas-Epic** [aloneguid/parquet-dotnet#410]
### Library Version

4.16.4

### OS

Windows

### OS Architecture

32 bit

### How to reproduce?

[FieldStriperCompiler](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Serialization/Dremel/FieldStriperCompiler.cs#L214) uses `field.ClrPropName ?? field.Name` when determining the property name to use when constructing the exepression.

When [MakeField](https://github.com/aloneguid/parquet-dotnet/blob/master/src/Parquet/Serialization/TypeExtensions.cs#L193) in the GetParquetSchema type extension constructs a StructField, it just passes in the column name (so the CLR property name is lost).

Suggested fix:
Make StructField constructor take in an optional parameter ClrPropertyName (and set the ClrPropName property to that parameter). In GetParquetSchema, pass in the appropriate ClrPropertyName.

### Failing test

```csharp
using Parquet.Serialization;
using System.IO;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

	public class Building
	{
		[JsonPropertyName("first_floor")]
		public Floor FirstFloor { get; set; }

		public Building(Floor firstFloor)
		{
			FirstFloor = firstFloor;
		}
	}

	public class Floor
	{
		[JsonPropertyName("num_room")]
		public int NumRooms { get; set; }

		[JsonPropertyName("room_names")]
		public string[] RoomNames { get; set; }

		public Floor(int numRooms, params string[] roomNames)
		{
			NumRooms = numRooms;
			RoomNames = roomNames;
		}
	}

	public class Program
	{
		public static async Task Main(string[] args)
		{
			Building[] buildings = new Building[]
			{
				new Building(new Floor(2, "kitchen", "bedroom")),
				new Building(new Floor(3, "kitchen", "bedroom", "bathroom")),
				new Building(new Floor(3, "office", "bedroom", "bathroom")),
			};

			Stream ms = new MemoryStream();
			await ParquetSerializer.SerializeAsync<Building>(buildings, ms);
		}
	}
```

**Comment by aloneguid** [comment]
PR merged
