### ISSUE TITLE
ParquetSerializer.SerializeAsync thread safe??

### ISSUE THREAD

**Issue by pantonis** [aloneguid/parquet-dotnet#427]
### Issue description

Im want to use ParquetSerializer.SerializeAsync to write hundreds of thousands of files using Parallel.ForEach. Is ParquetSerializer.SerializeAsync thread safe?

**Comment by aloneguid** [comment]
Yes, it should be thread safe. However, the better approach (and better performance) would be to use asynchronous API.

**Comment by pantonis** [comment]
Im using ParquetSerializer.SerializeAsync

**Comment by aloneguid** [comment]
It is then ;)

**Comment by pantonis** [comment]
Async and parallel are 2 different things :)

**Comment by aloneguid** [comment]
Only 2? Then you are using 1 thread, which is the same as `async` :) But seriously, it's thread-safe, so you can mix and match.

**Comment by pantonis** [comment]
Trying to understand this "Then you are using 1 thread, which is the same as async"

**Comment by aloneguid** [comment]
> Trying to understand this "Then you are using 1 thread, which is the same as async"

Silly joke, doesn't make sense, apologies ;)

**Comment by HeathHopkins** [comment]
I created a repo with a couple of different strategies for writing to a single parquet file from multiple threads.
https://github.com/HeathHopkins/ParquetMultithread
