### ISSUE TITLE
Exposed public classes under `System` namespace cause conflicts with other third party libraries

### ISSUE THREAD

**Issue by dfaivre** [aloneguid/parquet-dotnet#451]
### Issue description

Specifically: https://github.com/aloneguid/parquet-dotnet/blob/eb82887fec926cc0f1faf025171bfe4825c1943e/src/NetBox.cs#L1914

It probably wouldn't collide as much but a lot of the functions are declared under the root `System` namespace - so they are automatically imported.

Could these classes/functions be made internal - or at least the ones declared in the `System` namespace?

Very useful project - thank you for all the work!

**Comment by aloneguid** [comment]
Good catch, thank you.  They shutoff be all internal,  it's a bug

**Comment by aloneguid** [comment]
released

**Comment by dfaivre** [comment]
Thank you!

**Comment by aloneguid** [comment]
I'm glad you found it useful :) If you liked it, please consider giving it a star rating, it really makes a difference.

**Comment by dfaivre** [comment]
Done!
