### ISSUE TITLE
Difference with https://github.com/elastacloud/parquet-dotnet

### ISSUE THREAD

**Issue by nsulikowski** [aloneguid/parquet-dotnet#46]
What is the difference between this project and the one by elastacloud with the same name?
I'm not sure which one I would go for.
Thanks,

**Comment by skyyearxp** [comment]
i think the main project is maintained on alonguid/parquet-dotnet now.
you can search nuget, find Parquet.Net and look at the version history.
before v3.4.0 the projet url is https://github.com/elastacloud/parquet-dotnet
after 3.4.1 the project url is https://github.com/aloneguid/parquet-dotnet
so be it. :)

**Comment by nsulikowski** [comment]
good catch
