### ISSUE TITLE
string values are written as nulls in parquet file when data is set using Array SetValue Method

### ISSUE THREAD

**Issue by rajbojja** [aloneguid/parquet-dotnet#464]
### Library Version

4.23.2

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

Hello,

I have recently updated to the latest version of the Parquet.Net library and am facing issues that were previously working fine with older versions. I am attempting to run the following sample code, which generates a Parquet file, but the string values are now appearing as null.

Could you please review this and offer a solution to address the issue?

----CODE---- // create file schema
```c#
var schema = new ParquetSchema(new DataField<int?>("id"), new DataField<string>("city"));

//create data columns with schema metadata and the data you need 
var idColumn = new DataColumn(schema.DataFields[0], new int?[] { null, 2 });

var cityColumn = new DataColumn(schema.DataFields[1], new string[2]);

cityColumn.Data.SetValue("test", 0); 
cityColumn.Data.SetValue("test1", 1);

await using (Stream fileStream = System.IO.File.OpenWrite("C:\Users\Downloads\test.parquet"))
{
    using (ParquetWriter parquetWriter = await ParquetWriter.CreateAsync(schema, fileStream))
    { // create a new row group in the file
        using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
        {
            await groupWriter.WriteColumnAsync(idColumn);
            await groupWriter.WriteColumnAsync(cityColumn);
        }
    }
}
```

**Comment by aloneguid** [comment]
I appreciate your feedback, but I don't think I will modify the code, except for adding some comments, because this project is just something I do for fun in my spare time. If you really want this feature, you can try to submit a pull request for it.
