### ISSUE TITLE
[BUG]: Error on deserializing not required DateTime properties

### ISSUE THREAD

**Issue by VadymKuzin** [aloneguid/parquet-dotnet#467]
### Library Version

4.23.2

### OS

Windows 10

### OS Architecture

64 bit

### How to reproduce?

1. take parquet file which have not required int96 (datetime) column with some data
2. create corresponding model for the parquet file where create corresponding property or field (actually does not matter) with datatype DateTime? 
3. Try to run ParquetSerializer.DeserializeAsync on these parquet file into this entity

![image](https://github.com/aloneguid/parquet-dotnet/assets/157726017/ba4bff6b-b725-4f4e-a9e7-3cef49522cf8)

![image](https://github.com/aloneguid/parquet-dotnet/assets/157726017/3c0ded98-d41b-461a-b8e8-cc2b5ecc1f2d)

![image](https://github.com/aloneguid/parquet-dotnet/assets/157726017/6642bbc5-aab5-4404-857c-c33b3b62a4e5)

From what I've understood the issue is somewhere here:

![image](https://github.com/aloneguid/parquet-dotnet/assets/157726017/cf4ddad0-4ba9-4900-96e7-39a66acfae91)

Because after I did this, my test passes, but not sure because it might break something else:

![image](https://github.com/aloneguid/parquet-dotnet/assets/157726017/7d87141a-c8e3-40fd-ac6f-89e69b300669)

**Comment by lizziebeans** [comment]
Having the exact same problem.
If you downgrade to 4.20.1 it works fine, so looks like a bug was introduced in the 4.22.0 release

**Comment by VadymKuzin** [comment]
> Having the exact same problem. If you downgrade to 4.20.1 it works fine, so looks like a bug was introduced in the 4.22.0 release

Yep, currently working this way, just wanted

**Comment by aloneguid** [comment]
Fixed in latest realease. Btw you can use [Parquet Floor](https://aloneguid.github.io/parquet-dotnet/parquet-floor.html) which matches versioning with the library itself.
