### ISSUE TITLE
[BUG]: ParquetSerializer.DeserializeAsync

### ISSUE THREAD

**Issue by Zahrim** [aloneguid/parquet-dotnet#470]
### Library Version

4.23.3

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

use

`tempFile =  await ParquetSerializer.DeserializeAsync<SomeClass>(memoryStream,  cancellationToken: token);`

`public class FilialsToFilials
{
....
public DateTime? some_property { get; set; }
....
}

`
and I get an error
property 'some_property' is declared as 'some_property (System.DateTime)' but source data has it as 'some_property (System.DateTime?)'

in version 4.22.0 everything works well, but in 4.23.3 I have an error

**Comment by aloneguid** [comment]
fixed in latest release
