### ISSUE TITLE
Issue with certain stream sources

### ISSUE THREAD

**Issue by totalgit74** [aloneguid/parquet-dotnet#477]
I think you may have missed the point on issue #476 and have closed the issue in haste. 

As I wait for the entire stream to be complete from the API as far as the code is concerned it should be no different from a file stream as, to all intents and purposes, it is a file download and has completed at that point.

1. Pandas can latch onto the feed from the web API and decodes all columns correctly.
2. Parquet.net can also do so (as I wait for the entire stream to be present which means it is not different from a file stream at that point), correctly handling the stream but has an issue with the datetime64 column, all other data is decoded correctly.
3. Parquet.net does not have an issue if pandas persists the file for it.

It’s as if the `stream.ReadParquetAsDataFrameAsync` method needs to be able to accept `ParquetOptions` whereby the `TreatLargeIntegersAsDates` can be set to true which may well solve the problem. I believe `ParquetReader` can accept such a parameter in its read to its own table type but this extension method providing a `Microsoft.Data.Analysis.DataFrame` does not.

_Originally posted by @totalgit74 in https://github.com/aloneguid/parquet-dotnet/issues/476#issuecomment-1956350077_

**Comment by aloneguid** [comment]
Sorry this is an old issue. Woudl adding an overload to 

```csharp
        public static async Task<DataFrame> ReadParquetAsDataFrameAsync(
            this Stream inputStream, CancellationToken cancellationToken = default) {
...
```
that accepts also `ParquetOption` solve the issue?

**Comment by aloneguid** [comment]
closing due to no response
