### ISSUE TITLE
Parquet.Net Version 3.6.0 assembly not signed with a strong name

### ISSUE THREAD

**Issue by AidasTruskauskas** [aloneguid/parquet-dotnet#48]
**Version:** Parquet.Net v...

Parquet.Net -Version 3.6.0 (https://www.nuget.org/packages/Parquet.Net/3.6.0)

**Runtime Version:** .Net Framework v, .Net Core v etc.
 All of them:
 * netstandard1.4
 * netstandard1.6
 * netstandard2.0
 * netstandard2.1

**OS:** Windows/Linux/MacOSX v etc.
* Windows 10;

#### Expected behavior

dll's should be signed with a strong name. Now I am not able to add them to GAC;

#### Actual behavior
When I try to install the libraries to GAC using gacutl, I get an Error:
"Failure adding assembly to the cache: Attempt to install an assembly without a strong name"

I have used previous version (3.3.0) before, and it did not have this issue;

### Steps to reproduce the behavior

1. Step 1.
Open "Command Prompt for  VS 2019" as Administrator;
2. Step 2.
Execute a command:
* gacutil /i "C:\Temp\Parquet.Net.3.6.0\lib\netstandard1.4\Parquet.dll"
* gac/util /i "C:\Temp\Parquet.Net.3.6.0\lib\netstandard2.0\Parquet.dll"

Output:
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Failure adding assembly to the cache: Attempt to install an assembly without a strong name

**Comment by atomaras** [comment]
I am having the same issue with 3.7.1. I cannot use it unless it's signed. @aloneguid Any plans on adding this?

**Comment by AidasTruskauskas** [comment]
I was able to workaround this issue in version 3.6.0 by manually signing the parquet.dll file.
However, version 3.7.1 is referencing another unsigned library (IronSnappy) and my workaround is not working anymore. 

Once I manually sign the parquet.dll and reference it in the project. the application is failing with this error:
_Could not load file or assembly 'IronSnappy, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)_

As explained In this blogpost (https://blog.xoc.net/2015/12/could-not-load-assembly-because.html)
"An assembly that has strong name can only reference other assemblies with strong names."
and " The best solution is to get the maintainers to sign the assembly so everyone doesn't run into this problem."

@aloneguid , can we expect this issue to be resolved in the upcoming releases?

Thanks!

**Comment by aloneguid** [comment]
Hello. Sorry for delays in replies, I find it hard to deal with non primary work during the lockdown. I have removed strong signature for the reason it was "fake" i.e. it doesn't prove anything. Strong signature is meant to prove that the library was signed by a certain trusted body, however in my case the dll's private key (.snk) was stored in the repository itself. Remember that everything is open-source and free. Anyone can use this private key to sign their own build no matter how it was done and which changes were made which sort of defeats the purpose of strong name. In other words, strong signature only adds a wrong impression that this library is trusted in terms of who has built it.

If we want it to be really strong there are a few things to consider:
- Someone needs to pay for a code signing certificate, probably annually. This project has never made any money and so far received zero contributions and cannot afford one.
- If you want to make your own build of parquet.net with the same strong name you won't be able to - there can be only one owner of the code signing cert.

I understand though that some scenarios require the presence of the strong name, and happy for the community to decide how to deal with this - I'll go with your advise.

**Comment by AidasTruskauskas** [comment]
Hi @aloneguid, Thanks very much for your reply. Everything you say totally makes sense.

However, with the new 3.7.1 version having another unsigned dependency (IronSnappy) adds more complexity. Going forward, GAC dependent implementations will not be able just to reference Parquet.Net build and will require a custom build witch is not Ideal...

In my case using the "Fake" signature, would make the life easier. But I totally understand, that you must consider the whole picture here.

Please let us know, what way you will go forward.
Thanks!

**Comment by aloneguid** [comment]
@AidasTruskauskas I totally understand, therefore patching to include a fake strong signature (signing key has no password and included here in git). IronSnappy dependency is also strong signed now (I'm an owner of that). Please try v3.7.3.

**Comment by atomaras** [comment]
thank you for this!
