### ISSUE TITLE
[BUG]: Enum Serialization/Deserialization update

### ISSUE THREAD

**Issue by seoktaekim** [aloneguid/parquet-dotnet#488]
### Library Version

4.23.4

### OS

OS

### OS Architecture

ARM 64

### How to reproduce?

1. Use class serialization with enum property
2. Produces no error but enum is not updated when parquet file is deserialized

genius feature btw

**Comment by Pragmateek** [comment]
Hello,

same issue with `4.24.0-pre.2`:
```
using Parquet.Serialization;

var inputA = new A { E = E.One };

Console.WriteLine($"Input: {inputA.E}");

using var ms = new MemoryStream();
await ParquetSerializer.SerializeAsync([inputA], ms);

ms.Seek(0, SeekOrigin.Begin);

var outputA = (await ParquetSerializer.DeserializeAsync<A>(ms)).Single();

Console.WriteLine($"Output: {outputA.E}");

enum E
{
    Zero,
    One,
}

class A
{
    public E E { get; set; }
}
```
Result:
```
Input: One
Output: Zero
```
Is there a workaround?

Thanks,

Mickael

**Comment by aloneguid** [comment]
Unfortunately enums are not yet supported. As a workaround you can mark enum as ignored property and expose a get/set property exposing one of the supported types. This is a popular ask though, so I'll have to implement this in the next release.

**Comment by Pragmateek** [comment]
OK too bad.
As of now I've used DTOs which map enumes to strings.
Indeed that would be great as this is often used.
Maybe you could let the choice between mapping the integer or string value of each enum entry.

**Comment by aloneguid** [comment]
I have initial support for this already, which serialises enums to their underlying type (int or else).

**Comment by aloneguid** [comment]
You can try the `-pre.5` version for support of this.

**Comment by Pragmateek** [comment]
> I have initial support for this already, which serialises enums to their underlying type (int or else).

Indeed with `-pre.4` the integer value was serialized but under field `value__`.

**Comment by Pragmateek** [comment]
> You can try the `-pre.5` version for support of this.

The roundtrip is working with `-pre.5`.
Thanks again. :)

**Comment by Pragmateek** [comment]
Trying to plug the Parquet into AWS Athena and diving into the schema I see that the enum integer value are serialized.
Is it be possible to serialize the names? Maybe by annotating the field?
Thanks

**Comment by Pragmateek** [comment]
In the meantime, is there a way to hook into the serialization process to customize the way each field is serialized?
Thanks
