### ISSUE TITLE
Unable to write Timestamp Logical Type

### ISSUE THREAD

**Issue by kharlm16** [aloneguid/parquet-dotnet#492]
### Issue
Writing DateTimes using DateTimeDataField uses TIMESTAMP_MILLIS Converted Type instead of TIMESTAMP(isAdjusted, unit) Logical Type.
Is this by design or are there any plans to support writing TIMESTAMP logical type?

**Comment by aloneguid** [comment]
I have no plans to support this at the moment, so happy for you to pick it up.
