### ISSUE TITLE
Parquet file directly in binary

### ISSUE THREAD

**Issue by matmiranda** [aloneguid/parquet-dotnet#497]
### Issue description

Does this library not support generating parquet file in byte array?

The idea is to generate file as binary without saving in the path.

It's possible ?

**Comment by aloneguid** [comment]
Just write to memory stream,  which is essentially a byte array?

**Comment by matmiranda** [comment]
Do you have an example of writing to the memory stream? My idea is to generate a file directly in AWS Bucket S3.

**Comment by aloneguid** [comment]
Closing as this is unrelated to this library. See .net reference documentation for `MemoryStream`.
