### ISSUE TITLE
Working with null values when reading a Parquet file in FSharp

### ISSUE THREAD

**Issue by MiaMeyerMakes** [aloneguid/parquet-dotnet#499]
### Issue description

My team and I have tried implementing parquet dotnet to improve unit test runtime, but as there is virtually no documentation available in implementing parquet dotnet in F#, we have struggled immensely to get our code to work. Our biggest problem is reading in a dataset with null values. The code throws an exception when reading these values and we can't find any documentation that addresses this problem in the context of F#.

**Comment by aloneguid** [comment]
No

**Comment by MiaMeyerMakes** [comment]
The audacity.
