### ISSUE TITLE
ParquetConvert.Serialize issue in new version;

### ISSUE THREAD

**Issue by AidasTruskauskas** [aloneguid/parquet-dotnet#51]
**Version:** Parquet.Net v3.6.0

**Runtime Version:** .Net Framework v 4.6.1

**OS:** Windows 10

#### Expected behavior
flowing example should run fine and generate a parquet file:
https://gist.github.com/AndyCross/eb0c3392dc421fbee54f826a03e63a74

Tried the same example with Old Parquet.Net version (3.0.5) and it's working as expected

Please describe how you expect **Parquet.Net** to work.

#### Actual behavior
while running (console application in VS 2019) this example I get an error:
System.Reflection.Emit.Lightweight is not supported on this platform.

### Steps to reproduce the behavior

1. Step 1. In Visual Studio Create a new Console App (.NET Framework) project (Net Framework v 4.6.1);
2. Step 2. Install Parquet.Net 3.6.0 NuGet Package;
3. Step 3. Run the program;

#### Code snippet reproducing the behavior

https://gist.github.com/AndyCross/eb0c3392dc421fbee54f826a03e63a74

**Comment by aloneguid** [comment]
I think this is because I stopped including .net 4.6.1 build into nuget as it's supposed to be compatible with .net standard 1.4, but looks like it's not!
