### ISSUE TITLE
Serializes the nullable TimeSpan property

### ISSUE THREAD

**Issue by pawelciupkaOnwelo** [aloneguid/parquet-dotnet#517]
### Issue description

Hello,

Will it be possible to serialize nullable TimeSpan class properties in the future?

Class:
```
public class Downtime
{
    public TimeSpan? Duration { get; set; }
}
```

Serialization code:
```
var data = new List<Downtime>() { new Downtime() { Duration = null } }

using MemoryStream memoryStream = new MemoryStream();
if (memoryStream != null)
{
    await ParquetSerializer.SerializeAsync(data, memoryStream, cancellationToken: cancellationToken);
    // ...
}
```

Error message:
```
Expression of type 'System.Nullable`1[System.TimeSpan]' cannot be used for parameter of type 'System.TimeSpan' of method 'Void Add(System.TimeSpan)' (Parameter 'arg0')
```

Thank you in advance.

**Comment by aloneguid** [comment]
This should work with no issues. Can you try latest preview nuget?

**Comment by pawelciupkaOnwelo** [comment]
I have cleaned and rebuild the entire solution to make sure I am using the latest version (4.23.5) and the problem still persists.

![image](https://github.com/aloneguid/parquet-dotnet/assets/120187777/390a10d1-4b4b-407a-9080-9f0ee9667331)

**Comment by pawelciupkaOnwelo** [comment]
> This should work with no issues. Can you try latest preview nuget?

I made mistake. I mean TimeSpan insted of Timestamp.

**Comment by aloneguid** [comment]
I meant latest "preview" version. But 4.24.0 was just released, please try to update now.

**Comment by pawelciupkaOnwelo** [comment]
> I meant latest "preview" version. But 4.24.0 was just released, please try to update now.

Used `4.24.0` and it is working. Thanks for support!
