### ISSUE TITLE
Breaking change was introduced with version 4.23.5

### ISSUE THREAD

**Issue by stewild** [aloneguid/parquet-dotnet#523]
### Issue description

The fix for #496 is actually a breaking change. Files written with version 4.23.4 cannot be read with version 4.23.5.

**Comment by aloneguid** [comment]
It's not a breaking change but a bug fix.

**Comment by stewild** [comment]
For every consumer of the package that is reading or writing GUIDs, this is a breaking change because of the changed behavior. I agree that this is a bug fix, but it should be at least marked as a breaking change in the release notes.

**Comment by aloneguid** [comment]
Yes you are right.
