### ISSUE TITLE
[Feature Request] Add GeoParquet support and ability to read a file over HTTP

### ISSUE THREAD

**Issue by donnyv** [aloneguid/parquet-dotnet#524]
### Issue description

GeoParquet is built on top of Parquet. Currently there is no way to access this using C# with Spatial Filters. This would be huge in the GIS community. https://geoparquet.org/ 

The other request is the ability to access a Parquet and GeoParquet file across HTTP using range requests. Currently I could only find Duckdb to do this. https://duckdb.org/docs/guides/network_cloud_storage/http_import

**Comment by aloneguid** [comment]
Hi. I don't want to bring bad news, but this might be outside the scope of this library. I do like them though. Each can be a separate subproject on it's own.
