### ISSUE TITLE
Add de-serializer options to handle Pascal case similar to JsonSerializerOptions.PropertyNameCase

### ISSUE THREAD

**Issue by ErikApption** [aloneguid/parquet-dotnet#536]
### Issue description

If you need to handle parquet files that use lower case column names and match them with nicely formatted Pascal case c# classes, the only way is to add `[JsonPropertyName(...)]` to each property.
Any chances to get a deserializer property similar to [PropertyNameCase](
https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializeroptions.propertynamecaseinsensitive?view=net-8.0#system-text-json-jsonserializeroptions-propertynamecaseinsensitive) in `System.Text.Json`?

**Comment by Pragmateek** [comment]
Same need here, and unfortunately I currently cannot use `JsonPropertyName` because there is a version conflict I've not managed to sort out.

**Comment by aloneguid** [comment]
I'm working on functionality at the moment which will support this, no promises but will be part of the next release.

**Comment by aloneguid** [comment]
I think the work on [this](https://aloneguid.github.io/parquet-dotnet/serialisation.html#ignoring-property-casing) is done, you can try in `5.0.0-pre.3` nuget.

**Comment by aloneguid** [comment]
Released.

**Comment by Pragmateek** [comment]
Thanks, it is indeed working as expected. 👍
