### ISSUE TITLE
[BUG]: No rows read from an Amazon CUR 2.0 Parquet File

### ISSUE THREAD

**Issue by drusellers** [aloneguid/parquet-dotnet#540]
### Library Version

4.24.0

### OS

Mac

### OS Architecture

ARM 64

### How to reproduce?

1. Download an AWS CUR 2.0 file (Parquet + Snappy compression)

```csharp
using Parquet;

var pwd = Environment.CurrentDirectory;
var path = Path.Join(pwd, "ParquetDaily-00001.snappy.parquet");
if(!File.Exists(path)) throw new Exception("Missing file");
var p = await ParquetReader.ReadTableFromFileAsync(path);
Console.WriteLine(p.Count); // outputs 0
```

Expecting 8,000+ rows

Note: It does get the 114 columns correct.

DuckDB can open the parquet file (used to conform its not a trash file)

**Comment by aloneguid** [comment]
What are those CUR 2.0 files? Are you able to share an example?

**Comment by aloneguid** [comment]
@drusellers 8719 rows, seems to be no issues. Replied by email.

**Comment by aloneguid** [comment]
@drusellers this may be caused by a regression in 4.24. Please try the latest preview and reopen if it still persists.
