### ISSUE TITLE
System.IO.FileNotFoundException thrown while using Append mode in Class serialization

### ISSUE THREAD

**Issue by xeonfusion** [aloneguid/parquet-dotnet#541]
### Issue description

@aloneguid thanks for creating this useful library. Please advise about this:

OS: OS X 14.5 Env: .NET8 Parquet.Net Version: 4.24.0

I'm trying to serialize a List class containing six strings with this schema: https://github.com/xeonfusion/VSCaptureMP/blob/12321896f8beec85b271fd20430e703f83d89723/Class3.cs#L159

The List is populated by converting serial port byte arrays (through multiple read events) into strings. The List data needs to be written in multiple batches, each time the serial port receives data, into a single Parquet export file. 

This works without issues using the inbuilt .NET JSON serializer https://github.com/xeonfusion/VSCaptureMP/blob/12321896f8beec85b271fd20430e703f83d89723/Class3.cs#L2106.

But using the same populated List with the ParquetSerializer.SerializeAsync method (with Append option true) throws a FileNotFound exception:

```c#
Exception has occurred: CLR/System.IO.FileNotFoundException
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll: 'Could not find file '/Users/Documents/DataExport.parquet'.'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
   at Parquet.Serialization.ParquetSerializer.<SerializeAsync>d__9`1.MoveNext()
   at VSCaptureMP.MPSerialPort.<ExportNumValListToParquetAsync>d__119.MoveNext() in /Users/Documents/VSCaptureMP/Class3.cs:line 2163
   at VSCaptureMP.MPSerialPort.<ExportNumValListToParquet>d__118.MoveNext() in /Users/Documents/VSCaptureMP/Class3.cs:line 2136'

``` 
I followed the recommended method to append data: https://aloneguid.github.io/parquet-dotnet/serialisation.html#appending-to-files

I have tried changing the FileStream FileMode to FileMode.Append (instead of FileMode.Open that is used in ParquetSerializer.cs) but it still throws an exception:

``` c#
if (NumericValList.Count != 0)
            {
                if (m_parquetappendflag == false) //flag set to false for first data batch
                {
                    await ParquetSerializer.SerializeAsync(NumericValList, pathparquet); //This works but overwrites data
                }
                else
                {
                    using (FileStream _FileStream = new FileStream(pathparquet, FileMode.Append, FileAccess.ReadWrite))
                    {
                        await ParquetSerializer.SerializeAsync(NumericValList, _FileStream, new ParquetSerializerOptions { Append = true });

                        // throws exception File Not Found if used this way or if used with the file path and ParquetSerializerOptions directly set to true

                        _FileStream.Close();
                    }
                }
            }
``` 
If the library implements a concurrent queue internally for writing data batches, the Append flag option in ParquetSerializerOptions (that causes issues) probably may not be needed.

How do I append a continuously updated List to a single Parquet file, updating the records each time, without file access errors?

Thanks.

**Comment by xeonfusion** [comment]
@aloneguid is there a workaround for this issue or is it not fixable by the library? Even appending to a memory stream doesn't not produce an output (zero byte files are written). The documentation mentions that appends are possible but it doesn't work at all on OS X.

**Comment by aloneguid** [comment]
This looks like an error in your  ode unrelated to this library. Try to reproduce this in a console app with no dependencies.

**Comment by xeonfusion** [comment]
Could you suggest the cause of the error, couldn't find any reason so far? Has the library tested been tested on Mac OS X environment?
