### ISSUE TITLE
[BUG]: ParquetSerializer.DeserializeAsync (fasm.Field is null)

### ISSUE THREAD

**Issue by brendanbignell** [aloneguid/parquet-dotnet#548]
### Library Version

4.25

### OS

Windows 11

### OS Architecture

64 bit

### How to reproduce?

I used  the following to create a Parquet file from a List<Tick> (same behaviour with a class).
    await ParquetSerializer.SerializeAsync(sortedTicks, parquetFilePath);

However if I immediately try to load the file it appears full of default values.
    IList<Tick> ticksP = await ParquetSerializer.DeserializeAsync<Tick>(parquetFilePath);

Tracing through the code in the debugger reveals an exception being thrown from ParquetSerializer:279 because this comparison returns false : fasm.Field.Equals(dataField).
I can see this is because the dataField.SchemaElement is set to a valid element, but in fasm.Field is null.

Here is a sample file which will trigger the error when read: https://1drv.ms/u/s!AhDUHssG2nbYmoM7f0vBU3Lm8-Thow?e=TPGsP9

The Floor app can display the file fine.

****************************************************

public struct Tick
{
    private static int tickSize = 100000;  //  TODO - Look this up for the specific instrument

    [ParquetRequired]
    public long Timestamp { get; set;}

    [ParquetRequired]
    public float AskPrice { get; set; }

    [ParquetRequired]
    public float BidPrice { get; set; }

    [ParquetRequired]
    public float AskVolume { get; set; }

    [ParquetRequired]
    public float BidVolume { get; set; }

**Comment by aloneguid** [comment]
Do you mind trying the latest pre-release? I have not encountered the error:

```csharp
        [Fact]
        public async Task TestData_548() {
            // generate list of ticks
            var ticks = Enumerable.Range(0, 10).Select(i => new Tick {
                Timestamp = i,
                AskPrice = i + 0.1f,
                BidPrice = i + 0.2f,
                AskVolume = i + 0.3f,
                BidVolume = i + 0.4f
            }).ToList();

            await ParquetSerializer.SerializeAsync(ticks, path);

            IList<Tick> ticks2 = await ParquetSerializer.DeserializeAsync<Tick>(path);


        }
```

**Comment by aloneguid** [comment]
fixed in v5
