### ISSUE TITLE
When serializing to stream, cursor is not at the beginning

### ISSUE THREAD

**Issue by bsrobinson** [aloneguid/parquet-dotnet#549]
### Library Version

4.24.0

### OS

Windows

### OS Architecture

64 bit

### How to reproduce?

I'm using the following code to convert some data into a parquet file for uploading to a remote server
```csharp
MemoryStream stream = new();
await ParquetSerializer.SerializeAsync(data, stream);
```

Then adding to my http client request as follows:
```csharp
request.Content = new MultipartFormDataContent {
    { new StreamContent(stream), "file", "data.parquet" }
};
```

I was getting a failure response from the server because the file hadn't been sent.

Fix is to add this line between the code snippets above:
```csharp
stream.Seek(0, SeekOrigin.Begin);
```

**The bug**
I would expect the stream to be in a usable state following the Serialize() function call, however the cursor is at the end and needs to be reset before it can be used.

Maybe by design, but thought it was worth raising!

**Comment by aloneguid** [comment]
This is by design. Most of the streaming API in general work this way. Rewinding the stream would also introduce a requirement of a seekable stream which would not allow to use write-forward-only streams.
