### ISSUE TITLE
Sample given in https://aloneguid.github.io/parquet-dotnet/writing.html does not work

### ISSUE THREAD

**Issue by abskulkarni** [aloneguid/parquet-dotnet#554]
### Issue description

There is one quick sample given for writing parquet file in https://aloneguid.github.io/parquet-dotnet/writing.html

***
// create file schema
var schema = new ParquetSchema(
    new DataField<int>("id"),
    new DataField<string>("city"));

//create data columns with schema metadata and the data you need
var idColumn = new DataColumn(
   schema.DataFields[0],
   new int[] { 1, 2 });

var cityColumn = new DataColumn(
   schema.DataFields[1],
   new string[] { "London", "Derby" });

using(Stream fileStream = System.IO.File.OpenWrite("c:\\test.parquet")) {
    using(ParquetWriter parquetWriter = await ParquetWriter.CreateAsync(schema, fileStream)) {
        parquetWriter.CompressionMethod = CompressionMethod.Gzip;
        parquetWriter.CompressionLevel = System.IO.Compression.CompressionLevel.Optimal;
        // create a new row group in the file
        using(ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup()) {
            await groupWriter.WriteColumnAsync(idColumn);
            await groupWriter.WriteColumnAsync(cityColumn);
        }
    }
}
***

This sample does not work. This generates file with no content. 
I used it in below way:
1. Created a library project in .NET standard 2.0 & referred Parquet.NET NuGet package there.
2. Created a public method and pasted whole sample code as it is in that method
3. Created a .NET framework console application (That is our requirement) and called library project's public method from this console application
4. It created test.parquet but with no contents.

Below is public method of library project
***
public async Task SampleMethod()
{
    // create file schema
    var schema = new ParquetSchema(
        new DataField<int>("id"),
        new DataField<string>("city"));

    //create data columns with schema metadata and the data you need
    var idColumn = new Parquet.Data.DataColumn(schema.DataFields[0],new int[] { 1, 2 });

    var cityColumn = new Parquet.Data.DataColumn(schema.DataFields[1],new string[] { "London", "Derby" });

    using (Stream fileStream = System.IO.File.OpenWrite("f:\\test.parquet"))
    {
        using (ParquetWriter parquetWriter = await ParquetWriter.CreateAsync(schema, fileStream))
        {
            // create a new row group in the file
            using (ParquetRowGroupWriter groupWriter = parquetWriter.CreateRowGroup())
            {
                await groupWriter.WriteColumnAsync(idColumn);
                await groupWriter.WriteColumnAsync(cityColumn);
            }
        }
    }
}
***

**Comment by aloneguid** [comment]
sorry, can't reproduce this
