### ISSUE TITLE
Creates invalid files with Snappy compression and certain amount of data

### ISSUE THREAD

**Issue by superkartoffel** [aloneguid/parquet-dotnet#56]
When creating Parquet files with a certain size the Snappy compression create invalid output.
I setup a simple test that write random objects and reads them back in:
https://dotnetfiddle.net/g22ORE

It works fine for 1000 objects, but not 2000 objects. 
It throws a Unhandled exception. System.IO.IOException: corrupt input
   at IronSnappy.SnappyReader.Decode(Span`1 dst, ReadOnlySpan`1 src)
Using any other compression mechanism than snappy also solves the issue.

**Version:** Parquet.Net v3.7.1

**Runtime Version:** .Net Core v3.1

#### Code snippet reproducing the behavior

```csharp
using System;
using System.IO;
using System.Linq;
using Parquet;

public class TestStructure
{
	public string StringValue
	{
		get;
		set;
	}

	public DateTimeOffset DateValue
	{
		get;
		set;
	}

	public double DoubleValue
	{
		get;
		set;
	}

	public static TestStructure[] GenerateTestStructures(int size)
	{
		var ret = new TestStructure[size];
		for (int i = 0; i < size; i++)
		{
			ret[i] = new TestStructure()
			{DateValue = DateTimeOffset.Now, DoubleValue = i, StringValue = Guid.NewGuid().ToString()};
		}

		return ret;
	}
}

public class Program
{
	public static void RunTest(int n, CompressionMethod compressionMethod)
	{
		var testData = TestStructure.GenerateTestStructures(n);
		var memoryStream = new MemoryStream();
		ParquetConvert.Serialize(testData, memoryStream, null, compressionMethod);
		memoryStream.Position = 0;
		var result = ParquetConvert.Deserialize<TestStructure>(memoryStream);
		if (n == result.Length)
			Console.WriteLine($"Test Succeeded with n={n} compression={compressionMethod}.");
	}
	
	public static void Main()
	{
		RunTest(2000, CompressionMethod.Gzip); // works
		RunTest(1000, CompressionMethod.Snappy); // works
		RunTest(2000, CompressionMethod.None); // works
		
		RunTest(2000, CompressionMethod.Snappy); // throws System.IO.IOException: corrupt input
	}
}
```

**Comment by mj-rittermann** [comment]
I have just tried the fiddle with Parquet.Net v3.6.0. Here everything seems to work. I guess it is a bug introduced in a later version.

**Comment by skyyearxp** [comment]
the problem have been solved.
https://github.com/aloneguid/IronSnappy/releases v1.2.2

but no new version released.
https://github.com/aloneguid/parquet-dotnet

**Comment by aloneguid** [comment]
releasing fix in 3.7.2

**Comment by vc-74** [comment]
FYI I had a similar issue described [here](https://github.com/elastacloud/parquet-dotnet/issues/463)

**Comment by aloneguid** [comment]
@vc-74  is it resolved? Feel free to reopen if not.

**Comment by vc-74** [comment]
@aloneguid Yes, thanks for the quick resolution!
