### ISSUE TITLE
[BUG]: Parquet compression is not working inside a Linux container in Docker Desktop

### ISSUE THREAD

**Issue by ppczouz** [aloneguid/parquet-dotnet#563]
### Library Version

5.0.0

### OS

Ubunt Linux

### OS Architecture

64 bit

### How to reproduce?

1. Added Parquet.net 5.0.0, and executed the following line:
`ParquetSerializer.SerializeAsync<EventData>(dataList, stream, new ParquetSerializerOptions() { CompressionMethod=Parquet.CompressionMethod.Snappy});`
Where EventData is a class representing the schema, and Stream is an open stream on Azure Blob Storage

2. Compile and run this as a console application on both Windows and WSL2 Ubuntu works perfect. 

3. Compile and run as Docker container in Docker Desktop (Linux), the above statement would only produce a parquet file containing the schema, but no data. 
4. Changing the compression methods yields to the same results. Only when setting compression to None does it include the data in the parquet file.

I do not see any exceptions or other items showing up on the log stream.

**Comment by aloneguid** [comment]
What base image are you using?

**Comment by ppczouz** [comment]
> What base image are you using? I'm wondering if you are running this on musl runtime (Alpine etc.)

FROM mcr.microsoft.com/azure-functions/dotnet:4 AS base

**Comment by aloneguid** [comment]
This should be sorted now, please check.

**Comment by ppczouz** [comment]
Awesome, thank you.
Using 5.0.1, confirmed, it is now working properly.
