### ISSUE TITLE
[BUG]: Corrupt files are produced when saving DataFrame to Parquet

### ISSUE THREAD

**Issue by alex-g-axion** [aloneguid/parquet-dotnet#575]
### Library Version

4.25.0

### OS

Windows 11

### OS Architecture

64 bit

### How to reproduce?

This is related to https://github.com/aloneguid/parquet-dotnet/issues/558, I managed to reliably reproduce it.

1. Build the attached program and run it by passing "data\ElectrodeMetrics.csv" as an argument.  Ex:  "Df2Pq data\ElectrodeMetrics.csv"

Output:

> Converting ElectrodeMetrics.csv to parquet.
> file was in use for 00:00:00.0078764
> File ElectrodeMetrics.pq is corrupted: System.InvalidOperationException: don't know how to skip type Uuid
>    at Parquet.Meta.Proto.ThriftCompactProtocolReader.SkipField(CompactType compactType)
>    at Parquet.Meta.PageHeader.Read(ThriftCompactProtocolReader proto)
>    at Parquet.File.DataColumnReader.ReadAsync(CancellationToken cancellationToken)
>    at Parquet.ParquetExtensions.ReadParquetAsDataFrameAsync(Stream inputStream, CancellationToken cancellationToken)
>    at Df2Pq.Program.SaveAndVerify(DataFrame aTable, FileInfo aDestination) in C:\Users\agdalevich\source\repos\Df2Pq\Program.cs:line 197
>    at Df2Pq.Program.SaveAndVerify(DataFrame aTable, FileInfo aDestination) in C:\Users\agdalevich\source\repos\Df2Pq\Program.cs:line 197!

Program and data files to reproduce the issue:  
[Df2Pq.zip](https://github.com/user-attachments/files/17962192/Df2Pq.zip)

**Comment by aloneguid** [comment]
I think you have a bug here (Program.cs, line 166):

```csharp
await using FileStream fStream = aDestination.OpenWrite();
```

This opens existing file and writes data on top, so you get dirty file consisting of previous + new data. If you delete the file before writing it seems to be just fine.

**Comment by alex-g-axion** [comment]
Thank you!  Looks like this is the cause.  I cannot reproduce the issue after using `Open(FileMode.Create)` instead of `OpenWrite()`  .
