### ISSUE TITLE
[BUG]: The PAR1 magic number is sometimes duplicated at the end of the file.

### ISSUE THREAD

**Issue by naveenkrsh** [aloneguid/parquet-dotnet#577]
### Library Version

4.16.4

### OS

Ubuntu Linux

### OS Architecture

64 bit

### How to reproduce?

Not able to reproduce
![image](https://github.com/user-attachments/assets/5bf8be09-d606-48a6-bf5b-6d7f417d2945)

**Comment by eeabhishekmore** [comment]
@aloneguid  any input from you will be super useful. This is an intermittent issue which we have not been able to reproduce. Removing the last 5 bytes from left file (NULPAR1), fixes the file..
