### ISSUE TITLE
does Multithreaded Reads support? how to read fast ?

### ISSUE THREAD

**Issue by skyyearxp** [aloneguid/parquet-dotnet#62]
i use parquet-dotnet to read big parquet file, but it seems little slow. read all rowgroups pyarrow take 14 seconds, but parquet-dotnet take 42 seconds.

` private void ReadParquet(string file)
{
//遍历读取所有rowgroup c# 42秒 python_pyarrow 14秒

        using (var reader = ParquetReader.OpenFromFile(file))
        {
            //var schema = reader.Schema;
            var dataFields = reader.Schema.GetDataFields();
            var cnt = reader.RowGroupCount;

            for (var i = 0; i < cnt; i++)
            {
                using (var groupReader = reader.OpenRowGroupReader(i))
                {
                    var columns = dataFields.Select(groupReader.ReadColumn);

                    foreach(var column in columns)
                    //Parallel.ForEach(columns, column =>
                    {
                        var data = column.Data;
                    }
                    //);

                    //foreach (DataField field in reader.Schema.GetDataFields())
                    //{
                    //    var dataColumn = groupReader.ReadColumn(field);
                    //}
                }
            }
        }

    }`
https://arrow.apache.org/docs/python/parquet.html

Multithreaded Reads
Each of the reading functions by default use multi-threading for reading columns in parallel. Depending on the speed of IO and how expensive it is to decode the columns in a particular file (particularly with GZIP compression), this can yield significantly higher data throughput.

**Comment by skyyearxp** [comment]
the problem have been solved.
https://github.com/aloneguid/IronSnappy/releases v1.2.2

but no new version released.
https://github.com/aloneguid/parquet-dotnet

**Comment by 4eyecoder** [comment]
Did you figure out any optimizations for this?  I have a 11GB file that I wanted to process, but it seems like the ParquetReader keeps tons of data in memory.

**Comment by aloneguid** [comment]
It only keeps data that you read in memory. Read what you need and in smaller chunks.

**Comment by 4eyecoder** [comment]
After more research I found that it was the row group overhead that was causing me problems.  I was processing files contain
ing 10,000,000's of rows with a row group size of 1,000.  Increasing my row group size to 10,000 resulted in vast performance improvements.

Here is an example of the overhead:

![a74c4a73_FirstRowGroup_Capture](https://user-images.githubusercontent.com/16946773/94429053-bc716100-015f-11eb-9d61-79fadc291332.PNG)
