### ISSUE TITLE
InvalidCastException when writing DateTime columns

### ISSUE THREAD

**Issue by msitt** [aloneguid/parquet-dotnet#66]
**Version:** Parquet.Net v3.7.4

**Runtime Version:** .Net Core v3.0

**OS:** Windows

#### Expected behavior

According to [Supported Types](https://github.com/aloneguid/parquet-dotnet/blob/develop/doc/types.md), DateTime is supported.

#### Actual behavior

When attempting to write a DateTime column, I get the following exception
```
System.InvalidCastException : Unable to cast object of type 'System.DateTime' to type 'System.DateTimeOffset'.
```

### Steps to reproduce the behavior

Run the Unit Test below. In the constructor of `DataField<DateTime>`, the `IDataTypeHandler handler` returned is actually the `DateTimeOffset` one.

#### Code snippet reproducing the behavior

```csharp
using System;
using Parquet.Data;
using System.IO;
using Xunit;

namespace Parquet.Test
{
   public class DateTimeTypeTest : TestBase
   {
      [Fact]
      public void Write_read_DateTime()
      {
         var ms = new MemoryStream();
         var date = new DataField<DateTime>("date");

         DateTime now = DateTime.Now;

         //write
         using (var writer = new ParquetWriter(new Schema(date), ms))
         {
            using (ParquetRowGroupWriter rg = writer.CreateRowGroup())
            {
               rg.WriteColumn(new DataColumn(date, new[] { now }));
            }
         }

         //read back
         using (var reader = new ParquetReader(ms))
         {
            using (ParquetRowGroupReader rg = reader.OpenRowGroupReader(0))
            {
               Assert.Equal(now, ((DateTime[])rg.ReadColumn(date).Data)[0]);
            }
         }
      }
   }
}

```

**Comment by vladislav-stolyarov** [comment]
Same for me

**Comment by ccruden-shookiot** [comment]
Same here. Workaround is to convert the DateTimes to DateTimeOffsets.

**Comment by destinyboyer** [comment]
I am also experiencing this. It seems that the CLR type is being incorrectly set to `DateTimeOffset` in the registered `Schema`.

**Comment by aloneguid** [comment]
Closing as seems to be stale. Feel free to raise a PR later if you're still interested.
