### ISSUE TITLE
Appending to file in ADLS Gen2

### ISSUE THREAD

**Issue by daxborde** [aloneguid/parquet-dotnet#71]
**Version:** Parquet.Net 3.7.7

**Runtime Version:** .Net Framework 4.6.1

**OS:** Windows 10

#### Actual behavior

Attempting to append to a parquet file in Azure Data Lake Storage (ADLS) Gen2 causes the following exception:

`System.IO.IOException: destination stream must be seekable for append operations.`

(This error is thrown during execution of the code snippet below.)

#### Expected behavior

Appending to a parquet file in ADLS Gen2 should work.

Clearly the stream provided by the Blob storage API is not seekable, but does this make append operations on ADLS impossible with this library? How should small updates be handled? (eg. 10 new records come in from an external source, and we wish to update the parquet file.) Am I missing something, and it is actually possible to append via some other means?

#### Code snippet reproducing the behavior
```csharp
CloudBlobClient client = ...; // More info at [1] if necessary
CloudBlobContainer container = client.GetContainerReference(containerName);
await container.CreateIfNotExistsAsync();

string pqFileName = "asdf.parquet";
CloudBlockBlob parquetBlob = container.GetBlockBlobReference(pqFileName);

// Redefine the same schema used in asdf.parquet (can also get it by reading the file)
Parquet.Data.DataField[] dataFields = ...;
Schema schema = new Parquet.Data.Schema(dataFields);

Table table = ...; // New records with same schema

using (Stream stream = await parquetBlob.OpenWriteAsync())
{
    // Without append: true, this works; but my use case most likely needs append
    using (ParquetWriter parquetWriter = new ParquetWriter(schema, stream, append: true))
    {
        using (ParquetRowGroupWriter rgWriter = parquetWriter.CreateRowGroup())
        {
            rgWriter.Write(table);
        }
    }
}
```
\[1\] https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet-legacy#authenticate-the-client

Thanks for taking the time to read this, any help or insight would be appreciated!

**Comment by aloneguid** [comment]
This is not going to work because `CloudBlockBlock` does not support seekable streams. You will have to create the file locally and then upload to Gen 2 ADLS as the easiest workaround. 
In general, do not try to stream parquet files as they are not designed for it. Append operation is usually desisgned to add large amounts of data > 5000 rows in old days, probably much more today.
