### ISSUE TITLE
Does it support partitioned parquet files?

### ISSUE THREAD

**Issue by yashgt** [aloneguid/parquet-dotnet#72]
Does the library support partitioned parquet files such as shown here: https://aseigneurin.github.io/2017/03/14/incrementally-loaded-parquet-files.html 

Does it support append mode such that files written previously are left intact and new records are added to new partition files?

**Comment by aloneguid** [comment]
There is no such thing as partitions in parquet. Spark performs partitioning but that is for any data format not specific to parquet.

**Comment by yashgt** [comment]
Spark performs the partitioning and writes a parquet file as multiple
partitions. Spark can then read the file as multiple partitions put
together.

Can parquet.net read the multiple partitions as a single parquet file? Does
it have an API function that puts the files together ?

**Comment by aloneguid** [comment]
No, this lib doesn't try to reimplement spark. You have to read multiple files in your code.
