### ISSUE TITLE
Make ClrType on DataField public

### ISSUE THREAD

**Issue by Xtrimmer** [aloneguid/parquet-dotnet#74]
**Version:** Parquet.Net v3.7.7

**Runtime Version:**All

**OS:** All

#### Expected behavior

I'd like to be able to get the `ClrType` and `ClrNullableIfHasNullsType` from a `DataField`. I need to create some items in my app based on the type and cannot easily get to the CLR Type information.

#### Actual behavior

The field is internal and inaccessible

### Steps to reproduce the behavior
https://github.com/aloneguid/parquet-dotnet/blob/develop/src/Parquet/Data/Schema/DataField.cs#L27-L30
The field here is internal, I'd like it to be public as there is a comment above referencing the possibility.

**Comment by aloneguid** [comment]
I think the issue was it wasn't always populated and was a helper field for internal needs. Let me just check, maybe we need a clear comment.

**Comment by Xtrimmer** [comment]
Thanks. I'd love to get a handle on the `ClrType` from the Schema if possible. Currently I am reading in a single rowgroup to get the Types via reflection. It would be nice to be able to get this from the Schema definition.
