### ISSUE TITLE
Appending to file with ParquetConvert.Serialize

### ISSUE THREAD

**Issue by DmitryBaranov1986** [aloneguid/parquet-dotnet#77]
**Version:** Parquet.Net v3.7.7

**Runtime Version:** All

**OS:** All

#### Expected behavior
```csharp
...
var items = new LIst<T>();
ParquetConvert.Serialize(items, someFilePath, append=true)
```

The data from `items` should be appended to the existing parquet file `someFilePath`.

#### Actual behavior

There is no ability to append data to the existing file with ParquetConvert.Serialize

**Comment by AntonioJDios** [comment]
Did you get it?

**Comment by aloneguid** [comment]
Feel free to raise a PR
