### ISSUE TITLE
Unable to write array of strings to parquet file

### ISSUE THREAD

**Issue by konek3** [aloneguid/parquet-dotnet#78]
**Version:** Parquet.Net v3.7.7

**Runtime Version:** .Net Core v3.1 etc.

**OS:** Windows/Linux/MacOSX - Docker

#### Expected behavior

When I want to create column with array of strings type, that column should be created according to repetition levels.

#### Actual behavior

Parquet.Net is creating column with type of "string".

### Steps to reproduce the behavior

1. Create new DataField of type IEnumerable<string>
2. Create data array of type string[]
3. Create definitionLevels array of type int[] in following format: [0, 1, 1 ... 1] or [0, 0, 0, ... 0]
4. Create new DataColumn and apply three variables from above

#### Code snippet reproducing the behavior

```csharp
var dataField = new DataField<IEnumerable<string>>(fieldName);
                    var data = obj.ListProperty.Select(x => x.Id).ToArray();
                    var repetitionLevels = new int[obj.ListProperty.Count()];

                    for (var i = 0; i < repetitionLevels.Length; i++)
                    {
                        repetitionLevels[i] = 0;
                    }

                    dataColumn = new DataColumn(dataField, data, repetitionLevels);
                }
```

**Comment by aloneguid** [comment]
Have you tried to look at samples in unit tests?
