### ISSUE TITLE
contradiction on the documentation for RowGroups number of rows.

### ISSUE THREAD

**Issue by HassanBadir** [aloneguid/parquet-dotnet#80]
hey, just wanted to point a contradiction on the documentation

https://github.com/aloneguid/parquet-dotnet/blob/develop/doc/writing.md

on point number 4 you say that it's preferable that RowGroup contain up to 5'000 rows.

where down at that bottom before "CustomMetaData" you mention a note saying .. 5'0000.

which is correct?

thank you.

**Comment by aloneguid** [comment]
I think 5'000 is more like it
