### ISSUE TITLE
Field name with dot (.)

### ISSUE THREAD

**Issue by felipepessoto** [aloneguid/parquet-dotnet#82]
This commit https://github.com/aloneguid/parquet-dotnet/commit/16b55d54bc7f096eefb9df8227b1f321d9839ee5 added a validation to disallow fields with dots.

Do we really have a reason to don't accept dots? If I comment the throw line I can read a file with dots in column names, and the only failing test is the test that validates if it throws when we use dots.

I couldn't find any spec saying dots are not allowed.

Thanks.

**Comment by kirchsth** [comment]
A dot is the Schema.PathSeparator and used in e.g. paths of StructField's as separator if you store e.g. (list of) structs

**Comment by felipepessoto** [comment]
The problem is, some viewer like ParquetFileViewer can't open the parquet files if column has a dot.

**Comment by felipepessoto** [comment]
Any update? Is this by design? Is it possible to fix it, or have a opt-in option to allow dots?

**Comment by aloneguid** [comment]
Parquet spec does allow dots so Id say we should too.

**Comment by felipepessoto** [comment]
Fixed
