### ISSUE TITLE
Please fix the build pipelines

### ISSUE THREAD

**Issue by mikeblakeuk** [aloneguid/parquet-dotnet#86]
![image](https://user-images.githubusercontent.com/1986660/97283477-ce662280-1837-11eb-8b47-db3a1040263f.png)

#### Expected behavior

Green builds and test badges

#### Actual behavior

Build links are red and don't work. Is https://shields.io/ still used?

### Steps to reproduce the behavior

View the readme.md. check the links

**Comment by aloneguid** [comment]
It just hasn't been built for a while so build history is completely purged , the build pipelines are fine ) I'll start accepting PRS soon

**Comment by aloneguid** [comment]
Working now
