### ISSUE TITLE
Question - Reading current or given row group index as Table

### ISSUE THREAD

**Issue by manums** [aloneguid/parquet-dotnet#89]
**Version:** Parquet.Net v3.7.4

**Runtime Version:** .Net Core v2.1

**OS:** Windows

Existing extension method on ParaquetReader only allows reading all row groups of the reader into a table. It is good to have another extension method that allows reading given row group as0 a table.  New extension method will read only provided row group into table and there by working on small set of data.  

I created Pull request against Elastacloud repository only to realize that repository is not active 
Pull request to other repository - **https://github.com/elastacloud/parquet-dotnet/pull/475**

**Comment by aloneguid** [comment]
Sounds good, Feel free to raise a PR here

**Comment by aloneguid** [comment]
closing as nothing happened
