### ISSUE TITLE
There doesn't seem to be any way to represent a Dictionary in a DataField. 

### ISSUE THREAD

**Issue by dumbnose** [aloneguid/parquet-dotnet#99]
**Version:** Parquet.Net v3.8.4

**Runtime Version:** .Net Core 

**OS:** Linux

#### Expected behavior

I want to write out a column that contains a Dictionary using WriteColumn. 

#### Actual behavior

I don't see any way to do this. MapField can represent the schema. But, it cannot be used with DataColumn.

**Comment by aloneguid** [comment]
I think unit tests have plenty of examples how to write dictionaries.
